### ISSUE TITLE
Woocommerce Plugin Error: Expired invoice button back to store url error

### ISSUE THREAD

**Issue by andres-pinilla** [btcpayserver/btcpayserver#103]
When an invoice expires, the return button does not point to the WooCommerce order.

Point to [bitpayserverurl]/invoices

**Comment by NicolasDorier** [comment]
Ping @lepipele is it this ? https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Views/Invoice/Checkout-Body.cshtml#L299

By the way @lepipele, I noticed that the class name here is `pad` instead of `paid`. Is it normal? https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Views/Invoice/Checkout-Body.cshtml#L239

**Comment by andres-pinilla** [comment]
@NicolasDorier @lepipele Would be ideal an option where you can specify to which link redirects that button once the time expires.

**Comment by lepipele** [comment]
That `href` is wrong because `core.js` updates all `action-button` classes:

https://github.com/btcpayserver/btcpayserver/blob/992d359e790790f5431b198a6bf60fef3d9f1f6a/BTCPayServer/wwwroot/js/checkout/core.js#L36

So you may as well remove it and then expiry should redirect to merchant defined "Website" variable in Store settings.

**Comment by lepipele** [comment]
As for `pad` instead of `paid` - it is: 

https://github.com/btcpayserver/btcpayserver/blob/992d359e790790f5431b198a6bf60fef3d9f1f6a/BTCPayServer/wwwroot/css/normalizer.css#L9228

You @NicolasDorier need to put me in touch with guy who did original version of that Invoice.cshtml along with styles ;)

**Comment by andres-pinilla** [comment]
@NicolasDorier @lepipele Hello, the link is already fixed when the payment is successful, but when the time expires the button has no link.

**Comment by NicolasDorier** [comment]
tracked on https://github.com/btcpayserver/btcpayserver/issues/110
