### ISSUE TITLE
Disable email prompt on the checkout by default

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1084]
**Is your feature request related to a problem? Please describe.**
We've seen the increasing number of users reporting that email asking by default is a very confusing experience for most people.

**Describe the solution you'd like**
Make the checkbox unchecked by default, but don't break it for the users that have it enabled, so apply to newly created stores?

**Describe alternatives you've considered**
The alternative would be:
1. Make the e-mail field a bit clearer in terms of coloring.
2. Add email asking on step two after the invoice is paid

**Provide examples**
![Screenshot 2019-10-10 at 12 09 02](https://user-images.githubusercontent.com/36959754/66664451-d7944980-ec4c-11e9-8660-a5067a7eb1ab.png)
![Screenshot 2019-10-10 at 12 09 24](https://user-images.githubusercontent.com/36959754/66664452-d7944980-ec4c-11e9-8ab3-b8430e398b87.png)
![Screenshot 2019-10-11 at 17 30 15](https://user-images.githubusercontent.com/36959754/66664470-e3800b80-ec4c-11e9-86f1-4fdc5867c924.png)

**Comment by ErikDvorcak** [comment]
Can I help you with this?

**Comment by pavlenex** [comment]
Of course, @ErikDvorcak feel free to tackle it 🥇

**Comment by bolatovumar** [comment]
Looks like our guy is AFK. @NicolasDorier do we have an ACK for this? If so, then do we just wanna disable it by default for all new stores or do we wanna take additional action to reduce confusion?

I'm thinking clarifying the text could help. Also, making the e-mail input more prominent by putting it right below the "Contact & Refund email" heading instead of at the very bottom could help. Making the "Contact & Refund email" heading larger and more visible could help. Also, changing "Contact & Refund email" to "Enter your email to proceed" or something similar could help.

@astupidmoose have you ever used this featured and had customers confused about it?

**Comment by astupidmoose** [comment]
@bolatovumar We use the woocommerce plugin which automatically passes this to btcpay so it's not required from the customer. 

This is likely for donations or the "pay" button where no info is provided to btcpay.

**Comment by NicolasDorier** [comment]
@bolatovumar yeah concept ACK, I did it since it is a one line change (I may have broke the tests though... on it)
