### ISSUE TITLE
Close button for modal is broken

### ISSUE THREAD

**Issue by skddc** [btcpayserver/btcpayserver#1093]
**Describe the problem/bug**
When using the checkout modal dialog, it should show a "close" button, instead of "Return to [sitename]". However, it shows the latter button, which can break the checkout experience.

**Your environment**
* Version of BTCPay Server: Latest
* Deployment method: Manual

**To Reproduce**
* Pay invoice via modal dialog
* See if button is close button, or a link to the store URL

**Expected behavior**
It should show a close button.

**Actual behavior**
It shows a button link to the store URL.

**Additional context**
I think https://github.com/btcpayserver/btcpayserver/commit/9a9e31c759175cb34ff6b4e64320a17bc79eb5b7#diff-996cc28a55e53c44d56d4bda0fbe3dee is the commit that broke this feature. Reverting to the release before that commit fixed the problem for us.

**Comment by bolatovumar** [comment]
@skddc could you describe this in more detail? How does one launch the checkout modal dialog? I could take a look at this issue but having a problem reproducing it.

**Comment by NicolasDorier** [comment]
Ping @Kukks . @bolatovumar you can open it by clicking on the `^` in the invoices page.

**Comment by pavlenex** [comment]
I am unable to replicate this, or maybe I am misunderstanding the issue.

What you're saying is, when the invoice is paid, instead of the `return to website` button, you'd like to see `Close button`, correct?

@bolatovumar check below how to see the modal invoice.

![modal](https://user-images.githubusercontent.com/36959754/67617937-b2750e80-f7e8-11e9-909a-7950324f9b0e.gif)

Or are you reffering to Payment requests @skddc, because indeed, I've noticed that on payment requests, the button says return to store , but instead closes it, which makes sense, since payment request is your store, but would maybe make sense to say `close` instead.

**Comment by skddc** [comment]
The one that says "Return to store.btcpayserver.org" is supposed to be a close button, and not a link. Then link will actually open the store URL within the frame of the modal window, which doesn't work with proper security attributes anyway, and it's not supposed to link to a different page/URL in the first place.

This worked before the front-end code was changed in https://github.com/btcpayserver/btcpayserver/commit/9a9e31c759175cb34ff6b4e64320a17bc79eb5b7#diff-996cc28a55e53c44d56d4bda0fbe3dee which is the commit that broke it.

These are the specific lines of code that stopped working correctly:

https://github.com/btcpayserver/btcpayserver/blob/43ee22f965ecf50f0c080c96492ed9846b51fe05/BTCPayServer/Views/Invoice/Checkout-Body.cshtml#L406-L412

And here's the code from after the commit that I think introduced the regression:

https://github.com/btcpayserver/btcpayserver/blob/9a9e31c759175cb34ff6b4e64320a17bc79eb5b7/BTCPayServer/Views/Invoice/Checkout-Body.cshtml#L205-L211

**Comment by pavlenex** [comment]
Ok I understand now.
This is something for you @Kukks ;)

**Comment by bolatovumar** [comment]
Ok, I figured out what the issue is. When you first open the invoice in a modal, the `isModal` flag is correctly set to `true`, however, when the invoice is paid and you move to the success screen, the `isModal` flag is erroneously set to `false` causing the wrong button to render. I will take a look into fixing it. @Kukks would probably be able to fix this very quickly since he made that change lol.

**Comment by bolatovumar** [comment]
To follow up, the reason this doesn't work is because the `GetStatus` method in `InvoiceController.UI.cs` returns the model without checking if we are in the modal view so the `IsModal` flag is `false`. We need to check if we are in the modal view in the `GetStatus` method. I tried doing it the same way as in the `Checkout` method but it doesn't seem to work. I'm sure @Kukks knows exactly how it should be done.
