### ISSUE TITLE
Spanish string missing

### ISSUE THREAD

**Issue by andres-pinilla** [btcpayserver/btcpayserver#111]
Hello, the word transaction at the time of checkout is still to be translated.

The correct word is: transacción

<img width="364" alt="captura_de_pantalla_2018-04-10_a_la_s__11_55_51_a__m_" src="https://user-images.githubusercontent.com/29980213/38571631-a3aa4dd2-3cb6-11e8-8e9d-d045b239b32f.png">

Thanks,

Andrés

**Comment by lepipele** [comment]
@NicolasDorier you OK with me changing:

https://github.com/btcpayserver/btcpayserver/blob/77b42eb0855f378e7f15bee7389bf74a072ccf0b/BTCPayServer/Controllers/InvoiceController.UI.cs#L241

And changing `NetworkFeeDescription` field into `TxFee` and then forming string on client side (since we have other two fields already in the model?

**Comment by NicolasDorier** [comment]
yep should be done that way

**Comment by andres-pinilla** [comment]
Spanish:

Transacción
Transacciones —> Plural

**Comment by lepipele** [comment]
Thanks man! Added in commit: https://github.com/btcpayserver/btcpayserver/pull/117/commits/75099b99d4d8de0c7d6d8bc5946ae3a8a4eae947

@Saevar2000 @junderw @LinoxBE @pajasevi can you send me how those two words translate to languages you guys did? @NicolasDorier can do french ;) And we need someone for German... that's still missing on: https://github.com/btcpayserver/btcpayserver/issues/89

**Comment by NicolasDorier** [comment]
Fixed by https://github.com/btcpayserver/btcpayserver/pull/117 let's open new issue for the translation.
