### ISSUE TITLE
Errors not working in Apps 

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver#1141]
**Describe the problem/bug**
Some Apps errors are not working properly

**Your environment**
* Version of BTCPay Server: BTCPayServer v1.0.3.137
* Deployment method: LunaNode

**To Reproduce**

**Crowdfund** (Update App without required fields)
1. Click View App without required fields provided.
2. Page always shows "A Target Currency must be set for this app in order to be loadable."
3. Even if missing required field is something like not providing Description or Title

**POS** (Pay invoice without wallet connected to store)
1. Create POS without wallet 
2. Try to pay POS invoice
3. 500 error page

**Expected behavior**
Crowdfund - Missing required fields should not allow them to continue, right?
POS - Normally there is a warning, you need to connect wallet (like crowdfund does).

**Additional context**
I think this was not happening before.

**Comment by bolatovumar** [comment]
> POS - Normally there is a warning, you need to connect wallet (like crowdfund does).
Shouldn't there be a check when you assign an app to a store to make sure that store actually has a wallet connected to it? If there isn't a wallet, it shouldn't let you connect and give you a message as to why. This way you will never get to a stage where you created an app, tried to pay for something and got a 500 (or a warning in the UI). Same goes for the crowdfund app.

**Comment by britttttk** [comment]
> > POS - Normally there is a warning, you need to connect wallet (like crowdfund does).
> 
> Shouldn't there be a check when you assign an app to a store to make sure that store actually has a wallet connected to it? If there isn't a wallet, it shouldn't let you connect and give you a message as to why. This way you will never get to a stage where you created an app, tried to pay for something and got a 500 (or a warning in the UI). Same goes for the crowdfund app.

Normally the user can build the app before connecting a wallet. For why, I think an example is like if you are collaborating with a company, you can design the app and show it to them, before obtaining their xpub. This is the error for CF without wallet. 

I thought before, it was a text warning displayed on the page that opened, but I don't remember. This is how it is for CF. 

![image](https://user-images.githubusercontent.com/39231115/68538247-92883380-032e-11ea-8c23-c83596a77960.png)

**Comment by bolatovumar** [comment]
>Normally the user can build the app before connecting a wallet. For why, I think an example is like if you are collaborating with a company, you can design the app and show it to them, before obtaining their xpub.
You can always just use a throwaway xpub for this purpose. I still think there should be a check that makes sure a store has a wallet connected to it before allowing you to connect an app to a store. If there is a check then this bug is avoided entirely for both the PoS and the Crowdfund apps.

**Comment by Eskyee** [comment]
You can always just use a throwaway xpub for this purpose. I still think there should be a check that makes sure a store has a wallet connected to it before allowing you to connect an app to a store. If there is a check then this bug is avoided entirely for both the PoS and the Crowdfund apps.

I think adding a throwaway xpub will just confuses new users, keeping it simple with just a warning sign is a good idea I think!!

I like making Apps or crowdfund just for testing ideas out, before adding a xpub store.

![Screenshot 2019-11-14 at 11 03 43](https://user-images.githubusercontent.com/30862925/68852244-70483a00-06cf-11ea-942a-6677960b30ff.png)

![Screenshot 2019-11-14 at 11 04 05](https://user-images.githubusercontent.com/30862925/68852277-79d1a200-06cf-11ea-9bab-e6c1975a3589.png)

![Screenshot 2019-11-14 at 11 04 59](https://user-images.githubusercontent.com/30862925/68852364-9ff74200-06cf-11ea-9fc5-f15e890d7ba2.png)

![Screenshot 2019-11-14 at 11 06 19](https://user-images.githubusercontent.com/30862925/68852379-a5ed2300-06cf-11ea-82ca-a7e3e0a22861.png)

![Screenshot 2019-11-14 at 11 06 46](https://user-images.githubusercontent.com/30862925/68852395-ad143100-06cf-11ea-8a1d-de9589b6ecec.png)

![Screenshot 2019-11-14 at 11 07 15](https://user-images.githubusercontent.com/30862925/68852416-bbfae380-06cf-11ea-8811-6257615215ff.png)

This last screenshot should just be a simple warning!! not this.. dev info warning 

connecting a wallet should be a choice??  until the user is happy with content building!!
then he or she will need their wallet connected, to their store for payments.

just a idea

**Comment by NicolasDorier** [comment]
checking that now

**Comment by NicolasDorier** [comment]
Fixing like this:

![image](https://user-images.githubusercontent.com/3020646/68855114-e923b200-0720-11ea-8e07-af317822298c.png)

**Comment by NicolasDorier** [comment]
> Missing required fields should not allow them to continue, right?

Well it should, because anyway, even if we did not allow them, nothing prevent them to remove their derivation scheme AFTER having create the app.

**Comment by pavlenex** [comment]
@NicolasDorier that one looks okay, however the two one we had are a bit confusing.
I know @britttttk told me she'd like to try to fix them, but may need some guidance on how to approach them, what's the best way to tackle them.

**Comment by NicolasDorier** [comment]
Just finished fixing it. A bit hackish though.

What I did is not very clean: If you modify the form to be valid, but click on View App instead of Save,  it will still redirect you on the page you saw.

A complete fix would be to not show the View App buttons if the apps are not fully configured.

**Comment by pavlenex** [comment]
@britttttk do [57a694 ](https://github.com/btcpayserver/btcpayserver/commit/57a69495659262a20d8317b071816df69262edfc) and #1161 close this issue, or are there other things to address?  If not, please close.
