### ISSUE TITLE
Missing payments 

### ISSUE THREAD

**Issue by delapex** [btcpayserver/btcpayserver#1177]
Hello!
 
1) we have self-hosted btcpayserver
2) we create new shop and connect our electrum wallet to it
3) we open general setting -> Derivation Scheme -> modify
4) we use multi sign legacy wallet, that's why we select 2-of-xpub1...-xpub2...-[legacy]
5)  in electrum we have 3 xpub keys (cosigner1, cosigner2, cosigner3). We use standart multisign model 2/2
6) we enter 2-of-1st xpub key (cosigner1)-2nd xpub key (cosigner2)-[legacy]
7) after that we must Confirm the addresses (BTC), but we don't do that (our fault) and save Derivation Scheme with 2 keys. I was thinking that we can enter ANY 2 xpub keys (cosigners) of those 3 that we have.
8) Сustomer make payment but we don't see money on our electrum (Wrong derivation scheme)
9) we can see money only in btcpayserver wallets

We trying send money from wallet but our seed invalid for sign
Is there any way to return the money to us or to the client (payback)?

**Comment by pavlenex** [comment]
To replicate:
1. Create legacy multisig wallet 2 of 3 multisg in Electrum.
2. In BTCPay add only 2 xpubs, which means 2 of 2 and different address.
3. Without checking save.

Now you have 2 of 2 in BTCPay which can't be spent from Electrum and not a proper UI to spend it from BTCPay itself.

**Comment by pavlenex** [comment]
To sum up, I have not tried it yet, but I believe if you have a seed to both of the xpub's, you can create a 2 of 2 legacy wallet with those seeds in Electrum and it should be there.

**Comment by pavlenex** [comment]
So the issue here was that they used 2FA wallet. 2FA shows 3 xpubs. They've then input first two xpubs into BTCPay multisig and locked it into 2/2. 

We were able to retrieve the funds since we managed to restore the wallet, but disabled two 2FA upon restoring, retrieved the two xprivs from the text file and since we owned the two keys it was possible to sign and spend. Funds are SAFU, so closing this.
