### ISSUE TITLE
popper js error

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#1210]
This error happens sometimes after confirming passphrase on the vault. It screw up the js on the page when it does, and it is not deterministic.

![image](https://user-images.githubusercontent.com/3020646/70022665-51efa300-15d8-11ea-8434-39e3e1b76cad.png)

Any idea @rockstardev @Kukks @dennisreimann @bolatovumar ?

**Comment by dennisreimann** [comment]
My first guess is that this might be a bundling error like where the import order of dependencies matters. I don‘t know which bundle this is but can you try moving jQuery above popper.js/bootstrap so that it is present when the lib initializes?
Weird error nevertheless, I‘ll need to take a closer look at the code to see what‘s going on.

**Comment by NicolasDorier** [comment]
popper.js is already after jquery

**Comment by NicolasDorier** [comment]
After updating popper, I get another error

![image](https://user-images.githubusercontent.com/3020646/70110210-a1de7080-1691-11ea-83ad-ee2acb6caeaa.png)

Stepping in the source, that's the same issue. I tried to browse internet, but sadly lot's of people same issue no solution....

**Comment by NicolasDorier** [comment]
Probably happen because I was annotating an element which is not a popper as a popper.
