### ISSUE TITLE
Invoice Email Notification / Invoice IPN Notification - add placeholder

### ISSUE THREAD

**Issue by escapedcat** [btcpayserver/btcpayserver#1222]
![image](https://user-images.githubusercontent.com/1016218/70563577-c6a17f00-1b8e-11ea-94f3-8384dd9ccbc9.png)
(renamed to "IPN Notification" after #1199)  

For me it was not clear that I can put an email-address in the field. I suggest to add a placeholder like this to help people understand this:
![image](https://user-images.githubusercontent.com/1016218/70563744-1122fb80-1b8f-11ea-8c78-660f00ed18bc.png)

Would it also be helpful to explain what "IPN" means? I have no clue. 

I can help with this if wanted.

**Comment by pavlenex** [comment]
IPN is for developers, normal users should not use this. It should not be clear to them since they'll then expect something that they won't receive.

**Comment by escapedcat** [comment]
Should thsi be somewhat explained? I feel liek most of the inputs/options on that page a quite self-explaining but IPN isn't. What does IPN stand for?

**Comment by pavlenex** [comment]
[IPN](https://en.wikipedia.org/wiki/Instant_payment_notification) stands for - Instant payment notification.

I really have no idea how we can improve this, I re-named it purposefully so it does not remind people that they can get email, developers should know what this is, so I'm against putting a label, since people will again connect it with email and think they'll get an email where in fact they're getting bunch of scattered JSON IPN calls for each status change. If someone wants, he can document it in docs repo and put a tooltip in the UI but don't but `e-mail` label please.

**Comment by escapedcat** [comment]
Hm, I understand. No email hint it is ;)  

If people want to use it for this purpose in a way this field will take an email-address, yes? To receive a bunch of JSON via email? Sounds kinda weird.   

How do developers use this (field)?   
Maybe the usage could be explained using a ![image](https://user-images.githubusercontent.com/1016218/70565147-c951a380-1b91-11ea-94cf-b0320383daf0.png) to the docs.

**Comment by pavlenex** [comment]
> If people want to use it for this purpose in a way this field will take an email-address, yes?

Yes, this field is for e-mail, but I wouldn't label it since then we get confusion.

> How do developers use this (field)? =

I think @Kukks  added this for someone who requested it, unsure of the use-case. IMO this field would better be used for merchants to get emails or send emails, this way it's just confusing for non-devs.
