### ISSUE TITLE
Removing PaidOver for small amount?

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#1255]
Lightning 0.8.0, for privacy reason, is never sending the exact amount the merchant is asking for. It always send a bit more.

This mean that all c-lightning starts to be PaidOver, this unnecessarily ring bells for merchants.
I propose to extend the meaning of this field.

![image](https://user-images.githubusercontent.com/3020646/71799818-a71c4a00-3099-11ea-8fbb-04e0744fd5a8.png)

Where, if the user pay x % more, the merchant does not get bothered by it.
Or maybe just add a new field, with a proper default so by default lightning payment does not trigger paidOver.

**Comment by Kukks** [comment]
We already have the payment tolerance option that does this though?

**Comment by pavlenex** [comment]
Is this c-lightning, LND or both? If the invoice is slightly over-paid merchants in general don't care. It would be red alert if it was under-paid.

So you're proposing to entirely remove paid over for smaller amounts, in this case what is considered slightly smaller?

Adding a new field with a proper default sounds better to me, because this may mess with accounting if we blindly accept it without notifying the user. Though they'd see the overpaid amount when exporting the invoice.

**Comment by NicolasDorier** [comment]
@pavlenex maybe we should just ignore this problem until somebody actually complain?

**Comment by NicolasDorier** [comment]
This is only c-lightning doing it. Would not be surprised if one day LND does.
I think this is a bad decision.

**Comment by pavlenex** [comment]
Let's leave this one for discussion so that people are aware of it, imo this kind of privacy solution will cause more problems than do good.

**Comment by woutersamaey** [comment]
Us there no way to turn the privacy option on/off? That way the merchant decides if he want to deal with this shit or not.

**Comment by NicolasDorier** [comment]
@woutersamaey this is the customer which decide whether this feature is used or not.

**Comment by pavlenex** [comment]
Closing due to no complaints on this end. Will re-open if someone reports that this is the issue, does not seem to happen in versions we're using for now.
