### ISSUE TITLE
Adding comment on wallet transactions causes 500 error

### ISSUE THREAD

**Issue by mondoir** [btcpayserver/btcpayserver#1280]
**Describe the problem/bug**
I updated to the latest release. Now when I try to comment on a transaction in a wallet, it gives error 500.
Strangely, if you try to add a Label first and then a comment, it works fine.

**Your environment**
* Version of BTCPay Server: latest
* Deployment method: Lunanode

**Logs (if applicable)**
Basic logs can be found in Server Settings > Logs.

**To Reproduce**
1. Go to Wallets->Transactions
2. Click on Speech Bubble and write something
3. Click on Save Comment
4. See error 500 as bellow

**Expected behavior**
Should save the comment?

**Actual behavior**
Produced error 500

**Screenshots/Links**
<img width="638" alt="Screenshot 2020-01-14 at 22 49 19" src="https://user-images.githubusercontent.com/56967158/72389366-1e984c00-3720-11ea-83e5-f57adef36167.png">

**Additional context**
If you try to add a Label first and then a comment, it works fine.

**Comment by bolatovumar** [comment]
Looks like an Entity Framework issue again. I looked into it but I can't figure it out as I don't know EF well enough. And now I can't even repro it since adding a label once to any transaction seems to fix it. 

The error that gets thrown is exactly the same as this one: https://stackoverflow.com/questions/43359631/entity-framework-core-error-postgres-violates-foreign-key-constraint

**Comment by britttttk** [comment]
I'm able to reproduce this issue as well.

**Comment by NicolasDorier** [comment]
on it
