### ISSUE TITLE
 "Forgot your password?" and email didn't arrived

### ISSUE THREAD

**Issue by Amiga500** [btcpayserver/btcpayserver#1312]
**Describe the problem/bug**

I lost password to login into website. i pressed into "Forgot your password?" and put my email. I receive:
Email sent!
Please check your email to reset your password.

But no email was sent (checked into spam directory too)

--------------------------------------------------------------------------------------------------------------

**Your environment**
* Version of BTCPay Server:
* Deployment method: 
* Other relevant environment details:

**Logs (if applicable)**
Basic logs can be found in Server Settings > Logs.

**To Reproduce**

**Expected behavior**

**Actual behavior**
Tell us what happens instead

**Screenshots/Links**
If applicable, add screenshots or links to help explain your problem.

**Additional context**

**Comment by pavlenex** [comment]
If this is your self-hosted BTCPay Server, you can [reset the password in database](https://docs.btcpayserver.org/faq-and-common-issues/faq-serversettings#forgot-btcpay-admin-password)

The reason you did not receive email is because [SMTP settings have to be configured](https://docs.btcpayserver.org/faq-and-common-issues/faq-serversettings#how-to-configure-smtp-settings-in-btcpay) either by you or a third-party host.

In case you're using a [third-party BTCPay host,](https://docs.btcpayserver.org/deployment/thirdpartyhosting) you can either contact them and see if they can configure their SMTP, or just re-create a new account with them.

**Comment by Amiga500** [comment]
Thanks! I'll try
