### ISSUE TITLE
Checkout page to show when transaction is confirmed.

### ISSUE THREAD

**Issue by Transisto** [btcpayserver/btcpayserver#1319]
Most services will only trigger an action when the transaction is confirmed and it's usually a customer service nightmare to respond to people asking if their transaction is confirmed or not.

**Comment by bolatovumar** [comment]
@Transisto could you clarify what you are suggesting? BTCPay already has settings which allow you tweak when the invoice is considered paid:

![Screen Shot 2020-02-04 at 8 46 30 PM](https://user-images.githubusercontent.com/1934678/73811875-92fa6400-478f-11ea-833c-1fe1c29ef5c9.png)

You can also choose if you want the user to be redirected after invoice is paid:
![Screen Shot 2020-02-04 at 8 46 45 PM](https://user-images.githubusercontent.com/1934678/73811894-a9082480-478f-11ea-9595-7c134a5e62c1.png)

**Comment by Transisto** [comment]
I mean the business has to be the one to let the customer know when the
invoice is actually paid, because btcpay invoice show "paid" the second it
sees something in the mempool.

**Comment by pavlenex** [comment]
There's a difference between [paid and confirmed status](https://docs.btcpayserver.org/features/invoices#invoice-statuses).

Alternatively, you can send follow up emails based on different status either via your CMS or use [BTC-Transmuter](https://github.com/btcpayserver/btcTransmuter).

**Comment by Transisto** [comment]
@pavlenex, for example our website monitors the invoice status charge to
trigger the service but now we have to build a UI component and callback to
it so the customer can monitor the progression of it's transaction on chain.

The generated customers invoices themselves could show status change when
they are considered paid from the merchant standpoint instead of just the
mempool standpoint.

**Comment by pavlenex** [comment]
No, we can't conflict statuses like that but I see what you would want. 

You'd want when invoice is paid (but not confirmed) to show XYZ message, for example "Your invoice has been paid and now awaiting confirmation on the blockchain". And then when completed "Your invoice has been confirmed on the blockchain." I still don't quite understand why we'd want to do this since people paying with BTC would already know how to check transaction from their wallets, it's more likely even that they will check it their wallets than in the invoice URL.

Please alter your initial post if you want this as a feature request and clearly explain what is it that you're suggesting by following the [Feature Request template ](https://github.com/btcpayserver/btcpayserver/blob/master/.github/ISSUE_TEMPLATE/feature_request.md)so we can easier understand.

I still recommend your customers about this via email, it's way more convenient, people don't really keep the invoice tab opened after they pay it.

**Comment by pavlenex** [comment]
I've been thinking about this a bit and here are my ideas on how we can tackle it.

When an invoice is paid on-chain show something similar to this:

![Waitingconf](https://user-images.githubusercontent.com/36959754/75021481-c1b55180-5494-11ea-86bb-64f2f7722ac7.png)
![yellow waiitng](https://user-images.githubusercontent.com/36959754/75021482-c2e67e80-5494-11ea-89e0-b4cef0a01310.png)

The tooltip should show hover-over text that will concisely explain this and perhaps. I would not do a link to btcpay docs since this will attract customer support questions that merchants needs to handle, not us.

What concerns me here is that buyer may get a feeling that they need to stay on this page because something is "loading". I have no clue how to sort this except: show somewhere text that the page can be closed 

@Transisto is this what you had in mind?

**Comment by pavlenex** [comment]
related #1330

**Comment by Transisto** [comment]
@pavlenex Yes, pretty much this. Great design!

**Comment by chewsta** [comment]
Regarding my PR for this issue, I didn't add the tooltip to payment pending confirmation as I wasn't sure what the text should read as.

**Comment by woutersamaey** [comment]
> I still recommend your customers about this via email

Just wanted to add that we now have a Zapier integration that can make this very easy. Notify them by email or any other service that your customer may be on that Zapier offers. More info at https://github.com/btcpayserver/zapier

**Comment by Bersh1** [comment]
I hope that
