### ISSUE TITLE
Introduce "Update available" alert 

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#1420]
So many users stay on very outdated versions. We should add a small alert that shows up when the version shown on BTCPay does not match the latest release tag on github/ docker hub. 

 This should be optional with a flag of some sort `BTCPAY_UPDATE_ALERT`, which is off by default.

In the docker repo, we should turn it on by default, UNLESS `BTCPAY_IMAGE` is specified, which will turn it off

**Comment by pavlenex** [comment]
Not quite sold on this one. People who don't regularly maintain their server are the ones who connect it, and never visit it unless something breaks, in that case they'll update anyway. I think it's been discussed many times and general idea is that we should not urge users to update in any way, since it's a recipe for a mass breaking of servers in case of a bug. On the other hand, it can be good for critical bug-fixes and security patches. Really not sure.

If we decide this is a good idea however, I suggest we look into hooking it up with #775 as a way of displaying.

Kinda related to #1385

**Comment by woutersamaey** [comment]
You can make this very small and put it next to the current version number in the admin.

Something like:
Current version is 1.2.3 - An update is available

Doesn't need to be a big popup.

**Comment by Eskyee** [comment]
I agree with kukks their are a lot of users I see using old versions of BTCPayserver, given more version information details , might help those update to the latest version more often! & might help to cut down on support for old versions!!

**Comment by pavlenex** [comment]
Related #775 #1542
