### ISSUE TITLE
Update Invoice creation UI to highlight selected cryptocurrency/network

### ISSUE THREAD

**Issue by auldsyababua** [btcpayserver/btcpayserver#152]
![currency_choice](https://user-images.githubusercontent.com/18078607/39556644-95da6124-4e36-11e8-9eb5-70d017ddcfa6.PNG)

When a user chooses between BTC, LTC, BTC-LN, or LTC-LN, there is nothing to indicate what choice is currently selected except for the currency calculation below changes to either BTC or LTC, but even that does not indicate if its on-chain or lightning. Have the selected network either highlight or enlarge once chosen would provide a smoother UX.

**Comment by bitcoinuser** [comment]
I agree.

**Comment by rockstardev** [comment]
I suggested we go with DropDown list because that will allow us to also have text which will serve to better describe currency. This will also prevent confusion for BTC Lightning Network payment icons.

**Comment by rockstardev** [comment]
OK crew, update on this:

![currency-selection-improved-with-names](https://user-images.githubusercontent.com/5191402/42713569-97858168-86b5-11e8-83b5-570e98dde86e.jpg)

I needed to go with completely custom popup. I'll talk with @NicolasDorier on specifics on where we will be fetching currency names, but once that's decided we'll probably have pretty fast push to production. If anyone wants to test before push let me know.

And also one question for crowd on issue - should we aim to localize currency names? I.e. instead of English names (like Bitcoin, Litecoin) we can support local names for all that, like (google translate Japanease):

- ビットコイン (BTC)
- リテコイン (LTC)
- ビットコイン雷 (BTC)

?

**Comment by artlav** [comment]
This does not feel right - looks like it's Bitcoin fork number 37, rather than Bitcoin using lightning.

What about them having the same icons and being one under the other?

**Comment by NicolasDorier** [comment]
I think it is ok to not translate currency names.
I agree for same icon, one under the other (but please, put the lightning logo on the right if possible :D)

**Comment by rockstardev** [comment]
@NicolasDorier I already fixed the ordering:

https://github.com/rockstardev/btcpayserver/commit/464ab30feacc6bf8e9d626e3ba8b3189c4a85dab

I wasn't thinking too much about it - yet somehow this seemed to become the biggest issue in comments ;).

**Comment by LinoxBE** [comment]
For Lighting we can maybe use the text

Bitcoin (BTC) using Lightning Network

or something similar. It makes it clear that it’s still Bitcoin and not fork 37. But another layer/transport.

**Comment by bitcoinshirt** [comment]
I am with @artlav, this does not feel right for me either. Lightning looks like an altcoin, and I really don't see how people are going to be aware that they can pay in multiple currencies.

My suggestion is to make Lightning Network and Bitcoin integrated, it just does not make sense to separate them in any way. Based on the feedback from our customers, one of the biggest complaints with the checkout was that they have no idea how to pay through the LN since the icon itself is not recognizable (sorry @NicolasDorier I know it hurts).

I suggest that we use a very clever design with a **toggle**, which I suggested on slack in May.

![screen shot 2018-07-14 at 00 05 54](https://user-images.githubusercontent.com/36959754/42722184-ea935c9e-8747-11e8-919f-eda89ced82c4.png)

In my opinion, this sort of design for Bitcoin/Lightning seems natural. Also, the tooltip is great UX.

Now for the altcoins, I'd either just l**eave those as icons** (their logos are recognizable) or just use them in the same way as in the example above. Maybe @astupidmoose can chime in with his experience since he accepts altcoins. 

The drop-down certainly does not seem natural, though, since we only accept Bitcoin, I'm fine with that.

On another note, is there any good reason why we still need a "refund address field"? Woocommerce invoice already has that info in case I'd want to reach out to the customer.

**Comment by NicolasDorier** [comment]
(T-T)

**Comment by NicolasDorier** [comment]
The refund address field can be actually disabled. Also it does not show if it is passed by Woocommerce.

**Comment by astupidmoose** [comment]
I don't mind having it as a separate button, although I really liked the radio button idea. 

My main concern with above is there doesn't appear to be a way to indicate you can select the dropdown. I don't want to have a bunch of "How do I pay with LTC" questions etc. 

If there dropdown exists, it needs to have an indicator that it exists

**Comment by rockstardev** [comment]
@astupidmoose I added one more indicator to make it obvious it's clickable. It kinda works same like for that expansion (also has transition for hover). Provided more details on:

https://twitter.com/r0ckstardev/status/1019446888469233664
