### ISSUE TITLE
Can not see original deposit address on expired invoices anymore 

### ISSUE THREAD

**Issue by Uter1007** [btcpayserver/btcpayserver#1541]
**Describe the problem/bug**
When using older versions of btcpay, I could always search for the wallet addresses that have been used on the invoice even when invoice got expired. Now expired invoices get not monitored anymore and I don't know which addresses where sent out to the customers. 

**Your environment**
* Version of BTCPay Server: 
* Deployment method: 
* Other relevant environment details:

 BTCPayServer v1.0.4.2

**To Reproduce**
1. Create Invoice
2: Let it expire
3: Look Details for expired Invoice
4: Can not find the information what is the actuall used wallet address for this invoice

**Expected behavior**
To see the used address - in a perfect world it would be also amazing to see the number of the derived key that was used. 

**Actual behavior**
No infos about the used address

**Comment by NicolasDorier** [comment]
Ping @pavlenex , I think this was because we wanted to only show actual payments and not "current addresses". Maybe should have an additional table in invoice details for that.

**Comment by pavlenex** [comment]
@NicolasDorier In #1056 The issue was that a `paidPartial` invoice that has a `Paid` column and shows an unused address can lead to a false conclusion, leading the merchant to think the unused address is the one customer paid to. I detailed the issue in this [comment](https://github.com/btcpayserver/btcpayserver/issues/1056#issuecomment-536040956). [Your suggestion ](https://github.com/btcpayserver/btcpayserver/issues/1056#issuecomment-575026800 )was to show only which you did in #1283 and when @Kukks asked you said it's possible to see the [current address](https://github.com/btcpayserver/btcpayserver/pull/1283#issuecomment-575445216) once the invoice details are expanded.

I do remember us having a discussion which I am unable to find a reference to that perhaps we need to have paid address and unused address and present them as a separate entity in the invoice page.

I don't understand a particular use-case here, so I am only guessing that a customer shares an address with a merchant that has expired. But why would a customer share an address that he hasn't been paid to? 

@Uter1007 can you explain the exact use-case and workflow here so that we can understand better why this piece of information is useful and how we can show it.

My opinion is that we need to show both unused and paid address, but we must handle them as a separate and properly labeled entities. 

This is where we showed them in past and it's a really bad UX.

![65790974-08f71a80-e161-11e9-8ef5-b857b0da050c](https://user-images.githubusercontent.com/36959754/80924923-50472880-8d8c-11ea-8375-87276cda4385.PNG)

**Comment by Uter1007** [comment]
The use case is that people are asking always if transaction went trough. We are faced with some real beginners in the bitcoin sector and they are using weird online wallets that are sending transactions really late (maybe they are batching it, dont know exactly). So the problem is when the customer has no txId and I don't know the deposit address - I am not able to analyze anything on the chain. Thx for your quick responses ! Cheers ;)

**Comment by Uter1007** [comment]
An addtional use case is to fix the gap problem when you have a lot of expired invoices and you are using an online wallet like blockchain.info you are running out of sync because you can only watch 15-20 addresses -- so a typical fix would be to send a real small amount on this addresses to close the gap -> also not possible if you don't know the openend addresses.

**Comment by pavlenex** [comment]
While the first use-case makes little sense because btcpay would detect the payment to those invoices, I understand you have a workflow here. Second use-case makes more sense.

Okay, as far as I am concerned, we can bring back the `unused back`in, but in a way they are clearly distinguished and don't cause UI confusion for people.

**Comment by astupidmoose** [comment]
I'm going to agree with @Uter1007 here and say that the removal of this information from the addresses is a hindrance to the workflow for a merchant who is looking to solve issues with customers. 

Often we receive a "we sent payment" and although we know this to be true as BTCPay has not detected it, a quick and easy reference to the addresses in question was super helpful. It's basically a "here's the address we needed you to send to, look its empty". 

I realize this is available in the invoice list as @Kukks pointed out to me in the chat, but honestly it wasn't "obvious" to me and I think UX wise it should be listed on the invoice summary as before. Also, the addresses in the invoice list are concatenated so any longer addresses are not possible to lookup that way. We should display the full address even at the expense of UI's "prettyness".

**Comment by Kukks** [comment]
> I'm going to agree with @Uter1007 here and say that the removal of this information from the addresses is a hindrance to the workflow for a merchant who is looking to solve issues with customers.
> 
> Often we receive a "we sent payment" and although we know this to be true as BTCPay has not detected it, a quick and easy reference to the addresses in question was super helpful. It's basically a "here's the address we needed you to send to, look its empty".
> 
> I realize this is available in the invoice list as @Kukks pointed out to me in the chat, but honestly it wasn't "obvious" to me and I think UX wise it should be listed on the invoice summary as before. Also, the addresses in the invoice list are concatenated so any longer addresses are not possible to lookup that way. We should display the full address even at the expense of UI's "prettyness".

ACK from my end, we should never have removed that data imo.

**Comment by bolatovumar** [comment]
So what is it that we want to do here? Looks like the address is available in the invoice summary.

![Screen Shot 2020-10-11 at 1 41 58 PM](https://user-images.githubusercontent.com/1934678/95689774-f1ea6580-0bc7-11eb-809b-5c679f97518e.png)

![Screen Shot 2020-10-11 at 1 51 52 PM](https://user-images.githubusercontent.com/1934678/95689904-f6634e00-0bc8-11eb-9bd9-aa1314a407f7.png)

Or is this issue specific to partially-paid invoices?

Also, regarding @astupidmoose's comment about
> We should display the full address even at the expense of UI's "prettyness".

Do you mean this (highlighted below)? If so, it looks like if you copy the address it copies the full address. Or do you prefer to see the whole address anyway for quick visual reference?

![Screen Shot 2020-10-11 at 1 32 37 PM](https://user-images.githubusercontent.com/1934678/95689918-05e29700-0bc9-11eb-8ae3-8f92ff205d72.png)

**Comment by astupidmoose** [comment]
> Also, regarding @astupidmoose's comment about
> 
> > We should display the full address even at the expense of UI's "prettyness".
> 
> Do you mean this (highlighted below)? If so, it looks like if you copy the address it copies the full address. Or do you prefer to see the whole address anyway for quick visual reference?
> 
> ![Screen Shot 2020-10-11 at 1 32 37 PM](https://user-images.githubusercontent.com/1934678/95689918-05e29700-0bc9-11eb-8ae3-8f92ff205d72.png)


I didn't realize that copying and pasting took the whole address. With that functionality in place this part is no longer an issue to me.

**Comment by astupidmoose** [comment]
> So what is it that we want to do here? Looks like the address is available in the invoice summary.
> 
Addresses are not available in the invoice screen itself. When you go into the invoice details, I would think you would expect to see details of all available addresses or used addresses. The available invoices as shown on the summary are not available in the invoice details screen.

**Comment by pavlenex** [comment]
@astupidmoose @Uter1007 

Going back to this issue.

When the invoice is paid from multiple inputs, here's what you'll see
![Screenshot from 2021-01-18 13-47-07](https://user-images.githubusercontent.com/36959754/104918318-db0c9980-5994-11eb-9065-fe71af99a885.png)

When invoice is partially paid and expired. Here's what you see:
![Screenshot from 2021-01-18 13-54-56](https://user-images.githubusercontent.com/36959754/104918350-e8c21f00-5994-11eb-9b02-ac7987a8ef30.png)

The address shown in `Invoice Summary` is the next expired address. Is this information that you guys wanted to have, and if so, what can we do UX wise to better communicate what it is? I think this way it's slightly confusing.

**Comment by Uter1007** [comment]
thx !!! as always the btcpay team is amazing - keep up this spirit ! cheers

**Comment by astupidmoose** [comment]
Yea, I believe this issue is no longer an issue. Expired invoices didn't show this information before, but now they do.
