### ISSUE TITLE
Feature Request - Shapeshift / Changelly Integration

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#17]
Would be nice to have an optional setting in BTCPay store settings to turn on/off shapeshift integration.

This allows BTCpay clients to use the BTCPay service, while accepting altcoins from customers. 

This should be as easy as integrating a "shifty" button to the bottom of the Scan and Copy screens. [Shifty button docs](https://info.shapeshift.io/tools/shifty-button)

Server settings should also include an affiliate key to be set, which can be passed in the URL. 

- Possible issue with Shapeshift is transactions often happen past the 15 minute counter.

**Comment by NicolasDorier** [comment]
I plan later to allow merchants to accept multiple currencies on one store.

**Comment by NicolasDorier** [comment]
I will close this issue. I don't intend to allow shapeshift integration as this is a central party I prefer people does not depends on, this goes against the goal of this project.

However, I plan to support other crypto currencies in the future, probably starting by litecoin.

**Comment by astupidmoose** [comment]
Politics aside, I really think this is a missed opportunity right now for many merchants. This enables merchants to accept DASH/DOGE/MONERO and ETH until they can be implemented directly with very little effort. 

I envision this as being a simple checkbox in the store settings:

"Enable Shapeshift"
"Enable Changelly"

Shapeshift works out of the box without any sort merchant signup requirements.

Changelly requires merchants to have an API account signed up before being able to insert the code. This could have some privacy implications.

**Comment by bitcoinshirt** [comment]
I think this can be an interesting solution if we can find different platforms. Perhaps Shapeshift can be one way here, though as mentioned, I'm also not a huge fan of their service.

I'm certain that this can be done with atomic swaps in the long run, but perhaps services like ShapeShift can be a short-term solution.

**Comment by astupidmoose** [comment]
Shapeshift requires only a simple addition of this code:

<script>function shapeshift_click(a,e){e.preventDefault();var link=a.href;window.open(link,'1418115287605','width=700,height=500,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=0,left=0,top=0');return false;}</script> <a onclick="shapeshift_click(this, event);" href="https://shapeshift.io/shifty.html?destination={DESTINATION}&amp;output=BTC&amp;amount={AMOUNT}"><img src="https://shapeshift.io/images/shifty/xs_light_altcoins.png" class="ss-button"></a>

The {DESTINATION} and {AMOUNT} would need to be replaced by BTCpay

CSS would also need to be adjusted to make room for the "pay with altcoins button". Alternatively, design-wise we could add a Shapeshift icon, beside the BTC and LTC coin icons but this won't always be clear to everyone that this is for altcoins.

**Comment by lepipele** [comment]
@astupidmoose take a look:

![shapeshift_1](https://user-images.githubusercontent.com/5191402/37358390-00af7e44-26b9-11e8-98a3-5c9499b87034.jpg)
![shapeshift_btc](https://user-images.githubusercontent.com/5191402/37358391-00bfd442-26b9-11e8-9128-7d39215994ae.jpg)
![shapeshift_ltc](https://user-images.githubusercontent.com/5191402/37358392-00dafb0a-26b9-11e8-91cb-c33c31c3ccb9.jpg)

Here is commit that enables it: https://github.com/lepipele/btcpayserver/commit/9e16b83202514cb46f4d72393a06c84f6c3ee9b8

I still don't like it... it should rather go down in that "payment area" with Scan & Copy... because this is more like "payment method" rather than "currency selection". If @NicolasDorier is OK with this direction I can look into implementing this.

**Comment by astupidmoose** [comment]
I think this looks awesome but I get the point of placement. It's not exactly a coin, but I suggested it there as I knew we were having issues with cutoffs. 

I also think we should have it enabled/disabled via the settings in the BTCpay store settings screen. (Checkbox). Likely disabled be default.

**Comment by lepipele** [comment]
@astupidmoose I think definitely the best way would be to have another tab:

Scan / Copy / Altcoins

And then if you select Altcoins you get short explanation that you will be paying through another provider, there are extra fees, confirmation time, etc... plus we can even add links to more FAQs since we'll be having space.

Then that's followed with buttons for Shapeshift and Changelly. And as you say, it'll be setting that admin needs to enable.

I think if done like this it makes sense + merchants will likely love it.

**Comment by NicolasDorier** [comment]
@lepipele I am mind blown that the integration take so few line of code.

**Comment by NicolasDorier** [comment]
Ah actually I think it is not as simple... Because the invoice will be considered paid when shapeshift send the funds...

**Comment by lepipele** [comment]
You know me man - 1337 minimal code changes ;)

I agree that it's not as simple because we have that intermediary step in Shapeshift that's beyond our control. But merchant can tweak that for himself (increase default invoice expiry time) and we can provide additional explanation in new tab. Like make everyone understand that "Conversion transactions" will be more expensive and that there is intermediary between.

@astupidmoose do you know what are fees and guaranteed sending times? Maybe that's something we can also link if we do this... explaining there are "base currencies" that we have direct integration with in BtcPayServer" and then conversion supported ones.

I really think it would be good feature - turned OFF by default, but if some merchant wants to turn that integration on... we should give him ability to do so. Would definitely set us further apart from alternatives.

**Comment by astupidmoose** [comment]
When funds are sent, the window remains open during the entire processing timeline of the transaction. Most users who are using shapeshift will likely have a good idea of what they are doing. 

In regards to shops, this will be up to the shops to set their timelines in place for these transactions. The worst case scenario is a payment might be "paid late" status. 

If we go the new tab route, we can create a short breakdown of the process as well as the expectations of the customer. 

Shapeshift builds the fees and their exchange rates into the amount a customer needs to send. This makes it so the customer does not underpay invoices by guessing the amount for conversion. It's simply "your 2 ETH = .01 BTC. 

We had this feature in the past and it drove an added 10% of sales through obscure coins and ETH. Would be nice to have this option, likely disabled by default. 

I can even write up an explanation for merchants. 

Ps. When I added the code earlier, my plan was to also add the Changelly code for the same thing, however their website was broken and their API was down. :(

**Comment by NicolasDorier** [comment]
@astupidmoose so you are saying we don't really need to track shapeshift payment state from BTCPay because users using shapeshift are smart enough to understand what is going on ?

**Comment by NicolasDorier** [comment]
Is it possible to get a callback when the user made payment? At least we could mark the payment as 'paid' if it was the case.

**Comment by lepipele** [comment]
@NicolasDorier looking through @Shapeshift-Public API, they have this method: https://info.shapeshift.io/api#api-105

I'll PM you on Slack so we can figure this out.

**Comment by NicolasDorier** [comment]
mh maybe we can keep that for a later PR, it seems @astupidmoose said it was OK if it does not goes to paid immediately.

**Comment by astupidmoose** [comment]
Payment speeds should not usually be an issue. It may cause issues if the bitcoin blockchain is spammed. But then maybe merchant can switch the settlement on Shapeshift from BTC to LTC. 

Here are some points from their best practices guide, which I will attach as well: 

- payment is considered "accepted" by shapeshift after one block confirmation; some zero confirmation transactions occur but these are not common.

- processing speeds: 30 sec to a few hours, depending on block speed. Most are within minutes. Some can take up to 48 hours (this is not common).

- Shapeshift accepts one deposit per transaction; if sent in more than one deposit, customer will need to request refund from shapeshift.


[Affiliate Partners Best Practices Guide.pdf](https://github.com/btcpayserver/btcpayserver/files/1812762/Affiliate.Partners.Best.Practices.Guide.pdf)

**Comment by lepipele** [comment]
@astupidmoose OK man - I'll be doing proof of concept for this and once done let's review it.

**Comment by lepipele** [comment]
@astupidmoose take a look:

![work in progress](https://user-images.githubusercontent.com/5191402/37551750-a1b0ca4c-2974-11e8-98c8-99cfce104756.png)

Think about text that we can put there in order to explain to users process... plus we can link to more info. 

Changelly is out since they don't seem to have option to set DESTINATION AMOUNT. They only allow you to set from amount... and I don't think we want users to tinker with values and switching.

**Comment by astupidmoose** [comment]
@lepipele I think this is awesome! Wording is spot on to me. Love it!

We may want to add a note that funds sent late may be marked as paid late in the merchant's system but that might only be relevant to my own settings. Would love to hear what @bitcoinshirt thinks.

**Comment by azeemh** [comment]
is this ready for altcoin usage in production enviornment?

**Comment by bitcoinshirt** [comment]
I like the progress here.
@lepipele the note and the warning that the payments are good UX and remind users that there can be a delay.

@astupidmoose While this can be handy for some businesses, perhaps it's a bit too specific to mention. I just think users might be a bit confused as most of the customers have no idea what's happening on the backend and how the orders are fulfilled.

**Comment by astupidmoose** [comment]
@bitcoinshirt Definitely agree and was part of my worry hence asking you to check and see what you think too. I say we make it as clear and non-technical as possible.

I like what is there now and likely don't see any need for anything else.

**Comment by NicolasDorier** [comment]
on the UX I am just a bit concerned that user would use shapeshift instead of Litecoin even if the store support it directly, because he misses "Pay with..." or because he does not really understand why there is two choices.

**Comment by astupidmoose** [comment]
@NicolasDorier Perhaps we should have the Altcoins be an icon, as originally shown here: https://github.com/btcpayserver/btcpayserver/issues/17#issuecomment-372748279

But clicking the icon then brings the explanation dialogue with the "pay with altcoins" button as shown here: https://github.com/btcpayserver/btcpayserver/issues/17#issuecomment-373894400

This would then eliminate the duplication needed for adding "Altcoins" to each coin, and would have a clear flow of BTC OR LTC OR ALTCOINS

**Comment by lepipele** [comment]
...

Guys, I've tested this for last 2 days... it's way more confusing when top icons both change base invoice currency and also launch another window. I've changed tab name to **Conversion** for clarity.

Here is link to set of changes that enables all this: https://github.com/lepipele/btcpayserver/tree/dev-shapeshift - test and give it shot. Please keep in mind that you need to explicitly enable "Allow Coin Conversions" in Store Settings.

Nicolas I'll DM you for code review.

**Comment by lepipele** [comment]
![animation](https://user-images.githubusercontent.com/5191402/37562797-ff16d3fa-2a3e-11e8-8d44-02b45eb6bf9f.gif)

**Comment by NicolasDorier** [comment]
Created #62 as this is done!
