### ISSUE TITLE
Pull Payment DateTime displayed

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver#1725]
**Describe the problem/bug**
The DateTime displayed in the viewed pull payment is ahead of my local time. 

**Your environment**
* Version of BTCPay Server: BTCPayServer v1.0.5.2
* Deployment method: LunaNode
* Other relevant environment details: The DateTime is correct in the list of pull payments. 

**To Reproduce**
1. Go to Wallets
2. Click on Pull payments
3. Click view on the pull payment

**Expected behavior**
The time is was created for me is shown correctly as it is in the list of pull payments. 
In this case it should be 7/8/2020 11:06:16 PM

**Actual behavior**
When viewing the pull payment it instead shows as:
Updated 7/9/2020 5:11 AM

**Screenshots/Links**
Correct local time shown in the list of pull payments:
![PullPaymentsCorrectTime](https://user-images.githubusercontent.com/39231115/87000959-87aec880-c173-11ea-8341-3e043d2ab589.PNG)

Incorrect local time shown in the display of the pull payment:
![PullPaymentsTime](https://user-images.githubusercontent.com/39231115/87000993-9d23f280-c173-11ea-825e-95864752d6bc.PNG)

**Comment by britttttk** [comment]
Also as a very small nit, max characters for pull payment name will overflow into next row for any theme besides classic.
![image](https://user-images.githubusercontent.com/39231115/87009875-05c69b80-c183-11ea-9337-858c1d0a4e7a.png)

**Comment by bolatovumar** [comment]
@britttttk @pavlenex I tried this on my end and get the same thing. Looks like when you go to view the created pull payment it shows the current time. I fee like this might be intentional sine it says "Updated" there. Also, looking at the code, it looks intentional:

![Screen Shot 2020-07-11 at 8 33 12 PM](https://user-images.githubusercontent.com/1934678/87238312-dc418600-c3b5-11ea-916f-96dfc2bd4374.png)

**Comment by britttttk** [comment]
@bolatovumar hmm I see. I just noticed that payment requests shows the current datetime properly in the same area.

**Comment by pavlenex** [comment]
@NicolasDorier Can you explain why the `Pull Payment` here shows `current time` in `Last Updated` what is meant by last updated as it seems it should perhaps show creation date?

![Screenshot from 2021-01-18 14-09-17](https://user-images.githubusercontent.com/36959754/104919585-c8935f80-5996-11eb-8902-6d566f2b3893.png)

**Comment by AlexGidge** [comment]
@britttttk You're right, the "start date" in the list view is translated to browser date time, but this "Last Updated" is displaying server time. It would make sense to display them in the same timezone. Probably client timezone? Resolution would be to add the same date time translation logic from the list screen onto this View Pull Payment screen.

@pavlenex it's using the server's current time every page refresh. I think this is intentional as it's showing the time that the server "updated" or refreshed the status of the pull payment. But the wording isn't clear. It'd be good to update it, maybe to "Last Refreshed"

Also, is it worth adding the "Start Date" onto the View Pull Payment screen to match the list view?

**Comment by britttttk** [comment]
looks great @AlexGidge, possibly keep AM/PM as it was

**Comment by AlexGidge** [comment]
@NicolasDorier fixed an issue in my change in 94acf60
