### ISSUE TITLE
Improve generate wallet page

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1755]
**Is your feature request related to a problem? Please describe.**
In BTCPay, as described in #1703 user can use an existing wallet or create a new wallet. This issue is about creating a new wallet. In Store Settings > Derivation Scheme > Modify, you will have an option to `Generate a new wallet`. This issue specifically is about the generate wallet page. For wallet setup comments refer to #1703 

It's good idea to focus on small bits one by one, as we improve overall wallet setup experience. Anyway, when you click generate a wallet, you're greeted with this pop-up page. 

![Capture](https://user-images.githubusercontent.com/36959754/87925959-51315180-ca81-11ea-83f8-d1ffd834f43b.PNG)

The page itself has plenty of things going on. In my opinion here are the problems:

- Existing seed - in this field user can add an existing mnemonic. It's confusing since it's above the fold and user mostly wants to generate a new wallet.
- Passphrase field - there should be a warring, it's important as user starts typing passphrase we notify them that forgetting a passphrase may results in their funds being locked out
- Is hot wallet - weird naming, should be toggled instead checked?
- RPC - quite unclear very unlikely anybody will use it

After wallet generation, user is redirected to backup the mnemonic as described in #1745 

The workflow is simple most people just need to click generate button, everything else is in a way advanced on this page.

**Describe the solution you'd like**
Simplify the wallet generation page. Make important stuff above the fold. Warn user about the danger of using a passphrase and forgetting it. Perhaps hide advanced functions from the view, better communicate advanced features. Distinguish importing from generating a new wallet better.

Wallet generation process is described here https://docs.btcpayserver.org/CreateWallet/
Hot wallet is described here https://docs.btcpayserver.org/HotWallet/

**Provide examples**

**Additional context**
This issue is not a priority before we finish the 0.08 milestone and #1745. It should convey the ideas from #1703 which is a major overhaul.

**Comment by dstrukt** [comment]
Will take a look when we knock through the design tickets in this release.

**Comment by dennisreimann** [comment]
I approached this in parts while working in the recovery seed page. IMHO we should differentiate the cases generating a new wallet and importing an existing one. Though these share parts of the interface, I find it confusing to begin with, that the option to generate is hidden behind the "Import from …" link.

![import](https://user-images.githubusercontent.com/886/88259464-a314ea00-ccc2-11ea-8967-eb9d6f23e844.png)

I'd also consider moving away from using a modal – at least for the create/import cases. It not only looks crammed, but it doesn't feel natural to the user flows we are using in other cases. (comparing it to e.g. managing the lightning node)

Got some ideas on how we can clean it up and there's also a branch with the commit we separated out from the recovery seed PR, but I'm looking forward to what @dstrukt comes up with. This section definitely needs some love and I'm sure we can improve it quite a bit.

**Comment by dennisreimann** [comment]
Just saw that there is also #1703 – it overlaps with this one a bit.

**Comment by pavlenex** [comment]
It overlaps a bit indeed. I think #1703 should serve as a base on what we're doing here, even though #1703 will most likely be added in the next few releases (because we still haven't agreed on what we want there, plus some heavy refactoring will most likely be needed).

**Comment by britttttk** [comment]
@pavlenex @dennisreimann I agree with all of the bullet points above. 

 Since the related issue of 1703 is more design. I'll keep content and copy ideas here. 

It would be nice to still have the capability to produce a wallet from existing seed. Although I think this, along with RPC toggle might be better suited for a hidden Advanced Settings area (similar to how it is on the Send from wallet page). I agree that RPC is not clear and not likely to be used regardless..

The seed word page in the related issue page looks great. Only copy I would add is:
"**You will not be able to access these seed words at a later time** ..... they will be removed from the server on page reload.. etc"
I think it's common for users to think they can do it later.. afaik that's not possible, I think this bold part should be included. 

Similar with passphrase, it needs a better warning as you mentioned Pav. I would also say this is an "advanced setting". 

I think the most confusing part about this page is that it doesn't really help the user understand which options are mutually exclusive. I think the related issue 1703 does a good job of solving this. I agree with Pav that if 99% of users just need a hot wallet and that is 1 checkbox below the fold among several options, then the page is probably going to leave users with more questions than it should.

**Comment by pavlenex** [comment]
Done in #2164 :rocket:
