### ISSUE TITLE
Selecting Invoice filtering for the "last 24 hours" should not set a startDate filtering

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#1775]
Ping @rockstardev @dennisreimann 

With the new feature of saving preferences in cookie for searches, we should change the way we handle filters such as "Show invoice in the last 24H".

Currently, imagine the user is end of the 24 july.

* User set filter "show invoice in the last 24H", it will show the invoice that happened the 24 july.
* Tomorrow, same time, he comes back, go in the invoice list, and expect to see the invoices of the 25 july.
* However, the actualy behavior will be to show him the 24 july and 25 july. Because the filter string is only understanding "startDate: beggining of 24".

**Comment by rockstardev** [comment]
Lol

**Comment by rockstardev** [comment]
I gave birth to this monster feature, I'll take it down.

**Comment by rockstardev** [comment]
What needs to be done here is that we to create filter for `startDate:-24h` that will take `-24h` string and evaluate it at the moment of processing on the server (taking into account user's time zone value that's also coming in).

This can be done as part of `SearchString.GetFilterDate` method:
https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/SearchString.cs#L57

If someone wants to take stab at it, go for it... otherwise I'll do it as part of #1754 tonight (while also implementing blob for Nicolas).

**Comment by dennisreimann** [comment]
@rockstardev Sounds perfect, go for it!

**Comment by rockstardev** [comment]
Ready for review @NicolasDorier
