### ISSUE TITLE
[Discuss] Open Registration Page After Deployment

### ISSUE THREAD

**Issue by benichmt1** [btcpayserver/btcpayserver#1781]
**Background**

I've launched instances of BTCPay Server with both Azure and LunaNode. One of the things I immediately noticed to bring up for discussion is the fact that these deployments require an admin to finish the installation process by registering in the web interface. 

![Screen Shot 2020-07-28 at 3 48 53 PM 1](https://user-images.githubusercontent.com/1136610/88715991-5da25380-d0ec-11ea-83ce-c90fdac02182.png)

The problem I see is that anyone searching the web for these pages can theoretically take over the entire deployment. It would be trivial for an attacker to scan for newly-registered instances, upload an SSH key, and compromise the host. In my opinion the likelihood of this happening is high - the deployment process takes a fair amount of time to complete. A cursory scan of Shodan showed many sites able to be hijacked in this fashion.

**Suggestion**

In the deployment template, consider emailing temporary initial credentials rather than relying on user action. Another option might be using the console to print these messages to the administrator who is installing BTCPay Server.

I see that registration is disabled by default (see https://github.com/btcpayserver/btcpayserver/pull/463), but this happens AFTER an administrator registers for the initial account.

**Comment by pavlenex** [comment]
> In the deployment template, consider emailing temporary initial credentials rather than relying on user action. 

No this is not possible, user needs to create SMTP credentials in order to do this, so registration is needed. 

Even if the instance is hijacked people can easily reset user, there's no real benefit of hijacking someone's instance, there are no keys or funds at stake here, this has already been discussed a few times.

**Comment by NicolasDorier** [comment]
@pavlenex this kind of issue already happened. Some people got their instance hijacked by bots before they could register.

Luckily the result is that they can't access their instance, at which point their nuke their instance and start over.

**Comment by NicolasDorier** [comment]
Some of those vectors are closed depending on how the user installed it.

If installed on raspberry pi via the docker-compose, the user is most likely behind a NAT protecting his SSH port.
On top of that, by default ` BTCPAY_ENABLE_SSH` is false (https://github.com/btcpayserver/btcpayserver-docker).

What you point out is a problem for install via lunanode for example, that use `BTCPAY_ENABLE_SSH=true` in their scripts.
But when the instance get hijacked, the user always deploy a new node as he can't connect to his instance.

So the question is: Should we close by default the SSH port on Lunanode installs.
We keep SSH open as most our users are merchant, never used a command line in their life, and if something go wrong we should not have a 10 steps process for them to fix the server.
That said, with a proper documentation it may work. (somebody need to take the time to actually document this, step by step, with screenshots) and modify https://github.com/LunaNode/launchbtcpay/

Another idea is to put a warning when the user create the first admin, urging him to put his own SSH key and close the ability to set a new key via btcpayserver.
The problem is that such warning and instruction will just confuse our users. (once again, we have to keep in mind that those are people who never ran a command line, they don't know what a key is and what SSH means)

A third idea, is to add a configuration option in btcpayserver such that by default, changing SSH key is disabled, and use this in LunaNode.
I think this is a good compromise. The user can get the SSH password on the lunanode dashboard quite easily if he needs to connect.
