### ISSUE TITLE
I'm unable to verify the commits

### ISSUE THREAD

**Issue by Kixunil** [btcpayserver/btcpayserver#1802]
**Describe the problem/bug**
The key used for signing commits is not publicly available.

**To Reproduce**
1. Search for GPG key on GitHub
2. Run `git verify-commit ...`
3. Pass the key id from error message to `gpg --recv-key`
4. Key without id found, not imported

**Expected behavior**
Key can be found on github, or even better on keybase (with proofs linked to GitHub,  twitter and the official website)

**Actual behavior**
The key is not published anywhere

**Comment by Eskyee** [comment]
not sure why, but I'm also having this problem. since today, 

Commit failed - exit code 128 received, with output: 'error: gpg failed to sign the data
fatal: failed to write commit object'

**Comment by Eskyee** [comment]
ok I have now fixed this problem, with a fresh Mac user account. which now sign commits. ok.

this problem started for me when with my first time doing some Bitcoin Core release signatures on my Mac, which all passed, but the GPG key git stuff etc etc had messed up my old signing commits git commits.. 

the fix was.. as above!
created a fresh Mac account, and tested to sign commits, which worked ok, no problems now.

**Comment by Kixunil** [comment]
I have now succeeded at verifying the latest release of BTCPayserver with fingerprint `AB4CFA9895ACA0DBE27F6B346618763EF09186FE` which is on keybase and belongs to Nicolas. I consider the issue resolved.
