### ISSUE TITLE
Payouts - Support Lightning Payouts

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#1827]
**Is your feature request related to a problem? Please describe.**
Currently, Payouts only work via on-chain transactions. We should allow Pull Payments to specify which methods are allowed for a user to request a payout with.

**Describe the solution you'd like**
A similar UI as the Invoice create page, with a dropdown of available payment methods. On the public page, the user is shown available options. In the option to claim, the user can now enter a bolt11 invoice.

**Describe alternatives you've considered**
sadness

**Provide examples**
solution description is sufficient.

**Comment by brainharrington** [comment]
What does payouts mean in this context? This sounds cool and I think it sounds helpful because I've been having to manually pay out merchants that I'm running the lightning node for because I have no way to direct the funds to their wallet the way that we can on chain by using an x pub.

**Comment by pavlenex** [comment]
@brainharrington No, this won't help with your issue of distributing funds to a merchant. This means that pull payment's `payouts` should have the ability to have a off-chain option. One implementation of a pull payment is a [refund](https://docs.btcpayserver.org/Refund/). The implementation of this issue would simply mean that you can refund your customer a payment via the LN, currently it's only possible via LN.

**Comment by Zaxounette** [comment]
Chipping in on this.

Currently, when trying to issue a refund for a LN paid invoice, it returns an error 500. 
I feel like this is expected since this current issue is here.

While waiting for it to be resolved, would it be reasonable to either:
*  disable the `refund` button,
* or better, replace it with an non-actionnable button with wording in the lines of `Refunds are currently not supported for off-chain payments`.
This second option would be less confusing for users expecting the refund option to be available for all invoices IMO.
