### ISSUE TITLE
Weird redirect after login / Improper handling of rootPath (final / not allowed)

### ISSUE THREAD

**Issue by ketominer** [btcpayserver/btcpayserver#1915]
**Describe the bug**
When using a custom path for btcpay, such as btcpay.mydomain.com/btcpay/, after login, btcpay redirects to btcpay.mydomain.com/btcpay when rootPath doesn't contain a final /. Final / can't be added because it's not allowed (see below).

**To Reproduce the redirect**
1. set rootPath to /customValue
2. configure reverse proxy to proxy /customValue/ to btcpay:23000/customValue/
3. login to btcpayserver through reverse proxy
4. you get redirected to the /customValue without final / which ends up in a 404 if reverse proxy is not configured to also redirect customValue to customValue/

**To Reproduce the error**
1. set rootPath to anything ending with /
2. start btcpayserver.dll
3. see error in logs
Application startup exception: System.ArgumentException: The path must not end with a '/' (Parameter 'pathMatch')

**Expected behavior**
I don't see any good reason why the final / wouldn't be allowed as it allows for cleaner reverse proxy configuration in complex deployments.

**Proposed solution 1**
Allow final / in rootPath

**Proposed solution 2**
Add / when redirecting after login

**Comment by dennisreimann** [comment]
I'm currently also investigating a bit here, because I noticed a similar problem with the Transmuter service/extension: the services page links to `https://btcpay.host/btctransmuter` (no trailing slash), which results in a redirect to `http://btcpay.host/btctransmuter/` (http + trailing slash). This is weird and should be avoided, especially because one ends up in a non-https context, which works with Transmuter without a warning. 

`https://btcpay.host/btctransmuter/` (https + trailing slash) works, but one would have to manually switch the protocal afteer clicking the link on the services page. I haven't checked yet, but I'm not sure if adding a trailing slash to [`TRANSMUTER_ROOTPATH`](https://github.com/btcpayserver/btcpayserver-docker/blob/master/docker-compose-generator/docker-fragments/opt-add-btctransmuter.yml#L13) would suffice, because if I read this issue correctly, this could also result in the described error.

**Comment by NicolasDorier** [comment]
checking

**Comment by NicolasDorier** [comment]
So I checked, this is a limitation come from ASP.NET itself.

https://github.com/aspnet/HttpAbstractions/issues/683#issuecomment-240610389

**Comment by NicolasDorier** [comment]
Marking for closing, as sadly, this problem is out of our control.

**Comment by Kukks** [comment]
> Marking for closing, as sadly, this problem is out of our control.

We should probably not be using `Map` and use `https://github.com/btcpayserver/btcTransmuter/blob/master/BtcTransmuter/Startup.cs#L186` instead

**Comment by NicolasDorier** [comment]
@Kukks can you give a try with transmutter if that would work with trailing / ?

**Comment by Kukks** [comment]
@ketominer Would you be willing to do some of the testing for this if I did a PR?

**Comment by rockstardev** [comment]
@ketominer ping

**Comment by ketominer** [comment]
let me know which branch to test it on - I should have more time in the next two weeks

**Comment by pavlenex** [comment]
@ketominer Is this still an issue?

**Comment by pavlenex** [comment]
@ketominer @Kukks @rockstardev What are we going to do with this one? It's an old issue.
