### ISSUE TITLE
Bitcoin PoS icon doesn't work on iPhone browsers

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver#1920]
**Describe the bug**
PoS denomination icon for Bitcoin doesn't work on iPhone browsers when using these themes: Default, Dark, Classic

**To Reproduce**
1. Create PoS app
2. Make denomination BTC
3. View PoS on iPhone browser
4. See squares instead of B symbol

![iphone7](https://user-images.githubusercontent.com/39231115/93847650-b9a8d480-fc64-11ea-9be1-8162a29e1017.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version: v1.0.5.5
- Deployment Method: LunaNode
- Browser: tried on chrome, safari, firefox, ddg
- iPhone: tried on 7 & 11 

**Additional context**
- Icon works fine using the Casa Theme
- Works on PC
- It works if you use a bootstrap theme in addition to any of the themes.

**Comment by pavlenex** [comment]
@britttttk can't replicate this on iphone 8 on Safari (iOS14). Do you have a link where this can be tried out? I tried on btc.donate.kukks.org

**Comment by mariodian** [comment]
Can't replicate either on the latest commit (iPhone 8, iOS 14). 

Since the Bitcoin sign used on BTCPay is not an icon but a standard unicode symbol, I think it's a local problem. What iOS version are you using?

Are you loading some other CSS files with the PoS? It may be, that a custom CSS is overriding the font and not all fonts support all unicode characters. Or perhaps are you running a 3rd party app that changes the custom iOS fonts to something else?

**Comment by britttttk** [comment]
https://btcpay557691.lndyn.com/apps/2oWV57ZTEkFjLqoGvFFSyv5vKmXD/pos @pavlenex @mariodian only tried on iOS 13.6

**Comment by mariodian** [comment]
I see it correctly on my iPhone.

**Comment by britttttk** [comment]
Thanks @mariodian I updated and it works now. Since there are solutions for both versions new (14+ works) and old (use a bootstrap theme). I think it's fine to close this. Unless anyone thinks there is something we can do to improve it that is worth keeping this open.
