### ISSUE TITLE
Payment Button Improvements for Custom Amount/Simple Input Style

### ISSUE THREAD

**Issue by brainharrington** [btcpayserver/btcpayserver#1999]
**Is your feature request related to a problem? Please describe.**
The button I like most for squarespace sites and wix sites and non e commerce optimized sites where you just want to place an invoice button is the Custom Amount, Simple Input Style. Two things I've noticed that make using this button less than optimal are the 0 is not centered and when clicking into the box I've often seen users have trouble erasing the 0 in order to type over it the value that they want to pay.

**Describe the solution you'd like**
- Maybe the "0" would be better as a "-"
- Centering the "0"
- Is it possible to have only a single click be necessary to highlight the zero and type over it instead of a double click?

**Describe alternatives you've considered**
It's not mission critical, just wanted to have a discussion.

**Additional context**

Here's how it looks on the site I'm using

<img width="220" alt="Screen Shot 2020-10-19 at 11 24 11 AM" src="https://user-images.githubusercontent.com/37989507/96496318-f208e780-11fd-11eb-94a1-ed793788a6c0.png">

**Comment by bolatovumar** [comment]
Looks like the reason it's not centered is because this is a number input. I wonder if it should be updated to be text input instead which is limited to just numbers.

![Screen Shot 2020-10-31 at 9 03 21 PM](https://user-images.githubusercontent.com/1934678/97794859-825f0900-1bbc-11eb-9c2d-b405278814bb.png)

**Comment by bolatovumar** [comment]
Looks like the `type="number"` input field we use does not support selecting the input contents on click/tap so it can be easily overwritten. We can get around this by using a `type="text"` field instead and that will support all of the desired bullet points described above. We will have to enforce the min and max values manually with input `type="text"`, however. Also,  the "step" option we expose does not make sense with a input `type="text"`.

![Screen Shot 2020-11-01 at 4 37 54 PM](https://user-images.githubusercontent.com/1934678/97819944-9c522780-1c60-11eb-9ecf-a28ddffb0e3d.png)

**Comment by dennisreimann** [comment]
imho we should try to keep it as a `type="number"` input, because that's what we want technically and we can circumvent dirty fixes that way. Please try the [`hide-number-spin` class](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/wwwroot/main/site.css#L258), which I recently introduced – it solves at least the styling issue.

**Comment by bolatovumar** [comment]
@dennisreimann Yeah, we can solve the centering issue with CSS but not the other two issues mentioned above.

**Comment by bolatovumar** [comment]
Alright, added the inline stylesheet to center the input contents.
