### ISSUE TITLE
Unique wallet tx label colors

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver#2072]
**Is your feature request related to a problem? Please describe.**
The default labels (app, payment-request, etc.) use certain colors for labels. When I make custom labels, it uses those colors again before creating new unique label colors. 

**Describe the solution you'd like**
When creating a new custom label for a tx, I would like it to use a color that is not in use for another label.

**Sketch/Image/Wireframe/Mockup**
![image](https://user-images.githubusercontent.com/39231115/99869804-25d38600-2b8b-11eb-86e0-e74ede56e11a.png)

**Additional context**
In the image above, I only get a new color on the third custom label. I wish it was on the first.

**Comment by pavlenex** [comment]
Noticed this as well, but forgot to report it, agreed with the idea of having different colors as it's easier to differentiate.

**Comment by bolatovumar** [comment]
Hmm... I can't repro this one. It looks like a bug since the current logic ensures that the color that hasn't been used previously gets used first. You could only end-up with the same color being used twice if you have already used up all of the pre-defined available colors. See the list of colors available:

![Screen Shot 2020-11-21 at 6 45 41 PM](https://user-images.githubusercontent.com/1934678/99892449-d09a8180-2c29-11eb-9dfb-c32b5e411b1f.png)

The current logic for assigning a color to a new label is as such:

![Screen Shot 2020-11-21 at 6 44 13 PM](https://user-images.githubusercontent.com/1934678/99892453-dee89d80-2c29-11eb-852e-69338308a793.png)

Essentially, we get all colors and the pick the color that is used the least often and assign it to the label. This way you shouldn't end-up with the same color being used twice unless you have already used up all of the colors.

**Comment by bolatovumar** [comment]
Also, looks like there is an issue with the label that ends up assigned `#000000` as its color because the "x" icon becomes invisible:

![Screen Shot 2020-11-21 at 5 08 30 PM](https://user-images.githubusercontent.com/1934678/99892499-50285080-2c2a-11eb-8b24-6f04831ab14e.png)

**Comment by britttttk** [comment]
The `.ThenBy(k => Array.IndexOf(LabelColorScheme, k.Key))` puts the default labels at the top of the list. It works fine without it.

**Comment by bolatovumar** [comment]
@britttttk OK, thanks for clarifying, I can repro the issue now. The latest commit to my PR should now fix the issue.

**Comment by mariodian** [comment]
Feature idea: I think you should be able to choose custom colors. This makes sense when you use a custom theme that may interfere with default colors. For example that light green is almost invisible on light themes.

**Comment by bolatovumar** [comment]
> Feature idea: I think you should be able to choose custom colors. This makes sense when you use a custom theme that may interfere with default colors. For example that light green is almost invisible on light themes.

Yeah, that would make sense. Not sure how it would work from the UX flow perspective though.
