### ISSUE TITLE
CashApp doesn't recognize invoice as "Bitcoin Wallet" when scanning QR code

### ISSUE THREAD

**Issue by pretyflaco** [btcpayserver/btcpayserver#2099]
**Describe the bug**
Customer reported that "when scanning the BTCPay QR code, I get an error that it's not a Bitcoin wallet"

The BTCPay instance version is v1.0.6.0.

**To Reproduce**
Don't have CashApp to reproduce. 

**Expected behavior**
Recognize either on-chain or off-chain invoice

**Comment by pavlenex** [comment]
Hi, we need a bit more context to the issue.

What's the address format that you're using for your wallet? SegWit/Legacy/P2SH? Do you by any chance have the `
Include lightning invoice fallback to on-chain BIP21 payment url` enabled in Store > Checkout experience?

**Comment by britttttk** [comment]
I can reproduce this @pretyflaco regardless of wallet type it will not work, it gives the error you mentioned. I tried with and without payment amounts specified in cash app. 

I can however send to the BTCPay Wallet's Receive page from cash app.

**Comment by pavlenex** [comment]
Isn't this a cashapp issue then?

**Comment by britttttk** [comment]
I can reproduce it does not work with or without: lightning/payjoin/bip21.

**Comment by pretyflaco** [comment]
Address format is **P2SH** 
Include lightning invoice fallback to on-chain BIP21 payment url is **not** enabled

**Comment by britttttk** [comment]
It works in version 1.0.5.9 but stopped in 1.0.6.0

**Comment by pavlenex** [comment]
Ok so the issue is most likely that we've added uppercase for the QR in 1.0.6.0
`BITCOIN:BC1XYZ?amount=0.00000001` vs `bitcoin:bc1xyz?amount=0.00001`  So uppercase BITCOIN which should be according to BIP21 protocol isn't recognized by the CashApp. Would be good to test this with a few other wallets.

**Comment by rockstardev** [comment]
> So uppercase BITCOIN: which should be according to BIP21 protocol isn't recognized by the CashApp.

I think it's likely that `BITCOIN:` is supported, but uppercased Bech32 address in QR code is not supported. @britttttk since you have CashApp can you go to:

https://www.the-qrcode-generator.com

And then try following combinations:

BITCOIN:BC1Q6APR55WRXTDTK3CJ6M69MXAYW99VVGTVDNVUNT?amount=0.00005142
BITCOIN:bc1q6apr55wrxtdtk3cj6m69mxayw99vvgtvdnvunt?amount=0.00005142
bitcoin:BC1Q6APR55WRXTDTK3CJ6M69MXAYW99VVGTVDNVUNT?amount=0.00005142
bitcoin:bc1q6apr55wrxtdtk3cj6m69mxayw99vvgtvdnvunt?amount=0.00005142

Obviously don't send any funds... just see if QR codes generated scan.

**Comment by britttttk** [comment]
@rockstardev 
1. No
2. No
3. Yes - bitcoin:BC1Q6APR55WRXTDTK3CJ6M69MXAYW99VVGTVDNVUNT?amount=0.00005142
4. Yes - bitcoin:bc1q6apr55wrxtdtk3cj6m69mxayw99vvgtvdnvunt?amount=0.00005142
