### ISSUE TITLE
TLS thumbprint is not updated when LND changes it

### ISSUE THREAD

**Issue by Kixunil** [btcpayserver/btcpayserver#2182]
**Describe the bug**
LND occasionally changes TLS certificate which causes BTCPayServer connection to break since TLS fingerprint changes as well. The user gets confusing error message and has to manually reset the link to fix it. (This is not apparent from the message.)

**Suggested solution**
Provide `certpath`  config option similar to `macaroonpath` that will accept the path to TLS certificate, re-read it when connection to LND fails and attempt to connect again (if changed).
If this is difficult or lot of work, suggest resetting the link in the error message as a temporary solution.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Setup BTCPayServer with *internal* LND ("Use internal node" link")
2. Cause LND to change certificate e.g. by changing domain name or some IP address.
3. Attempt to create LN invoice from BTCPayServer

**Expected behavior**

LN invoice is created without any error messages.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    1.0.6.0, looking at the changelog it should behave the same using the latest version
- Deployment Method:       Debian package, should be irrelevant unless Docker deployment does some magic trick to fix it
- Browser:                 irrelevant

**Logs (if applicable)**

I only got small part from an affected user, this message should be relevant:

> Impossible to create lightning invoice (The SSL connection could not be established, see inner exception)

I can ask for more, however given the fact that TLS cert thumbprint is not (and can not be) dynamically updated in configuration and resetting the link helped I don't expect it's needed.

**Setup Parameters**

Config contains `btc.lightning=` option with `certthumbprint=XYZ`

**Comment by NicolasDorier** [comment]
Yeah, that's why we don't use https by default for accessing LND. You should either use a real certificate like let's encrypt. (We have a fork of LND in our docker install which remove TLS)

If @rockstardev want to try to takle, the code is https://github.com/btcpayserver/BTCPayServer.Lightning/blob/master/src/BTCPayServer.Lightning.LND/LndSwaggerClient.partial.cs#L86

That said @rockstardev just to let you understand why I don't do this already:
* We can only check certificate pinning by not using the defaultHttpClient
* I want to use defaultHttpClient as much as possible, because this is a HttpClient which is created from the IHttpClientFactory which take care of many problems such as http connection reuse, prevent socket exhaustion and properly refresh DNS if the IP change. Using a custom fingerprint might cause problem in the future such as socket exhaustion and problems if the calling code of the client expected using the HttpClient of the factory. Even though the odds are low, that's why I use HTTP by default on btcpayserver-docker.

That said, using a certpath rather than a certthumbprint would not make more problem thant what certthumbprint could potentially cause.

**Comment by Kixunil** [comment]
Thanks! Not using TLS has a few problems:

* Not secure against other system user being compromised - same sniffing attack as described in [my article about cookie files](https://github.com/Kixunil/security_writings/blob/master/cookie_files.md) This could be solved by using Unix socket (LND supports it), but does BTCPayServer support Unix socket?
* LN-Zap needs TLS to connect securely. Some kind of forwarding would be required. This is solvable but adds a dependency on some kind of bridging software.
* The fork is not an official LND build so there's fewer people who independently reproduced the build. (Although I admit not checking it deeply right now. Want to improve in the future.)

You are correct that using cert path should not introduce more problems. It'd be best if someone experienced in C# can fix this but in the worst case I could look into it myself eventually.
