### ISSUE TITLE
Address reuse on same invoice

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#22]
Currently BTCpay generates a new address for each payment. This can cause confusion for the customer and shop owner if the invoice is paid with multiple payments. It also potentially generates an unnecessary amount of addresses. 

I think reusing the same BTC address for all payments to a single invoice should not be an issue and much cleaner. 

Thoughts?

**Comment by NicolasDorier** [comment]
While we can do that, I am unsure it is really useful. As when multiple crypto will be supported, it will be possible to pay partly in say LTC and partly in BTC in which case you would have 2 addresses anyway.

I think you got confused because the woocommerce plugin was showing you only one of the two addresses. If this is the case, then the best way is for my to update the invoice details you receive on woocommerce to include ALL the addresses and payment already done.

I am however unsure about this approach either, maybe a better way is for you to just have a link to the invoice details on the btcpay website? The details page should summarize everything. The only thing I would need to do is to remove authentication of this page so you can just click on the invoice url in woocommerce and it open the page in BTCPay.

**Comment by bitcoinshirt** [comment]
Now that this is our oldest opened issue, let's see what to do with it.
@astupidmoose looking at you.
Was there really a confusion from your customers?
I assume with invoice export this is easily visible on your end.

**Comment by Kukks** [comment]
Considering all the questions and "issues " people ask about the gap limit because of the amount of unused addresses we generate, we should consider reusing addresses for same invoice. 

After that, we take it to the next level and generate addresses on demand base don invoice creation or by letting the user toggle the crypto they want to pay in.

**Comment by astupidmoose** [comment]
It's not really any longer an issue on our side and haven't heard anymore issues from this.

Using the same address for the same invoice though might reduce load on gap limits and maybe system resources?

At this point, I don't think its mission critical but maybe still a good idea

**Comment by astupidmoose** [comment]
I like #2, default to bitcoin but have a drop-down of other choices. Eliminates the need for the extra step. 

As for paying in multiple coins, this actually is a thing and many people do it on our service. I don't understand it, but it exists lol.

**Comment by bitcoinshirt** [comment]
Well isn't that quite close to an already existing solution?
![screen shot 2018-12-10 at 22 46 04](https://user-images.githubusercontent.com/36959754/49763612-7cf92c80-fccd-11e8-86db-a041c58c1cc3.png)
BTC Default, but the addres is generated only when a new coin is selected? And we just need to make selection a little bit better somehow in terms of UI.

**Comment by rockstardev** [comment]
I'm gonna keep this issue open since it's our oldest one talking about this... 

But as I said in #46 - if we want to preserve ability of users to change coins during checkout process [which is something I think merchants love - you just redirect to BtcPayServer, and user is able to switch between coins as he goes] -> then the only solution to preserve this and deal with gaps is to refactor huge part of solution.

Alternative is what @pavlenex says - you fix coin at step 1 and only then create invoice - this would still require some refactoring, but I expect it would be way easier to pull off than generating of address and starting listening process on the fly.

**Comment by NicolasDorier** [comment]
@rockstardev we can't do this. Clients of the API expects that after a call to create invoices at API side, the invoice is fixed.

**Comment by Sjors** [comment]
For shops with Lightning as a default #924 could be of some help.

**Comment by pavlenex** [comment]
As a privacy-orientated software, I don't think we will ever add or encourage address re-use, what we can try to do is optimize btcpay to generate less addresses, as @Sjors mentioned in #924 for example.

I'm not sure if we should re-phrase this old issue or what. @astupidmoose thoughts?

**Comment by astupidmoose** [comment]
This issue isn't really a problem for me anymore. I still think address reuse on the same invoice is acceptable, but not a big deal. 

We have electrum which allows for gap limit increases. Would be nice if other wallets sharpened this up a bit.

**Comment by pavlenex** [comment]
In that case, we probably have to figure out how to optimize and don't generate a new address when it's not needed as suggested in #924. I'll close this issue then and leave the other opened for future suggestions and improvements.
