### ISSUE TITLE
Improve the UI in Server Settings > Files when storage provider is not configured

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#2272]
**Describe the bug**

BTCPay Server has a file storage system in Server Settings > Files where users can upload their files. For it to work, user first needs to choose storage provider (local storage or cloud). 

Currently the way we communicate that may not be as clear on the first glance, so it would be a good idea to update the UI slightly. Perhaps we can add yellow warning box and position it better, with a better text than what we currently have.

What user should do here is click on the `external storage provider` link and then on that page configure the provider so that the files can be uploaded.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to Server Settings > Files
2. See the UI hiccup

**Expected behavior**

User should be able to figure out instantly that they are required to set up a local storage provider.

**Screenshots**
![Image Pasted at 2021-2-11 12-18](https://user-images.githubusercontent.com/36959754/107630869-71666f00-6c64-11eb-82cb-3186b20b44db.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:  v1.0.6.8  
- Deployment Method:    Docker

**Comment by pavlenex** [comment]
Another topic is if `external storage provider` is proper term, since user can configure it both internally and externally ping @Kukks 

and ping our man @dstrukt for ideas on copy, position and the overall thoughts on how to proceed.

**Comment by Eskyee** [comment]
I like the idea of a external provider as that cloud be cloud or IPFS in the future!! And it keep files away from the BTCPAY Deployment and hard drive space the the internal bitcoin node .. etc etc

**Comment by bolatovumar** [comment]
I think the experience should be more guided to make it clear there are multiple options and what's expected of the user on this screen (if anything is expected).

**Comment by pavlenex** [comment]
@bolatovumar Agreed. Do you have any concrete flow in mind?

**Comment by bolatovumar** [comment]
> @bolatovumar Agreed. Do you have any concrete flow in mind?

Not really as I don't understand the feature and all the things related to it well enough.

I assume you start out with your server as your storage provider and can configure some other external storage through this feature? (I don't really use this feature so have no idea) Or do you start out with nothing set up be default and can configure the storage provider only after going through the setup process by following the link? 

If it's the former then perhaps we can update the text slightly to indicate that you are currently set up with your server as your storage provider and that you can configure an external storage provider through this link. If it's the latter then we should probably do something like what you describe in the bug description to make it really obvious that you need to do the initial setup first before you can use this feature.

Also, I notice that clicking on this link is not the nicest experience because it just takes you to the top of the "Services" page and you have to know to scroll to the very bottom to get to the right section and click on the link there to get to the right setup screen. Ideally clicking on the first link would take you to the storage provider setup screen directly. If that can't be done for some reason then at least it should take you to the right section on the "Services" page so you don't have to scroll to find it.

**Comment by pavlenex** [comment]
> Or do you start out with nothing set up be default and can configure the storage provider only after going through the setup process by following the link?

This, you need to configure a storage provider first, regardless if it's internal or external.

> Also, I notice that clicking on this link is not the nicest experience because it just takes you to the top of the "Services" page and you have to know to scroll to the very bottom to get to the right section and click on the link there to get to the right setup screen.

Agreed, good idea.

**Comment by bolatovumar** [comment]
> > Or do you start out with nothing set up be default and can configure the storage provider only after going through the setup process by following the link?
> 
> This, you need to configure a storage provider first, regardless if it's internal or external.

Ok, that clarifies things. Sounds like making the UI a bit more obvious in telling the user that they must do something first before this feature is activated would be useful. I never made the connection myself.

**Comment by dstrukt** [comment]
Taking notes on everything, great feedback on this screen - will follow up with something after I deliver on the other few tasks!

**Comment by bolatovumar** [comment]
Also, not directly related to this issue but I wonder what the difference is between the URL and Direct URL is and if it would be useful to add some sort of tooltip or something else to explain the difference between the two.

![109374050-87c91900-7867-11eb-9b69-3e1d78a66c6d](https://user-images.githubusercontent.com/1934678/109401781-7fbfb680-7905-11eb-9206-e2e5de06a2e1.png)

**Comment by dstrukt** [comment]
Would also appreciate some clarification on this.. what exactly is the difference?

**Comment by pavlenex** [comment]
ping @Kukks ^

**Comment by Kukks** [comment]
Yes, there is a difference:
Url: Always provides the file through BTCPay so that the link is http://btcpay.com/storage/{fileId}
Direct: Provides a direct link to where the file is hosted (in this case storage is local so the url is not very different, but when you use Azure or another, it would show adasd.azure.com/download/blablabla

Url is always the recommended way, but if you uploaded a file through btcpay but did not want to depend on it for access to the file, use the direct url.

**Comment by bolatovumar** [comment]
@Kukks thanks for clarifying.

**Comment by dstrukt** [comment]
Added to my list, have a few suggestions to improve this .. will try to follow up this weekend.

**Comment by rockstardev** [comment]
@dstrukt no need for too much structure. Don't want to take your time since I've already agreed with @pavlenex on how to cleanup and opened PR, will finish it today.
