### ISSUE TITLE
Can't Import Ledger Nano S Derivation Schema

### ISSUE THREAD

**Issue by dela15** [btcpayserver/btcpayserver#2289]
Hi,

I'm trying to connect my Ledger Nano S to the BTCPay Store Derivation Scheme. But when I click on import Ledger wallet, nothing happen. I'm using Google Chrome and I also tried with Firefox, same result. My Ledger Nano was set on the bitcoin app.

Here is a link of a video so you guys can see what I'm talking about

https://www.awesomescreenshot.com/video/2765255?key=5d0656421df2c1463d5f6253d3bb6637

Thank you

**Comment by pavlenex** [comment]
Please do not ignore the issue template when opening a bug report.

Before submitting a bug report please check:
1. Your Hardware wallet is running on latest versions
2. Close any external applications that may be using your wallet (Ledger Live, etc)
3. If you have ,remove any U2F devices such as Yubikey from your PC
4. Try different browser, Brave is known to cause problems with vault.

Please fill in as much of the template below as you're able. 

**Describe the bug**

A clear and concise description of what the bug is:

**Your  BTCPay Environment (please complete the following information):**

- BTCPay Server Version:    
- BTCPay Server Vault app version:    
- Deployment Method:        

**Your local environment (please complete the following information):**

- Your operating system 
- Browser:                  

**Your hardware wallet details  (please complete the following information):**

- Hardware wallet name:
- Hardware wallet version:
- Hardware wallet firmware, bootloader, microcontroller verisons (where applicable):

**Additional context**

**Comment by Kukks** [comment]
You are on a very old version of BTCPay Server. Update first. Secondly, use the Vault, the direct ledger integration is obsolete and no longer used.

**Comment by Kukks** [comment]
Closing for now since this issue is no longer applicable as the bug is from a version at least over a year old and the feature used do0esn't exist anymore.

**Comment by dela15** [comment]
Ohh my bad Guys, I'm new to all this. 
I will follow the rule next time, my apology
and thanks for the help I will update my version!

**Comment by pavlenex** [comment]
No worries @dela15, hopefully it'll work for ya, if not do let us know. :beer:
