### ISSUE TITLE
[i18n] Translate the PointOfSales app

### ISSUE THREAD

**Issue by junderw** [btcpayserver/btcpayserver#243]
"Buy for `<<amount>>`" and "amount" and "Pay" are all English.

I would like to translate to Japanese:

"`<<amount>>`で購入", "金額", and "支払う" respectively

**Comment by rockstardev** [comment]
When I did custom values in POS for "Buy" and "Donate" it was possible to localize whole page completely.

Now we have Cart mode that @mariodian has done, so we may want to consider refactoring all of this and providing either ability to customize all strings directly in POS or reference translation files from page.

I think doing robust translations like we have for Invoice is best course of action - we would just need to stabilize page enough and then plug in same process that @britttttk now does for checkout/invoice.

**Comment by rockstardev** [comment]
I'm closing this issue since when initially opened we only needed to localize those two buttons - which was done.

If there is interest in localizing POS with cart checkout process - I would open new issue and track it independently. If we are to do this - I recommend start from clean slate - new BtcPayServer App that is specified and redesigned from ground up, so whoever is implementing it doesn't need to handle legacy dependencies and code for them
