### ISSUE TITLE
Pairing compatibility with BitPay

### ISSUE THREAD

**Issue by itsaphel** [btcpayserver/btcpayserver#2451]
BitPay allows tokens with the "Point-of-Sale" facade to be created without the pairing process. These tokens only allow for the creation of invoices.

As far as I can tell, BTCPayServer doesn't support this, which is an incompatibility with BitPay. Clicking "Create a new token" in BitPay requires either entering a PublicKey, or approving a pairing code. IMO the 'full' pairing process is inconvenient compared to just having the customer copy an API key from BitPay/BPS. It would be nice if BPS supported the BitPay method of generating tokens, which gives you an API key as soon as you click "Add token".

**Comment by Kukks** [comment]
We removed the facade concept since we only support invoice API compatibility with Bitpay's.   

Additionally, we do support the API token option that circumvents the pairing mechanism, it's called "Legacy" which is what Bitpay used to call it.

![image](https://user-images.githubusercontent.com/1818366/114664214-a9893d00-9cfb-11eb-82bd-df9d57d0acd0.png)

We will not do additional work around Bitpay related functionality as we are focused on providing a superior and easier API, the [GreenField API](https://docs.btcpayserver.org/GreenFieldExample/)

**Comment by itsaphel** [comment]
@Kukks I think the legacy API is a separate thing from a "POS" facade API token in the new API? I might be wrong, though. 
 Looking in the BitPay panel at least it looks like two separate things.

<img width="1247" alt="Screenshot 2021-04-15 at 05 51 45" src="https://user-images.githubusercontent.com/2878052/114815743-bca91500-9dae-11eb-853f-5045c937e5b9.png">

If indeed they are two separate things, I hope this issue can be reconsidered. It's economical for us to adjust our existing BitPay integration to work with BTCPayServer, but it's more work to create a new integration entirely.

**Comment by Kukks** [comment]
> @Kukks I think the legacy API is a separate thing from a "POS" facade API token in the new API? I might be wrong, though.
> Looking in the BitPay panel at least it looks like two separate things.
> 
> <img alt="Screenshot 2021-04-15 at 05 51 45" width="1247" src="https://user-images.githubusercontent.com/2878052/114815743-bca91500-9dae-11eb-853f-5045c937e5b9.png">
> 
> If indeed they are two separate things, I hope this issue can be reconsidered. It's economical for us to adjust our existing BitPay integration to work with BTCPayServer, but it's more work to create a new integration entirely.

Just give it a try first and then let us know.
