### ISSUE TITLE
Feature Request: other denomination units like mBTC or bits

### ISSUE THREAD

**Issue by chris-belcher** [btcpayserver/btcpayserver#250]
It would be cool to allow the payer to choose which denomination of bitcoin they want to have displayed. Somewhere to click to show the payment amount in `BTC`, `mBTC`, `μBTC`, `bits` or `satoshi`.

As one bitcoin is worth so much, many purchases will involve a decimal point and maybe leading zeros which is much harder to read and understand, and is more prone to making mistakes like sending too much or little. Bitcoin Core, Electrum and other wallets allow configuring the denomination unit. Electrum actually shows mbtc by default.

I personally use mbtc when mentally thinking about amounts. One mbtc is about $6 these days so its a useful unit. Many other people use bits or μbtc.

**Comment by NicolasDorier** [comment]
Ping @rockstardev might interest you

**Comment by Tigerix** [comment]
Please make Satoshis the default unit for lightning payments!

**Comment by rockstardev** [comment]
I've been thinking about showing prices in different denominations... especially now that LN is active and people are starting to prefer satoshis. Plus I like the word "Satoshi". I tweeted today about it (https://twitter.com/r0ckstardev/status/1097614657261658116), potentially just doing satoshis for LN payments... community response is great so it seems I should definitely do something on this front.

My only worry is that it doesn't become too confusing - person new to Bitcoin ends up in checkout and sees `3 258 466 satoshi`... will that person know it needs to send `0.03258466 BTC`?

Related question on that - in Copy tab I assume we'll keep showing value in BTC for easy copy? More user friendly option would be to provide dropdown to select denomination if we start supporting everything Chris mentioned when opening issue.
 
![copy-tab](https://user-images.githubusercontent.com/5191402/52979462-56293780-339b-11e9-8822-253850a59d42.jpg)

**Comment by chris-belcher** [comment]
How about having the dropdown menu hidden somewhere, so that newbs will by default see bitcoin or satoshi but power user customers can still choose their unit.

Regarding confusing newbs about satoshi vs bitcoin. One option is to have the displayed unit (e.g. satoshi) be in big letters and then the other unit (e.g. bitcoin) be underneath it in small letters. But a downside is the UI ends up cluttered with lots of numbers, which might be itself confusing.

**Comment by phptek** [comment]
"0 BTC, 12345678 Sat" ?

**Comment by beatljuice** [comment]
If you do denominate in satoshis it would be nice to have commas to separate it out in thousands, millions, billions, etc.. Example: 234,352,126 is easier to read than 234352126.

**Comment by rockstardev** [comment]
@beatljuice yeah, if we are implementing this we are definitely going with spaces, like `3 258 466 sats`

**Comment by patmillertime** [comment]
@rockstardev agree with that completely. Both SamouraiWallet and Bitcoin Lightning Wallet use spaces, not commas. Very functional.

Also, skip any other denominations. Satoshis are the only other denomination with ubiquitous usage

![lightning-satoshis](https://user-images.githubusercontent.com/9270876/52994552-d61bc580-33cc-11e9-909b-55d36e7f2531.jpg)

**Comment by Tigerix** [comment]
I would prefer commas. Much faster and easier to read than spaces!

**Comment by Kukks** [comment]
If you support commas, you have to support other culture-specific styles
which is a nightmare. Did you know that in Scandinavia, the usage of commas
and periods are inverted? E.g 5.000.000,09 EUR
ᐧ

**Comment by patmillertime** [comment]
I used to think commas were helpful, but I changed my mind after using Samourai and BLW.

**Comment by chris-belcher** [comment]
> Also, skip any other denominations. Satoshis are the only other denomination with ubiquitous usage

I'd like to see some data supporting this.

You've got bustabit casino which uses bits everywhere.

Remember that lots of bitcoin users don't speak english and never interact with our twitter/github communities.

**Comment by patmillertime** [comment]
> I'd like to see some data supporting this.
> 
> There is bustabit casino which uses bits everywhere. It's used by millions.
> 
> Remember that lots of bitcoin users don't speak english and also never interact with our twitter/github communities.

I definitely don't have data to support, this is merely my observation after many discussions in various places. You make a good point about other users that don't speak english and participate in these discussions.  BTCPay is in a place to be a leader, and not a follower.  Just because this is how things were done in the past, doesn't make it automatically a good idea for the future.  As a product guy, I recommend following the practices that "less is more". Adding additional UX complexity to support denominations means that they are giving up their leadership position to help guide towards best practices from a product perspective.  This is all of the insight that I can provide.  But I strongly believe that satoshi should be the base unit, and other size units should develop from that base unit; e.g., kilosats (ksats): 1 000 satoshis, Megastats (Msats): 1 000 000 satoshis, etc.  Just my 2 cents on this, that it's not too late to reduce mental complexity in the long-term.

I for one have never used mBTC or bits in 6 years, and frankly I find them confusing.  I am definitely biased in this regard.

**Comment by chris-belcher** [comment]
I understand.

The reality seems to be that nobody ever agrees on which unit to use, so I reckon the best way is to let users choose for themselves. Because the alternative is everyone trying to convince everyone else that their unit is the best. These debates on units have already been going on for years in bitcoin with no end. 

The downside with allowing users to choose for themselves is that the interface becomes more cluttered, but maybe there's a solution to keep the option menu small and out-of-the-way so that only power users notice it. Even if we settled on satoshi as a unit we'd need to be able to change to ksats and Msats.

It's worth noting that mBTC is the default unit shown by Electrum wallet when it first gets installed, that wallet is used quite a lot (I think it creates about 10% of all transactions but I don't remember where I saw that)

**Comment by corbimos** [comment]
Satoshis being displayed for LN txs is something I've been wanting for a while. 

I don't think all the others units should be included. Bits, mbits and uBTC would be more confusing to noobs. I still struggle when converting between those. But sats to BTC or BTC to sats has been very easy to get used to. 

If it could display the amount in BTC or sats like Samourai that would be fantastic.

**Comment by rockstardev** [comment]
I'm just finishing PR (#1306) that will add spacing to Sats display; we are moving in direction of:

  - BTC being displayed for on-chain transactions
  - Sats being displayed for off-chain transactions

So I'm going to close this issue since it's unlikely anyone will dedicate time to work on bits mbits and uBTC. If situation changes we can reopen... @chris-belcher feel free to hit me up on chat.btcpayserver.org if you want to talk on this.
