### ISSUE TITLE
Different icons/emoji's for notifications

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#2510]
It would be good if we can distinguish notifications with different icons or emojis.

![Screenshot 2021-05-06 at 12 02 48](https://user-images.githubusercontent.com/36959754/117281228-b82ec400-ae63-11eb-88e6-d828ec347b17.png)

Currently, we notify users on the following:
 
- New version
- All invoice updates 
- Invoice was paid after expiration  
- Invoice expired with partial payments 
- Invoice has payments that failed to confirm on time
- Invoice was confirmed paid
- Payouts

**Comment by lopezdp** [comment]
@pavlenex how is this going? id love to help this project move along a bit more; I think I can handle a few of these easy ones to get started while I familiarize myself with the project, wanna assign this to me? 😊 pleasure to meet you.

**Comment by pavlenex** [comment]
Hey @lopezdp that's great! I've assigned this issue to you. 

@dstrukt do we have any UX examples for this one that can help @lopezdp while he's on it?

**Comment by dstrukt** [comment]
Early, but some more progress here:

As you can see from left to right:

1. removing entirely, not ideal as it becomes harder to parse quickly, but arguably next to no. 2 the most scalable, no icons required, matches more closely to the notification view, etc..
2. some color dots to represent action .. interesting, but not ideal, still thought i'd share
3. some fully circular icons, look nice, but drawback is the potential to scale, as we'd likely have to reuse some of them for multiple purposes, which might not be bad considering they're pretty clear, e.g. a settled invoice could use the same notification icon as a successful payout, etc..
4. a little more context specific, e.g. the "invoice" could be rectangular, etc.. which would allow us to scale the icons to the application, but mmm, doesn't look quite as nice as the simple rounded icons of no. 3 .. there's the most room for exploration here and will likely take another pass as more "custom" icons in this format (things like hourglasses, stopwatches, paper sheet with an "X" on it, that sort of thing), but obv. this doesn't scale as well as it requires design work .. but i suppose this depends on future ambitions / needs for btcpay
5. emojis .. i'm not the best at picking these, but even after looking through all of them, i'm not really a fan of this method due to the specific nature of some of these notifs. but i suppose i could be swayed, but overall, not really a fan

![Image](https://user-images.githubusercontent.com/6250771/172037332-40dd6d95-713c-49f9-bc2f-1f89247a2740.png)

Regardless, thought i'd share to get some feedback in the midst of other things I'm pushing forward .. more updates soon.

**Comment by lopezdp** [comment]
thanks @pavlenex and @dstrukt ill start playing around a bit

**Comment by dennisreimann** [comment]
@dstrukt Can you provide icons for the following?

- Invoices
  - Invoice was paid after expiration
  - Invoice expired with partial payments
  - Invoice has payments that failed to confirm on time
  - Invoice is settled
- Payouts
  - A new payout is awaiting for approval
  - A new payout is approved and awaiting payment
  - A payment that was made to an approved payout by an external wallet is waiting for your confirmation.
- New version released

**Comment by dstrukt** [comment]
Will drop the ones that were created to you in Mattermost @dennisreimann, and we can see if we like them / swap them out if necessary, to get the PR moving.
