### ISSUE TITLE
Immature coinbase UTXOs counted towards balance

### ISSUE THREAD

**Issue by Kixunil** [btcpayserver/btcpayserver#2656]
**Describe the bug**
If BTCPay is funded directly from `bitcoin-cli -chain=regtest generate 6 ADDRESS_FROM_BTCPAY`, the coinbase UTXOs didn't reach maturity but the UI says balance is 300 BTC. Originally I thought sending is broken but realized that it's actually that message.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Setup regtest BTCPayServer instance
2. Setup hot wallet
3. Generate a deposit address for hot wallet
4. run `bitcoin-cli -chain=regtest generate 6 ADDRESS_FROM_BTCPAY`
5. Attempt to spend portion (e.g. 0.0042) of generated sats (300) - will say insufficient amount
6. Generate 100 more blocks to a different address
7. Attempt to spend all coins - will work

**Expected behavior**

The UI either reports balance without immature UTXOs and maybe additionally notes that there are immature UTXOs.

**Screenshots**

![300-btc-is-not-enough](https://user-images.githubusercontent.com/1178779/124269817-aacc4800-db3b-11eb-936e-b360b402f565.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:   1.1.2
- Deployment Method:        Debian package
- Browser:                 Firefox 78.11 ESR

**Comment by pavlenex** [comment]
@NicolasDorier can you check this out, this reminds me a bit of that wallet spending bug we've been trying to track, though I'm not sure, it doesn't look like it.

**Comment by sageprogrammer** [comment]
@NicolasDorier @Kukks I think this has to be fixed from NBxplorer side. When calling GetBalance from nbxplorer client in BTCPay, immature coinbase txn are also counted into confirmed balance, rather than unconfirmed oen.

**Comment by Kixunil** [comment]
@sageprogrammer the thing is immature is not unconfirmed either, it's just immature. So basically there should be three fields: confirmed, immature, unconfirmed.

**Comment by sageprogrammer** [comment]
> @sageprogrammer the thing is immature is not unconfirmed either, it's just immature. So basically there should be three fields: confirmed, immature, unconfirmed.

Correct, The GetBalance function in nbxplorer client will have to be changed first so that it returns confirmed, immature, unconfirmed.
https://github.com/dgarage/NBXplorer/blob/853955171e8c19bffee47831a30fb4f8dc442cce/NBXplorer/Controllers/MainController.cs#L838
Then the UI can show these seperately.

**Comment by NicolasDorier** [comment]
thanks, will take a look at it.

**Comment by NicolasDorier** [comment]
waiting input from @sageprogrammer  who fixed it. I modified slightly the API he proposed on https://github.com/dgarage/NBXplorer/pull/324
Will put it for this release.

**Comment by NicolasDorier** [comment]
I pushed a NBXplorer.Client version 4.0.1 and 2.1.54 for the docker image

@sageprogrammer you want to update NBXplorer on btcpayserver?
* Just need to use `balance.Available` rather than `balance.Total`. (however use something like `balance = balance.Available ?? balance.Total;` so we make sure old version of NBX doesn't crash btcpay)
* Change message to `your **available** balance is <available> BTC`
* If there is immature funds add a message like `<immature> BTC are still immature and need additional confirmation`.

No need to make a unit test imho, this is a real corner case and people having immature funds probably know what they are doing.

**Comment by sageprogrammer** [comment]
changing to NBXplorer.Client version to 4.0.x causes some issues.
I suspect this is due to different version of NBitcoin used in BTCPayServer & NBXplorer.Client.
`NBXplorer.Client 4.0.1 -> NBitcoin 6.0.3`
`BTCPayServer ->  NBitcoin 5.0.81`
I suspect it is due to some differences in the function signatures of `Sign` & `SignAll` between version `6.0.3` & `5.0.81`.
So I think we need to fix those issues first as we need NBXplorer.Client version 4.0.1 for this issue.
I could work on that issue too.

**Comment by NicolasDorier** [comment]
Are you sure you pull latest @sageprogrammer ? Because I already updated BTCPayServer.

**Comment by NicolasDorier** [comment]
(btw, meanwhile I did another update of NBxplorer.Client and NBXplorer)

**Comment by NicolasDorier** [comment]
I try to bump it again on https://github.com/btcpayserver/btcpayserver/commit/2207d836f1d480e6ecfd952f748f13b04614f5f1 to make sure things are ok

**Comment by sageprogrammer** [comment]
Ah! I realized I was really on an outdated pull. Will quickly work on this issue

**Comment by sageprogrammer** [comment]
So here is how it is showing
**Immature BTC > 0**
![20210801_13h20m33s_grim](https://user-images.githubusercontent.com/16453468/127763784-5ae42e7d-37b7-462b-b713-15ff4b80b2f5.png)

**Immature BTC = 0**
![20210801_13h24m39s_grim](https://user-images.githubusercontent.com/16453468/127763817-286b2250-0f4b-4d55-891c-516ae340edfa.png)

**Comment by Kixunil** [comment]
Thanks a lot folks!
