### ISSUE TITLE
shopify multi-currency is not supported

### ISSUE THREAD

**Issue by Gfloresechaiz** [btcpayserver/btcpayserver#2683]
**Describe the bug**
Hi, I'm reporting a shopify integration bug. I have a Shopify store that's multi-currency, however BTCPay Server Checkout only seems to be possible in USD.

For example, if I checkout with CAD (Canadian Dollars), as soon as I select BTCPay Server as the payment option, the price gets converted to USD. 

Also, it doesn't get converted to my USD set value for the product but to what the exchange rate (shopify's I guess) says it should be. For example, my product is set to 26$ CAD or 20$ USD. If I checkout with 26$ CAD, it converts to 20.6$ USD since that's what the exchange rate calculates.

Is there a way to use BTCPay Server Shopify Integration and checkout on the set currency? Thanks a lot for the constant great support.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to a Multi Currency Shopify Store with BTCPay Server Integration. 
2. Select a different currency than USD e.g. CAD.
3. Checkout, enter all required information and select ''Pay with BTCPay Server''.
4. Watch prices get converted back to USD.

**Expected behavior**
1. Prices should remain in the selected currency. 

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    latest version
- Deployment Method:        luna node
- Browser:                  firefox

**Comment by rockstardev** [comment]
@Kukks from what I remember we were creating invoice in BTCPayServer depending on currency that Shopify passes to our API.

Looked through code and found:
https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Plugins/Shopify/ShopifyController.cs#L193

So is this an error on Shopify side? They are automatically converting to whatever is the country of customer and then sending $20.6 USD our end?

I want to make sure it's error on our end before I talk with @sagecoder or @cypherbeerus about potentially helping with this issue.

**Comment by pavlenex** [comment]
ping @Kukks

**Comment by Kukks** [comment]
Based on https://shopify.dev/api/admin/rest/reference/orders/order, the currency sent on an order is the "shop currency". They seem to have additional currencies based on the current total though (called presentment_currency). We need to update our C# APIclient code to use their new fields

**Comment by ademers** [comment]
Hi, I see this issue was closed, but I’m still experiencing the same problem with Shopify auto-converting CAD to USD before passing it to BTCPay Server.

- Shopify store currency: USD
- Customer checkout currency: CAD
- BTCPay Server version: 2.0.6
- Shopify Plugin version: v1

Before opening a new issue, I wanted to check if this is expected behavior or if there’s a recommended workaround.

I’m also planning to upgrade to Shopify plugin v2 once it’s available on the Shopify App Store. If this is already addressed in v2, I’d appreciate any insights.

Would it be best to open a new issue for tracking, or is this something that’s already being worked on? Thanks for your time!

**Comment by pavlenex** [comment]
Hi @ademers, I'll let @TChukwuleta or @ndeet answer your question about auto-currency conversion, from what I understand your store supports multiple currencies, and your BTCPay is in USD? What exactly needs to be converted, normally a customer will just check out normally, do you mean the checkout doesn't work?

> I’m also planning to upgrade to Shopify plugin v2 once it’s available on the Shopify App Store. If this is already addressed in v2, I’d appreciate any insights.

You can upgrade right away, it's very unlikely that the app will come to the app store, so you need to run it yourself, Shopify TOS aren't clear about payment processing when there are no fees or intermediary.

**Comment by ademers** [comment]
Hi @pavlenex ,

Yes, my Shopify store supports multiple markets and currencies (USD, CAD), but the store currency is set to USD. The issue is that when a customer checks out in CAD and selects Bitcoin (via BTCPay Server), Shopify converts the CAD total to USD before sending the amount to BTCPay Server. This means that instead of paying the CAD total converted to BTC, the customer ends up paying based on the USD equivalent.

I was expecting that Shopify would pass the original CAD total to BTCPay Server, and BTCPay would then convert that to BTC based on its exchange rate rules set in BTCPay Server. Is this expected behavior, or is there a way to ensure BTCPay receives the original CAD total instead of the USD-converted amount?

I also noticed that when I change the Shopify store currency to CAD, customers who check out in USD see their total converted to CAD before it’s passed to BTCPay Server.

Also, regarding Shopify plugin v2, I noticed that the [BTCPay documentation](https://docs.btcpayserver.org/ShopifyV2/#using-btcpay-shopify-from-shopify-app-store) states:

> WARNING
> As of now, the BTCPay-Shopify app is not yet available on the Shopify App Store. We are working on getting it published.

However, you mentioned it’s very unlikely to be listed due to Shopify’s TOS. Can you clarify whether the plan is still to publish it, or should merchants assume that self-hosting will be the only option?

Thanks!

Screenshots:
![Image](https://github.com/user-attachments/assets/c92292bd-51f4-4633-a68b-eb7b068910bf)
![Image](https://github.com/user-attachments/assets/c32fc158-0516-4985-a25f-b1a71a83ac6f)
