### ISSUE TITLE
Greenfield API: Get invoices with Order ID filter as array does not work.

### ISSUE THREAD

**Issue by woutersamaey** [btcpayserver/btcpayserver#2736]
**Describe the bug**
The docs tell me that I can load invoices by orderId as an array. This does not work. It works if `orderId` is a string, but not an array.

![image](https://user-images.githubusercontent.com/71019/127782641-a75a87b2-e4c2-4506-b185-16b43a833869.png)

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Just run the API call with `?orderId[]=1000&orderId[]=1001&orderId[]=1002` assuming 1000,1001 and 1002 are order IDs you have in `metadata`. You will get ALL invoices returned instead of a filtered set.
2. Calling the API with just `?orderId=1000` as a string (not array) and you will get the invoices with this order ID (but only 1 order ID can be given).

**Expected behavior**
- Either doc needs to be fixed or API call should work.
- The call should return an error if a querystring parameter is not understood. Like in my case I'm trying to filter using multiple order IDs, but I get all invoices. An error like "invalid filter parameter" would make sense instead of giving me all invoices which I was certainly not expecting.
- Maybe more and other filter options would be nice, but that's not the issue here.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:   Latest
- Deployment Method:      Docker
- Browser:              N/A

**Comment by bolatovumar** [comment]
@woutersamaey I just tested this and it seems to work as expected. I think you are just formatting your query string wrong. Instead of using `?orderId[]=1000&orderId[]=1001&orderId[]=1002` try `?orderId=1000&orderId=1001&orderId=1002`. I tried it with `http://127.0.0.1:14142/api/v1/stores/9sTGRW5iWvwsLB2V67BwYk9JdkFKqYNuuSYK12Sm4NXr/invoices?orderId=PAY_REQUEST_4ff7a1dd-f53a-4823-a31f-77813c680dc0&orderId=PAY_REQUEST_5978c6a8-1054-4c77-a7b8-b0a6c7150cba` locally and it's working as expected (I get two items in the response).

**Comment by woutersamaey** [comment]
I did some research and turns out this is very framework dependent. Because of my PHP background, I tried it with [] attached, but it appears some frameworks do it like you suggested.
So I guess it’s not a bug, but it’s not included in the docs how the formatting should be either.
We should still improve the docs with a sample then…

**Comment by bolatovumar** [comment]
@woutersamaey I made a PR that adds an example to the docs here: https://github.com/btcpayserver/btcpayserver/pull/2759
