### ISSUE TITLE
If an app maps  `root` domain, the .onion in Tor, redirects to the login page instead of the app.

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#2792]
**Describe the bug**
It's been reported on Twitter that our crowdfunding campaign [bitcoinsmiles.org](https://bitcoinsmiles.org) when view in Tor Browser the .onion redirects to the server login page instead of the app.

I've replicated the issue, and this happens because the app is mapped to domain's root. I'm not sure if this is something that's fixable, but would be good to fix it if it's possible.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Map the crowdfunding app to a domain root in Server Settings.
2. Visit the root domain via Tor Browser

**Comment by pavlenex** [comment]
@NicolasDorier Unfortunately this issue is not fixed in 1.2.1 not even with https://github.com/btcpayserver/btcpayserver/commit/77d1580ee3871f34945af8569527630ddeb81f9a

**Comment by dennisreimann** [comment]
I think I know what's going on:  The "Display app on website root" policy works for me with a Tor URL, the "Domain to app mapping" does not, because the policy [checks against the host](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Filters/DomainMappingConstraintAttribute.cs#L36) - which in this case is the onion URL host and has been defined as the clearnet domain. (-> pavlenex.com != pavlenex.onion ;))

It works if one creates one more domain mapping for the onion host - in addition to the clearnet host.
If one uses the "Display app on website root" policy it works out of the box with both the clearnet and onion host.

So, in general I'd say it works as intended -- the question is whether or not and if so how to "fix" it.

**Comment by pavlenex** [comment]
@dennisreimann is right.

The way for this to work is as follows:
![Screenshot 2021-08-31 at 13 00 25](https://user-images.githubusercontent.com/36959754/131491316-3ee68b24-7ce3-44a0-b879-22d8351a8184.png)
