### ISSUE TITLE
lnd-migration,  recreate_bitcoin_lnd.sh does not exist.

### ISSUE THREAD

**Issue by Transisto** [btcpayserver/btcpayserver#2871]
./recreate_bitcoin_lnd.sh

following
https://blog.btcpayserver.org/btcpay-lnd-migration/

**Comment by pavlenex** [comment]
Please do not ignore the issue template, we cannot understand what you're trying to do, which version you're migrating from, etc



**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**



**Screenshots**




**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    
- Deployment Method:        
- Browser:                  

**Logs (if applicable)**




**Setup Parameters**



**Additional context**

**Comment by Transisto** [comment]
Latest version, problem when following the instructions to enable seeded LND.

The sh file to execute does not exist in that directory or anywhere else.

**Comment by pavlenex** [comment]
What is it that you're trying to do and has your instance been deployed prior to `1.0.3.138`?

**Comment by Transisto** [comment]
Yes, deployment was originally done with 1.0.3.49

**Comment by Transisto** [comment]
I'm trying to enable lightning payments and backup the seed of the LND

**Comment by dennisreimann** [comment]
I took a look and the script got moved to `Tools/lnd/lnd_recreate_volume.sh` with [this commit](https://github.com/btcpayserver/btcpayserver-docker/commit/a86252dde1d47972de3f8603858a9564725b1d02#diff-ea93d6a262ecb87a9fa4d09edbd7654c046597936a8e235fc3949eb01775ff99).

I've [updated the blog](https://github.com/btcpayserver/blog/commit/b52243bfde2eaed4333d70eac76aeee3a813cee6) to reflect that change.
