### ISSUE TITLE
Troubles with NBXplorer

### ISSUE THREAD

**Issue by purpurato** [btcpayserver/btcpayserver#2877]
My btcpayserver instance seems to be working fine and I can see my LND node public now, but cannot make any transaction with lightning. These are the logs:

`[ERR] Error while connecting to WebSocket of NBXplorer (BTC)
System.Net.WebSockets.WebSocketException (0x80004005): The socket has been closed (NormalClosure: Close message received from the peer)
   at NBXplorer.WebsocketMessageListener.CloseSocketAndThrow(WebSocketCloseStatus status, String description, CancellationToken cancellation)
   at NBXplorer.WebsocketMessageListener.NextMessageAsync(CancellationToken cancellation)
   at BTCPayServer.Payments.Bitcoin.NBXplorerListener.Listen(BTCPayWallet wallet) in /source/BTCPayServer/Payments/Bitcoin/NBXplorerListener.cs:line 137`

I have just updated to the latest version and tried restarting the server, but still getting this. 
I deployed using docker on contabo.

**Comment by pavlenex** [comment]
@purpurato Do you still face an issue?
Can you please not skip the appropriate template when filing an issue?
To troubleshoot these we need:



**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**



**Screenshots**




**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    
- Deployment Method:        
- Browser:                  

**Logs (if applicable)**




**Setup Parameters**



**Additional context**

**Comment by dennisreimann** [comment]
Possibly related to #2895?

**Comment by purpurato** [comment]
Hello, 
I am sorry for the poor formatting. 
This issue is now gone, I am not sure how, but my LND node no longer shows this on logs. I used to have problems on the node for channel balancing and a couple other features that are now fully operational.
