### ISSUE TITLE
Crowdfunding

### ISSUE THREAD

**Issue by bitcoinshirt** [btcpayserver/btcpayserver#313]
There are lots of content creators who may want to have a campaign with BTCPay to raise some funds.

I like the idea of [TallyCoin](https://tallyco.in/s/demo/)

Simply said, it can be an APP which creates the page, where we will have:
1. A button similar to the payment button
2. HTML text for description
3. Amount Goal
4. Progress (showing the balance vs goal)
5. Timer

I think it can be a great use-case for podcasters, content creators and even charities to raise funds in a private but transparent way.

![crowdfund btcpay](https://user-images.githubusercontent.com/36959754/46522464-21e92a80-c883-11e8-89e9-0be87e25554c.png)

**Comment by Kukks** [comment]
This could probably be good as another "application" type.

would having donation perks be part of the same scope of this? (0.1btc gets you a tshirt, etc)

**Comment by bitcoinshirt** [comment]
Agreed has to be a new app. Actually, I'd prefer payment buttons in an app, but that's another issue.

Hm, well I think we can start simple, without too much complexity, but sure, why not. It can then be a bit more like Patreon.

So if we make it, start simple and build features in it if there's interest in such features.

**Comment by NicolasDorier** [comment]
Really love it

**Comment by ketominer** [comment]
I like the general idea, but shouldn't that be a separate service built on top of BTCPay Server? I think BTCPay should continue doing what it does best, processing payments, and higher "value added" features should be separate projects. The PoS is cool but it's already borderline...

Maybe it could be part of a BTCPay Suite of tools but be a separate project?

**Comment by bitcoinshirt** [comment]
@ketominer But why?
BTCPay should free people not lock them into subscription model crap. It's a separate app like POS.
I would prefer that BTCPay does not try to make any "money" out of small people like content creators. Institutional apps can be put in "suite" but that sounds way to ugh...

**Comment by bitcoinshirt** [comment]
There was a talk to have plug in modals, but I don't think that's going to happen any time soon. The whole UI needs to be re-written for that.

**Comment by ketominer** [comment]
But should the payment processor be a CMS? I think the payment role is critical enough to deserve an app doing that and only that... but of course if I'm a minority thinking that I will shut up :)

Just makes it less scalable and harder to run in real production environments.

**Comment by ketominer** [comment]
Last but not least (I promise I shut up after this one) it would be sad to compromise the security of the payment processor because of a bug in some additional feature which doesn't require the same level of security :)

**Comment by NicolasDorier** [comment]
I think that's fine. If a piece of code becomes less use, then it will slowly go away.

The "Apps" concept has been done to prevent too much leakage of specific apps into BTCPay overall source code.
I think those apps have their place in BTCPay because the alternative is having people rely on central party. (like tally coin or money button)

In an ideal world, people could make apps on top of BTCPay with the same ease of deployment. But I think it is not likely the case.

Today we have actually very few use case to cover. Patreon, Tallycoin, basic crowdfunding, and decent PoS.

**Comment by Kukks** [comment]
@djbooth007  You can create an invoice on btcPay and set the notificationUrl to an endpoint you listen to to know an invoice has been paid. You can use the bitpay auth and api to then fetch the invoice through the api then

**Comment by gerbz** [comment]
I tend to agree with @ketominer - to have core BTCPay team members working on apps seems like a poor use of resources, especially when there are more important features (like Ethereum and New API) to be worked on.  The goal should be to focus on building the best non-custodial payment processor and have app developers (like TallyCoin) use it.

**Comment by bitcoinshirt** [comment]
> especially when there are more important features (like Ethereum
Ethereum is not a feature, ain't nobody gonna work on that.

**Comment by britttttk** [comment]
@gerbz. This is from the BTCPay altcoin documentation, in reference to your Etherium comment:

> BTCPay developers do not implement alternative coins on request. Adding a new coin explicitly depends on the community and developers of those coins. Furthermore, BTCPay developers do not spend excessive time testing nor maintaining the altcoins. If you're submitting a PR for a new coin, make sure your image works. If the altcoin integration is not actively maintained it will be removed from BTCPay. https://github.com/btcpayserver/btcpayserver-doc/blob/master/Altcoins.md

In my opinion, app development is a very good way for new contributors to join the BTCPay community, which to me, is very important. Even if they are simply new users. Whereas altcoins/API are a bit more specialized. Obviously, developers can work on what they prefer, BTCPayServer is not a company, it's an open source community.

Personally, I want BTCPay contributors to work on specialized features, so I try to help facilitate them by doing some of the tasks which don't require as much specialization, so that they can focus more on that kind of development. Less complicated tasks can be completed by new contributors but only if those opportunities exist. So you see it's kind of like a chicken and egg thing.

**Comment by gerbz** [comment]
Apologies if I've struck a nerve here.  I understand that every contributor is free to work on anything they wish, and I have no problem with apps.

Maybe I'm just more curious about the roadmap overall.  I'll move this discussion to slack.
