### ISSUE TITLE
Wallet balances.

### ISSUE THREAD

**Issue by erald** [btcpayserver/btcpayserver#3456]
I have version 1.4.0 on my server and trying to find where I can see the balances of the wallets. As admin I cannot see them anymore nor can the shop owner see his wallet balance.
Am I just overlooking it or is that feature gone. The documentation is for the older versions and does not give me anything I can use.

**Comment by pavlenex** [comment]
There's no way to collectively see the balance of the wallets of multiple stores. 
For a single store you can now use a workaround and go to wallet >send to preview it.

![Screenshot 2022-02-15 at 17 47 04](https://user-images.githubusercontent.com/36959754/154108657-2c45f64c-f108-4f3c-8709-987aead01124.png)

There are plans to showcase a single store balance in the dashboard #1711 though which is coming in 1.5.0. 
We'll definitely see how we can make it possible to have a balance per user for multiple stores, since a few people requested it already. cc @dennisreimann @dstrukt 

Will close this as it's being considered in #1711 already.

**Comment by dennisreimann** [comment]
As a workaround you can still go to `/wallets`. We don't link there anymore and will most likely replace that page with a better solution (hint hint dashboard), but for now that's at least still present.
