### ISSUE TITLE
Invoice filtering should match the `greenfield api` statuses.

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3573]
It's time that we address invoice filtering statuses.

Right now, when you click on invoice filters this is what you get:
![Screenshot 2022-03-24 at 21 38 02](https://user-images.githubusercontent.com/36959754/160009692-d7aa6753-2f12-4da5-834f-be9acbd9f3dc.png)

A few things:
- `Paid` status no longer exist, calling invoices `paid` is inaccurate.
-  `Paid`was replaced with `Settled`
- Drop down `paid` filters `settled` and `processing` 

Questions:
1. Should we just use terminology that 100% matches statuses and show that
2. Should we use collared labels in dropdown so people can easier distinguish statuses?
3. `Unusual` is weird but very useful, any other name for this one, its' not a status per se, but a collection of statuses that require attention?

This issue requires collaborative effort from back-end and design teams to come up with technically accurate but easy to use solutions that doesn't introduce complex terminology and innacurate naming. pinging @NicolasDorier @dennisreimann @dstrukt @Kukks

**Comment by bolatovumar** [comment]
> Should we just use terminology that 100% matches statuses and show that

I think this makes sense. It's especially weird when you click on "Paid" and see "Settled" and "Processing" in the "Status" column while this banner shows up above. It's not too bad though and people would probably make the connection between these.

![Capture](https://user-images.githubusercontent.com/1934678/160264844-df4c6a80-5d08-410d-986f-fd13b1241791.PNG)

> Should we use collared labels in dropdown so people can easier distinguish statuses?

Some statuses map to labels of different colors. "Paid over" maps to green "Settled (paid over)" and red "Invalid (paid over)"

> Unusual is weird but very useful, any other name for this one, its' not a status per se, but a collection of statuses that require attention?

I kind of like "Unusual". Another name that could apply here is "Unexpected".

**Comment by pavlenex** [comment]
@bolatovumar I think we should use the coloured statuses, it kinda communicates well if something is okay, wait or bad, so I'd match those same way we colorize them in the invoices page.

I guess you're right about the `unusual` I was just thinking if there's a better term like `Action needed` or something implying these invocies in most cases need to be addressed or require a reaction from a merchant.

**Comment by phershbe** [comment]
I can work on this if you still need somebody to!

**Comment by bolatovumar** [comment]
> @bolatovumar I think we should use the coloured statuses, it kinda communicates well if something is okay, wait or bad, so I'd match those same way we colorize them in the invoices page.

What color would be used if the same status maps to two different colors like in my example above?

**Comment by pavlenex** [comment]
@bolatovumar There's no such case where the same status would map to two different colors. The example you provided is because in the legacy API indeed Confirmed and Complete were same or very similar. 

We should basically reflect what we have on the invoices view.

![Invoices](https://user-images.githubusercontent.com/36959754/160553008-090b161c-fb8c-4694-b6ae-800f4309ba0b.png)

**Comment by pavlenex** [comment]
@NicolasDorier Do you think we should mark `Expired PaidPartial` also in `Red` color. Now it's grey, grey gives impression no action is needed, but actually merchant would want to either issue a refund or contact customer to pay due, so I'd say `red` since the action is required.

**Comment by theBitcoinDeveloper** [comment]
Hi @pavlenex, @NicolasDorier , @bolatovumar  

I worked on it and changed the drop down of _Paid to Settled_ and I played a little with colors as well. I personally think the **drop downs should NOT be colorful**. Simple is better. I do agree with Expired or PaidPartial to be changed to Red color on the data rows. 

Here is a screenshot with same color as the ones in datarow for settled items. I added styles for unusual and archived invoices, however, I could not find logic to change color for them in line items in the codebase. 

![Screenshot from 2022-04-18 21-24-16](https://user-images.githubusercontent.com/96552652/163920008-22caddd7-64fd-4094-b757-095fe775073d.png)

The below screenshot has different shades of green instead of the same one. 

![Screenshot from 2022-04-18 21-22-41](https://user-images.githubusercontent.com/96552652/163920028-125d50f5-1f00-4c9a-99fa-af6e8aac6f6a.png)

Having it simple in the dropdown is more pleasing to the eyes in my opinion. 

Please let me know your thoughts. If you agree with Paid to be changed to Settled then I would love to PR my changes.

Thank you!

**Comment by bolatovumar** [comment]
ping @dstrukt @pavlenex ^^^^^^^^

**Comment by theBitcoinDeveloper** [comment]
PR number https://github.com/btcpayserver/btcpayserver/pull/4000 (4 Millenium) for your review
