### ISSUE TITLE
README link to local development environment instructions broken

### ISSUE THREAD

**Issue by phershbe** [btcpayserver/btcpayserver#3590]
In the README https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer.Tests/README.md the link to the local development instructions is broken.

<img width="1054" alt="tooling documentation" src="https://user-images.githubusercontent.com/25594870/160874722-29e1089b-bdbe-4986-8e42-350700c50920.png">

The broken link sends you here: https://docs.btcpayserver.org/LocalDevelopment/

Correct me if I'm wrong, but the link should probably send you here: https://docs.btcpayserver.org/Development/LocalDevelopment/

**Comment by pavlenex** [comment]
Nice catch, that's right, you wanna tackle this one @phershbe?

**Comment by phershbe** [comment]
@pavlenex Yeah I got it. I still have some questions about how to name branches and am having problems setting up the local development environment (hence why I was on the README), but those things aren't necessary in order to get this done I think. I made an account in the chat and will probably ask in the "Development" section there if I'm still stuck soon.

**Comment by pavlenex** [comment]
Yeah hop on to our mattermost (Tip: Install Mattermost app, it's better than using it via web) and we'll help you out. There are quite a few videos that explain it.

**Comment by phershbe** [comment]
Okay, thank you. Yeah I watched the video about Server Development on MacOS but still got stuck somewhere. I have the docker container running, it's after that that I have problems. I'm trying to go back over the video and the webpage that explain it in order to to make sure I'm not making any stupid mistakes, but if I'm still stuck soon I'll get in the chat.

**Comment by phershbe** [comment]
@pavlenex I forked the repository and made the pull request thinking that it would go to maintainers to be checked. It's not in the list of pull requests in the base repository, and on my fork under pull requests I have the option to "Merge pull request". When I click that does it automatically merge? Is this because somebody has given me push access in this case? I suppose that it should be fine for me to click that but I wanted to check to make sure and also try to understand what's going on.

**Comment by pavlenex** [comment]
That's because you did a PR on your own fork instead of our's main repository.
What you did is:
1. Forked BTCPay ✅ 
2. Created a branch ✅ 
3. Made changes ✅ 
4. Saved and commited a change ✅ 
5. Created a pull request ❌ - On this step you've chosen a wrong repository when submitting a PR.

I am not sure what you're using as your enviroment, but some good resources on how to do a PR can be found [on this page](https://bitcoin.design/guide/contribute/propose-a-change/#creating-a-pull-request) of the @bitcoindesign community that I wrote a while ago. 

Specifically you should've have something like this

![Screenshot 2022-03-31 at 23 44 22](https://user-images.githubusercontent.com/36959754/161154389-3ce3a19e-b1ec-47bf-a3d7-71acc3b24e3d.png)

In BTCPay example, you need to set base repository to `BTCPay Server master` and head repository, your own fork.

The changes can only be done by you proposing a change to our main repository, us reviewing it and merging 😃 

In your case, you need  to change the base of your pull request, by googling I found this https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request

**Comment by phershbe** [comment]
@pavlenex Really amazing. This is way above and beyond, I'm self-taught so this kind of personal feedback is invaluable for me. I'm very grateful for the information, thank you. It's late here but I will sort this out tomorrow.

**Comment by pavlenex** [comment]
Closed in #3602
