### ISSUE TITLE
`Integrations` should be `Store Plugins` and `Plugins` should be `Server Plugins`

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3594]
Right now we're using quite a few different terms. `Integrations` within the store is basically a store plugin page.

`Store plugins` should show plugins server admin activated  and allow people to access the plugin (click on them), but shouldn't allow adding plugins or disabling them.

`Server plugins` is basically what we now call `plugins` which are available to admins only.

Both pages should allow people to access plugins and open them. Right now we have plugins like whitepaper or hairstylist which once activated nothing happens, because a user isn't aware where they can access them, so allowing easy way to access activated plugin should be had in mind when re-making these pages.

I've discussed this with @Kukks and it seems we'd want to do it for 1.5.0 if we can, otherwise for 1.6.0

**Comment by dennisreimann** [comment]
@Kukks We decided that we want to simplify the concepts for the user, hence the goal is to simply call integrations "plugins" from now on. Technically and internally we can distinguish the different concepts, but we should not surface that to the user.

So the general idea is to rename the store Integrations page to Plugins (think "Store Plugins") and adapt the wording on that page - otherwise it'd stay the same. Store-related plugins can offer an entrypoint to their setup and configuration on that page.

All plugins should be installable on the "Manage Plugins" page, which is available only to the admin in the sidebar. Installed plugins can offer entrypoints depending on whatever fits best for the particular plugin.
