### ISSUE TITLE
Add `store's default currency` to the dashboard wallet balance

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3661]
User should be able to toggle between a store default currency and a BTC balance on the dashboard.

Not sure how we could make `toggle` action obvious, or should it be side by side. I think most wallets have toggle, so should be fine as long as it's clear a user can click. The conversion logic should already exist in the `Wallet` > `Send` tab where a BTC amount is converted to store's default currency.

![Screenshot 2022-04-21 at 12 06 53](https://user-images.githubusercontent.com/36959754/164432228-56f231bc-19a0-4cca-9e1d-ac5a29881a6e.png)

This should address most concerns in https://github.com/btcpayserver/btcpayserver/discussions/3637

![Screenshot 2022-04-21 at 12 10 34](https://user-images.githubusercontent.com/36959754/164432892-af1f17a7-b487-4feb-a601-c2b4c9890226.png)

**Comment by ishristov** [comment]
Is the "wallet balance" on the dashboard a combination of the on-chain balance AND the lightning wallet that's configured for the store?

IMO if you are managing a store, the more important info that you care about is the received amounts for a particular period (in btc and fiat) and not the wallet balance. The wallet balance graph (balance for different days) is not very useful and shouldn't be the center of the dashboard. The received payments (settled invoices) should be.

With that being said, issues in #3637 are something different and not really addressed by this.

**Comment by pavlenex** [comment]
You can filter periods in dashboard. 

> Is the "wallet balance" on the dashboard a combination of the on-chain balance AND the lightning wallet that's configured for the store?

No, on-chain only.

**Comment by ishristov** [comment]
I understand that LN is different. But I'm talking from the user's perspective. They (I'm also running a store for selling stuff so I'm also on that side) don't care about a "wallet balance" if they also receive LN payments. What they MOSTLY care about when they login in btcpay is to see what PAYMENTS have been received, not the balance 1 week ago (the current graph in the new dashboard). The important thing is how much value in FIAT have been received, because usually there's a legit business running the store and they want to tax and account these payments. Which is done by checking the total FIAT representation of the paid invoices.

I know I (and they) can make almost everything in excel/google sheets but is that what you really want for the btcpay users? To export files on their mobile phone, then importing it in google sheets and then making a pivot table just to see a sum of the paid invoices in USD? :)

If you think that this will be taken into account, I can work on some more concrete suggestions, but these summaries (totals received in fiat for 1d, 7d, 30d, 1y, easier filter for dates, etc) must be handled sooner than later. The new in-progress graph with the "wallet balance" on the dashboard can be ditched as it doesn't provide any real value (same as in the ledger live dashboard). If you don't believe me, talk with some other real business that is actually using btcpay for receiving payments.

**Comment by pavlenex** [comment]
All of our decisions are based on real feedback and users. Adding LN to the dashboard is something we discussed for 1.6.0.

There are many different type of users and we cannot really cather for every specific use-case so adding flexibility in how people handle data is a good trade-off.

I disagree that wallet balance is useless, it's a good start and better than nothing. We're a small team doing incremental changes, you're free to tackle the issues and help us expedite thing, or fund a developer to help. Otherwise, feel free to add suggestions, we value feedback, but cannot take every single use-case into account ,though we do our best to do that.'

Let's keep discussion focused on this specific issue and featuture which is adding store curerncy to the balance, any other comments are welcomed on chat.btcpayserver.org

**Comment by dstrukt** [comment]
@ishristov Appreciate the feedback, and understand where you're coming from .. but rest assured, there will be some great improvements to both Dashboard/Invoices in 1.6.0. 

We've been heavily focused on improving the overall usability of the admin side of things, and are now continuing to focus in on these more specific use-cases, etc.. similar to what you're mentioning but as @pavlenex we're a small team and there's a lot to tackle, but please continue to highlight your needs and we'll do our best to address them!

**Comment by ishristov** [comment]
Noted. I didn't mean disrespect. I've created #3669 to keep track of it and stop spamming the current topic. If you need hands for the front-end of this, I can help.

**Comment by Aheyachy** [comment]
👍
