### ISSUE TITLE
Improve invoice filtering UI

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3664]
Currently, invoice filtering is cryptic and people aren't really aware they can toggle the filter.

![Screenshot 2022-04-21 at 12 56 28](https://user-images.githubusercontent.com/36959754/164464525-b7ddcb82-dfd9-4de7-b1fe-a268e7cd5194.png)

Some good suggestions were made in this discussion, but TLDR:
- Add a multiselect drop down for store & status filtering (bear in mind user should be able to filter by mutliple stores, statuses).
- instead of typing startDate, endDate -> show 2 datepickers for start and end date;

This PR from 2019 can server as an inspiration, but ideally we should tend towards simplicity. https://github.com/btcpayserver/btcpayserver/pull/771

Another question would be how to make the toggle more obvious since people weren't really aware of these options.

**Comment by fabu21** [comment]
What do you think about a solution like this? Could also be used for date (from - to) and amount (from - to). 

![image](https://user-images.githubusercontent.com/87422685/165837084-f0e22ca6-2856-405e-b80b-43e08ac969ec.png)

Instead of the dropdown-icon we could also use the "filter" icon. Maybe this would also clarify the function on the left side of the search input field.

I'm aware that this is not working for stores. Maybe we find another idea to tackle this problem.

**Comment by dstrukt** [comment]
Few thoughts on the above:
- Being able to filter by status is important, a critical feature to surface, so definitely agree, conceptually

- However, shouldn't be incorporated into the table header (imo)
-- adds noise at too low of a hierarchical level
-- ideally whatever pattern we develop, we should be able to leverage as a consistent pattern across all table views
-- don't feel this approach enables max flexibility in the future (e.g. updating the "status" -> "expired" text on selection)
-- mobile limitations and considerations (resolvable, but worth noting)

- Could be a drop-down, could be a tabbed menu, etc.. but..

- Additionally, we need to be considering all of the filter functionality, not just a subset of the filters, otherwise we're left with a dropdown selector for one, and the rest tucked back behind the current functionality, not ideal, imo.
-- Few considerations, how accessible are some filters vs. others, etc..

After exploring a few things as well, I think labelling this a "good-first-issue" is inaccurate. This table view, and the component table pattern touches the entire app, and shouldn't be patch-worked, but a holistic solution that scales across all views.

**Comment by dstrukt** [comment]
Exploring as a more flexible component
<img width="1020" alt="Screen Shot 2022-04-28 at 3 27 11 PM" src="https://user-images.githubusercontent.com/6250771/165858125-96271a70-f4ac-447c-8a08-0a702fc742ce.png">
<img width="1019" alt="Screen Shot 2022-04-28 at 3 27 15 PM" src="https://user-images.githubusercontent.com/6250771/165858133-af0d52e8-71fe-49ed-9183-710e51bfa7f5.png">

Mass Actions Iteration:
<img width="1014" alt="Screen Shot 2022-04-28 at 3 27 59 PM" src="https://user-images.githubusercontent.com/6250771/165858400-e75c722c-c334-4412-a85b-068ce2caed7f.png">



OLD: Starting to put some of the existing components in the framework to see how feasible it would be:
<img width="714" alt="Screen Shot 2022-04-28 at 3 28 34 PM" src="https://user-images.githubusercontent.com/6250771/165858305-7af66507-45fe-4562-aea4-5d13759e936c.png">

(OLD) Early explorations from the last 1-2 weeks:
<img width="675" alt="Screen Shot 2022-04-28 at 3 27 35 PM" src="https://user-images.githubusercontent.com/6250771/165858195-68d66056-040d-419c-bdc7-075e6733c760.png">
<img width="713" alt="Screen Shot 2022-04-28 at 3 28 26 PM" src="https://user-images.githubusercontent.com/6250771/165858301-e6afb4a7-bde2-42f4-83f1-2af33c55c43a.png">

**Comment by dstrukt** [comment]
More progress. Refined the thinking and focused solely on Invoices in this exploration .. but will extend to all other views to see how well it holds up:

Extracted all of the filterable content into a few labeled examples with the mobile counterparts:
<img width="1680" alt="Screen Shot 2022-06-05 at 1 07 15 AM" src="https://user-images.githubusercontent.com/6250771/172041607-6bfe6c36-d974-4f9c-8fea-4413dda1a399.png">
Showed examples with "Start/End" vs. "All Time", another small variation we could explore depending on feedback.
<img width="1720" alt="Screen Shot 2022-06-05 at 1 07 23 AM" src="https://user-images.githubusercontent.com/6250771/172041610-f6f0eb66-f743-4622-9170-3acb304c44cb.png">
<img width="1715" alt="Screen Shot 2022-06-05 at 1 07 34 AM" src="https://user-images.githubusercontent.com/6250771/172041611-35b833de-3840-453b-ba15-a01e1b7ec666.png">
<img width="1498" alt="Screen Shot 2022-06-05 at 1 07 42 AM" src="https://user-images.githubusercontent.com/6250771/172041612-4e16e950-819f-4b17-aacd-128134e57a54.png">

Only other functional pattern that crossed my mind was multi-select per dropdown filter (other ways we could explore this as well), but wanted to see if this is something we *might* want to support, e.g:
<img width="833" alt="Screen Shot 2022-06-05 at 1 12 13 AM" src="https://user-images.githubusercontent.com/6250771/172041758-f2571562-aa28-4013-b220-adf862229ca2.png">

This doesn't include the table / action / multi-action table mocks, will likely post those independently to keep the discussion more focused, and @dennisreimann will be showing some of the progress on this front soon I believe. cc @pavlenex

**Comment by dstrukt** [comment]
Progress:

The "Time" filter needs to be addressed, we could even split into Start/End with the calendars, but this might be worth a discussion.

### Desktop
<img width="1196" alt="Screen Shot 2022-06-09 at 11 17 09 PM" src="https://user-images.githubusercontent.com/6250771/173003407-88f1f990-3fc5-4b0a-b185-f6e8591547b7.png">
### Mobile
<img width="450" alt="Screen Shot 2022-06-09 at 11 17 47 PM" src="https://user-images.githubusercontent.com/6250771/173003412-67894085-d586-45fa-b831-578d471f4173.png">

**Comment by petzsch** [comment]
It would be very cool to have a default filter in here to not show 0 sat invoices (Lightning Address testing by nostr clients). The topic was brought up on [Telegram](https://t.me/btcpayserver/57118) today.

Just from my perspective: I'm currently archiving all 0 sat invoices... a tedious job.
