### ISSUE TITLE
Add Point of sale data to the dashboard

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3675]
As of 1.5.0 we currently only have dashboard data for the crowdfunding. We should add it for the point of sale app as well.

It can be very similar to what we already have for the crowdfunding, displaying `total sales` and `best sellers` products in a pie chart.

![Screenshot 2022-04-25 at 15 02 14](https://user-images.githubusercontent.com/36959754/165094696-db450e02-657b-4468-b485-691ddd520c4a.png)

**Comment by dstrukt** [comment]
I agree about the `best sellers` being similar, but I think we may want to modify the way we present the contributions in the left card .. could be a bit more tailored than the bar chart (imo), but, will share a mock to see if you guys also agree.

Glad to see this is a focus in 1.6.0 though!

**Comment by dstrukt** [comment]
Pushing this further, still exploring ideas in the midst of a few others things, but thought I'd share progress. Updates to come:
<img width="687" alt="Screen Shot 2022-05-01 at 1 32 03 AM" src="https://user-images.githubusercontent.com/6250771/166138368-44d012ae-c618-42dd-9605-2fcd0d2f2f78.png">
<img width="413" alt="Screen Shot 2022-05-01 at 1 32 14 AM" src="https://user-images.githubusercontent.com/6250771/166138369-01bc6080-22b1-4ef8-987b-cd9de5b79834.png">
<img width="691" alt="Screen Shot 2022-05-01 at 1 31 37 AM" src="https://user-images.githubusercontent.com/6250771/166138367-812563a1-7a14-48ba-a748-997f56053119.png">

**Comment by NicolasDorier** [comment]
@dennisreimann the current approach of putting all the data in the dashboard isn't sustainable.
This will start failing and make the dashboard screen unusable and slow to load for users with lots of PoS or for users with lot's of invoices.

I suggest that instead of putting everything in the store's dashboard, this sort of data is put in a view relative to the specific PoS the person is using. At least this won't slowdown every requests to the much visited store's dashboard.

**Comment by dstrukt** [comment]
Glad you brought this up @NicolasDorier.

I figured we were going to eventually reach that point with plug-ins, etc.. but I didn't anticipate we'd have a problem with our current feature set.

There are some important usability trade-offs we might want to discuss by pushing that data (reports, general metrics) to the POS or other relative views.

w.r.t POS specifically, would it help if we reduced the time period to just the last week or month to potentially reduce the initial load, and maybe if they want to view `All` for example, if we keep it, it's a specific and intended action vs. a general initial load? or something along these lines..

Long-term we could address ways to potentially alleviate the current direction we're headed ... e.g. limiting the number of widgets that can be shown, default time period (as mentioned), etc..

I also ask, as the more technical constraints you guys share, the more I know where our hypothetical limits are, so we can all design around them!

**Comment by dennisreimann** [comment]
How about adding JSON endpoints for most of the tiles, so that we can display the dashboard fast initially and those data intensive tiles fetch  their data asynchronously?

We'd need something like this anyways for tiles where the user might change something, like the time period. We have this for the wallet balance already. 

I agree that the current approach isn't scalable, but I don't think that having a separate dashboard for the PoS data is a good option. The above seems to me like the best way forward regarding the performance.

**Comment by NicolasDorier** [comment]
Dashboards is a hard topic, in normal company you have teams dedicated only for that. If you want a dashboard that doesn't blow up in response time, it needs quite radical backend work. (For example, just showing the balance of NBX in acceptable time took me a month of work, it was taking 5-10s before, and even saw more than 1 min for some people)

Having separate tables to maintain the stats is the way to go, but then you have to solve other problems: How do you keep the data up to data? Triggers? materialized view refresh periodically? App side? Does the stats need to be accurate or approximate?

This is more than we can chew for now.

I also believe it is strange from UX point of view to put everything in a single page.
If there is too much information, the user isn't likely to find easily what he wants in it. (need to scroll down and scan all page looking for it rather than just clicking on a separate link)

I have an instance using apps quite heavily so I'll see how the current response time is affected and see if we can't go with what @dennisreimann already did. But next release we will need either heavy re-work on the backend, or splitting the data in several pages as this is not sustainable to continue that way.
