### ISSUE TITLE
[Greenfield API]: Graceful return for in-flight HTLCs

### ISSUE THREAD

**Issue by ghost** [btcpayserver/btcpayserver#3781]
When invoking the Pay Lightning Invoice from Internal Node endpoint (/api/v1/server/lightning/{cryptoCode}/invoices/pay) and the HTLC gets stuck mid-flight, the application times out and no invoice meta data is returned.

Without the invoice id being returned, it's not possible to check the status later to see if the payment settles or fails.

Likely also affects the Store Lightning Pay Invoice endpoint (/api/v1/stores/{storeId}/lightning/{cryptoCode}/invoices/pay) although I haven't tested it.

Edit: Happens on both CLN and LND.

Suggestions/Ideas:

- Always return a response with an invoice ID and a status when invoking this end-point
- Get invoice endpoint (/api/v1/server/lightning/{cryptoCode}/invoices/{id}) lookup by Bolt11 or invoice ID
- Parameter to set timeout
- New endpoint to Get All Invoices on the node to fetch the invoice id

**Comment by dennisreimann** [comment]
Which implementation (LND, Core Lightning) is the underlying node using? Was it a hold invoice you were trying to pay?

**Comment by barrydeen** [comment]
I have experienced this issue on both LND and CLN. 

All I know about the invoices that get stuck is they are valid bolt11 invoices. My application accepts bolt11 invoices from users and attempts to pay them. Occasionally (3% of the time) the HTLCs take 10-20 minutes to settle.

**Comment by nemanja-z** [comment]
I'm experiencing the same problem. The server returns, most of the time, status 504 with text Gateway Time-out.  Query(60) from peer x.x.x:8333 failed, rescheduling: did not get response before timeout keeps appearing in the log file.

**Comment by dennisreimann** [comment]
## Core Lightning

Unfortunately the [pay](https://lightning.readthedocs.io/lightning-pay.7.html) command (which we use) does not support these cases well: 

> The response will occur when the payment fails or succeeds.

ElementsProject/lightning#2629 does not address this directly, but it contains some more context for digging a bit deeper here.

There is also the lower-lever [sendpay](https://lightning.readthedocs.io/lightning-sendpay.7.html) command, but this is way more complex to implement, because it requires the client to resolve and try payment routes — as well as listening for the results using [waitsendpay](https://lightning.readthedocs.io/lightning-waitsendpay.7.html):

> The response will occur when the payment is on its way to the destination. The sendpay RPC command does not wait for definite success or definite failure of the payment. Instead, use the waitsendpay RPC command to poll or wait for definite success or definite failure.

## LND

We use the `POST /v1/channels/transactions` [endpoint](https://api.lightning.community/#v1-channels-transactions) with LND, which also works synchronously and does not offer a response, until a definite outcome is achived:

> SendPaymentSync is the synchronous non-streaming version of SendPayment.

As we are using the REST API, the HTTP Client has a timeout and fails after 100 seconds, but this isn't handled gracefully with a response our API clients can use.

There is the newer `routerrpc.SendPaymentV2` [endpoint](https://api.lightning.community/#v2-router-send):

> SendPaymentV2 attempts to route a payment described by the passed PaymentRequest to the final destination. The call returns a stream of payment updates.

I will give this a try and see if we can use it in a way that adds an immediate response for the HOLD invoice case. 

However, as this would only be a solution for LND, the best thing might be to handle those cases with an explicit timeout in our client and return the result of the `GetPayment` call, which supports in-flight payments.
