### ISSUE TITLE
[Bug]: You cannot login over an insecure connection. Please use HTTPS or Tor.

### ISSUE THREAD

**Issue by kieselbert** [btcpayserver/btcpayserver#3854]
### What is your BTCPay version?

I'm running BTCPay v1.5.2.0

### How did you deploy BTCPay Server?

Umbrel Node (Docker)

### What happened?

I used BTCPay without problems and the update of my Umbrel Node also updated BTCPay to v1.5.2.0. When I now try to loginI get the error "You cannot login over an insecure connection. Please use HTTPS or Tor.".
Access as follows:
(Sub)Domain-->HTTPS-->ReverseProxy (Treafik)-->HTTP-->BTCPay(on Umbrel = Docker)
The ReverseProxy is hostet in my location, traffic from internet to proxy is secure, traffic from proxy to BTCPay is unecrypted.

My setup is, as far as i know, secure and worked well before. Now after the update it will false declared as insecure.
How can I deactivate this "security detection" that keeps me away from the login form?

### How did you encounter this bug?

1. configure a reverse proxy setup internet>443>proxy>80>BTCPay
2. access BTCPay through this proxy 

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
Hey, I think you might need to pass through the relevant information through your proxey. For nginx it is that part in the config:

```nginx
proxy_set_header Host $http_host;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```	

Docs: [Can I use an existing Nginx server as a reverse proxy with SSL termination?](https://docs.btcpayserver.org/FAQ/Deployment/#can-i-use-an-existing-nginx-server-as-a-reverse-proxy-with-ssl-termination)

I don't know how this works for Traefik, but you need a t least the equivalent of the `X-Forwarded-Proto` setting.

**Comment by kieselbert** [comment]
Hm I found some settings for Traefik, but I am not sure if this will solve the issue.
For testing purposes I raised a "whoami" container that provides me some information about the headers. The configuration for BTCPay is equal, so this information also reaches the BTCPayserver.

X-Forwarded-For: 192.168.6.6 
X-Forwarded-Host: test.mydomain.de
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: 7db0f9c2ff8c
X-Real-Ip: 192.168.6.6

192.* <--its my client IP
For me it looks right in this way.

**Comment by SatoriHoshiAiko** [comment]
Hi there,

I have a very similar issue to OP here.

I see you are actively working on this. I checked documentation over here:

https://docs.btcpayserver.org/FAQ/Deployment/#can-i-use-an-existing-nginx-server-as-a-reverse-proxy-with-ssl-termination

And I have used all of the x-forwarded protocol in Nginx.

I have a slightly different setup that produces the same bug.

Where the Original Poster's Setup is:

internet>443>proxy>80>BTCPay

I have used

Internet>443>Nginx proxy>Socat .onion:80>BTCPay .Onion socket/Hidden Service/Nginx>BTCPay Localhost (Not Docker)

Where the First proxy is on a second separate server (in my case, to create a dedicated IP different from the original server for a DNS A record) and the second runs on localhost but *NOT* a docker image.

I have a very complex and detailed backend setup (Bitcoin, lnd, etc) for the BTCPayServer instance that does not afford me to use a docker image comfortably. I followed the Extended Manual Setup here:

[  ](https://docs.btcpayserver.org/Deployment/ManualDeploymentExtended/)

And The Reverse Proxy to Tor.

[  ](https://docs.btcpayserver.org/Deployment/ReverseProxyToTor/)


And I have also included the x_forward_ssl and x_proxy as suggest for Nginx configuration here:

https://github.com/btcpayserver/btcpayserver/issues/2322

On both hosts (the reverse proxy server, and the original localhost ".Onion" Nginx server running BTCPay (not docker)


It appears to me that having SSL, reverse proxy via Onion, and then localhost, it will produce this bug again.

I think the only difference between myself and OP with the the connection over :80 is also to an .Onion

And the documentation provided to solve the solution with:

BTCPAYGEN_EXCLUDE_FRAGMENTS="$BTCPAYGEN_EXCLUDE_FRAGMENTS;nginx-https"
. btcpay-setup.sh -i

Would likely work well also, but only exists on a docker instance of BTCPayServer, and I have used a localhost installation on a second server.

I will note that everything works beautifully otherwise. I can connect and not get this error is I connect via the Localhost on the instance server, I can connect via the .Onion address on the Nginx proxy/Hidden Service on top, and I can even go to my second server with the Socat proxying to tor, and this bug does not yet appear going to 127.0.0.1:9081

It's only when I go to the last point of entry via the domain name DNS and the Nginx Reverse Proxy (after SSL) that this bug appears. So both localhosts and the Onion address this works great.

I am going to assume that there being so many jumps, that it doesn't x forward nicely.

I would be happy with a fix that allows insecure connections, and being able to turn the flag off that does this error "Connect via Https or Tor", but it seems that only exists for a docker setup.

Apologize for the length here, I would appreciate if you could add this into the consideration for support.

~ SatoriHoshiAiko

**Comment by SatoriHoshiAiko** [comment]
Here I could note, that I am already using .onion routing as a point of trust, so that I no longer feel the need to depend on https for security.

This overall setup affords (unlike a docker container) a BTCPayServer with a Clear-Net DNS A record to an IP that is separated from the original location of the BTCPayServer. But It is noted that my whole Bitcoin-Core and Lightning stack is being hidden behind tor, for optimal security reasons.

The added security to a separate IP address for the DNS A record from the original location of the BTCPayServer is by design adding routing that tells Cloudflare or a DNS provider an IP that reroutes to and .Onion service of BTCPayServer.

Of course, with this error, I can't connect a WooCommerce plugin at the end point (Cloudflare running a Wordpress website) because I can't login from the Cloudflare destination, which is the real world or post-proxy use case of the BTCPayServer.

In general, with this bug resolved, this gives a really strong model for complete anonymity, where the DNS record is also pointing to a separate server from the original instance of BTCPay, and I believe that is what the OP was doing. The Nginx reverse proxy to Tor, it isolated the original server. But expanding this bug fix to more than just the docker installation, afford a more complex and detailed setup of the backend nodes (which in my case are *also* running in tor-isolation).

It's a thought anyway, that this has a very valuable model for privacy. Would be great to fix this bug. I am using a test model and being able to log-in at end point would allow the connection with WooCommerce. Hoping to display the model for repurposing.

Thank-you

**Comment by dennisreimann** [comment]
There's an open issue with Umbrel v0.5 which might be causing this: getumbrel/umbrel#1428

**Comment by pavlenex** [comment]
@SatoriHoshiAiko Are you still having problems with this?

**Comment by SatoriHoshiAiko** [comment]
I ended up working with BitcartCC. Spent two months one on one and we fixed this in their version. You are probably going to have issues well past this including CORS and http headers. The reverse proxy to tor on it works great.

I only mention because of the similarities of the two platforms in design.

We also implemented multiple deployments, load balancing, scalability, macOS compatibility, updating to newest docker releases, running docker as uid 1000 (not as root). After my time spent it looks like Monero support is on the way, as well as WalletConnect was implemented outside of my efforts. For others, not having to run a full node is helpful. But my biggest issue with BTCPay was actually the fact that the Tor privacy of my node were overwritten by symlinking my existing nodes, I was infuriated.

Nicholas Dorier's comment on Tor Project "We cannot guarantee privacy" is lazy. I take a lot of effort in to guaranteeing on that exact subject, and this really goes against cybersecurity and the reasons why we even practice this with scrutiny. You can, if you do things correctly and strip it down and assess it properly. Tor does do specific things effectively, mainly hiding IP address and location of the instance. It just needs to be used properly is all.

BTCPay is not an effective Reverse Proxy to Tor and would need a lot of cleanup for it to be effective in doing so. This specific problem is well, you will have CORS and http header problems local to BTCPay to get well past this issue, it reaches Tor Browser. Beyond that, it is probably not fit for the task by default.

I would have worked with BTCPay but three months later the comment on this ticket finally comes through, after I spent two months with the owner of Bitcart, he worked one on one (and does with lots of the community) within a day.

Thanks again, this is no longer needed.
