### ISSUE TITLE
[Bug]: 0 amount invoices crash the checkout UI

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#3904]
### What is your BTCPay version?

master

### How did you deploy BTCPay Server?

N/A

### What happened?

It seems that with some previous optimization where we no longer generate payment methods for 0 amount invoices, the UI/checkout of such invoice crashes. This attempts to fix it.

### How did you encounter this bug?

Create invoice with 0 amount, then go to checkout page

### Additional information

An attempted fix was at #3678 

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by rustywave** [comment]
This might be a race condition -- sometimes the $0 invoice is correctly listed as `Settled` and sometimes the `Checkout` option is available and gives a 404 when clicked. I always get `Settled` if I refresh the page. At the end of creating a new invoice, an event is published:

`_EventAggregator.Publish(new Events.InvoiceEvent(entity, InvoiceEvent.Created));`

Once published, we proceed back to the invoice list view. The InvoiceWatcher (`UpdateInvoice()`) processes the event at the same time, and I think that sometimes it marks the invoice as paid up before the list view appears and sometimes it doesn't finish until after.

Not sure what the best way to fix this would be...perhaps update the view if the InvoiceWatcher modifies the invoice even after it's loaded? Is that being done anywhere?

**Comment by bolatovumar** [comment]
> Once published, we proceed back to the invoice list view. 

This behavior was changed in https://github.com/btcpayserver/btcpayserver/pull/3936 which will be in the 1.6.0 release so the bug may not repro anymore (or it might, idk).

> At the end of creating a new invoice, an event is published:
> _EventAggregator.Publish(new Events.InvoiceEvent(entity, InvoiceEvent.Created));
> Once published, we proceed back to the invoice list view. The InvoiceWatcher (UpdateInvoice()) processes the event at the same time, and I think that sometimes it marks the invoice as paid up before the list view appears and sometimes it doesn't finish until after.

This description makes sense. Since invoice status is updated asynchronously you may land back on the page before the status has been updated.

> Not sure what the best way to fix this would be...perhaps update the view if the InvoiceWatcher modifies the invoice even after it's loaded? Is that being done anywhere?

I wonder if we can set the status synchronously to settled right there right away for 0 amount invoices so it's never in any other state. This feels maybe a bit hacky but we do other similar special things for 0 amount invoices already. Idk if this would actually fix the issue, I haven't tried it.

**Comment by rustywave** [comment]
@bolatovumar 

Just tested it with the update, issue is still there but different side effect now. I created six $0 invoices and one time came up as `New`...rest of the correctly marked as `Settled`. Was thinking the same about special case...not great but if we're already doing it then maybe.

![image](https://user-images.githubusercontent.com/100967048/177841780-8263a208-967e-47f9-9747-e313108b4de6.png)

**Comment by bolatovumar** [comment]
@rustywave I just tested the approaches I described above and they don't fix this issue. I'm out of ideas.

I don't even know why we allow these zero amount invoices for non-top-up invoices since they get marked as "Settled" right away anyway and if you try to go to the invoice page you will get a 404.

**Comment by rustywave** [comment]
@bolatovumar Oh okay, I just noticed that the custom $0 settlement happens all at once so that makes sense. Not sure either regarding allowing them, but I'm new. I thought I read somewhere it was for testing purposes? Does anyone know? If that's the case, perhaps we can prevent $0 invoices in production.

Another thought is SignalR, I noticed it's used in other parts of the application but this seems like way overkill.

**Comment by Kukks** [comment]
Guys, https://github.com/btcpayserver/btcpayserver/pull/3678 is the fix, but it needs to be cleaned up and made without spaghetti code

In the checkout, you need to check the following condition: `if (invoice.Status == InvoiceStatusLegacy.Complete && invoice.Price == 0 && !invoice.GetPaymentMethods().Any())` and if true, handle the UI in a way that it wouldn't crash without null values.

This is purely an aesthetic bug

**Comment by rustywave** [comment]
No problem, will leave you to it. But unless I'm misunderstanding I think the issue will still be there because with the 1.6.0 update, post-create now redirects to the detail view -- there is no more Checkout link. You will see `New` as status occasionally instead of `Settled` when the event hasn't processed in time (see image above). I think that check will not work because the status may not have changed to `.Complete` yet on page load?
