### ISSUE TITLE
[Bug]: Not my address in transaction and wrong balance after it

### ISSUE THREAD

**Issue by sadovyiov** [btcpayserver/btcpayserver#3933]
### What is your BTCPay version?

v1.5.4.0 

### How did you deploy BTCPay Server?

Docker

### What happened?

The server adds not my address and steals my money. For example:

This is a wrong transaction with not my address to receive: **3Qc4fq3XmMgEVKAnV2zuHLuWywztPsq4Td**
https://blockstream.info/tx/9b0cf67c86ae74d600546b958b5486b39f2013d5b86421ab4f7681667ddeaa6f

In dashboard
![CleanShot 2022-07-06 at 22 54 21@2x](https://user-images.githubusercontent.com/9282021/177632048-54d08012-06ab-4a2c-b35b-1132ae42a8bb.jpg)

Destination
`[{"destination":"35LbnJuwCkNF9i2edbuk67EnrHP3Zq579n","amount":"0.05278851","subtractFromAmount":true},{"destination":"bc1qv4xwntmwqpjxv7fphp07mfywmk084jqsnl5f9p","amount":"0.00081000","subtractFromAmount":false},{"destination":"3MQ4mRNEVA5DbEpeL3E2T9PJhT1FNNaurm","amount":"0.00009000","subtractFromAmount":false}]`

Answer from BTCPay server:
`{"transactionHash":"9b0cf67c86ae74d600546b958b5486b39f2013d5b86421ab4f7681667ddeaa6f","comment":"","labels":[],"amount":"-0.05368851","blockHash":null,"blockHeight":null,"confirmations":0,"timestamp":1657128639,"status":"Unconfirmed"}`

After this transaction balance in the wallet does not correct.

How I use it BTCPAY server:

I make 10-20... invoices. And people pay.
After some interval, I send money to some addresses. For example, 10 invoices money to one address, and 10 to another.
I know that all the money is in my wallet. I use it after 2 confirmations.
After the first transaction from 10 invoice addresses, I can not do the next transaction and have an error: 
`Got response (422): [{"path":"Destinations","message":"You are attempting to send more than is available"}]`

### How did you encounter this bug?

Combine 10-20 invoices and send them to 3 addresses from API with subtractFromAmount = true in one destination

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NicolasDorier** [comment]
The address 3Qc4fq3XmMgEVKAnV2zuHLuWywztPsq4Td is your address. It is called a change address. I don't see anything wrong here.

**Comment by sadovojav** [comment]
@NicolasDorier 
Wrong is balance. It does not correct in BTCPay after this transaction. And I can not send other money that I received before.
You can see in the screenshot, that I send -0.05368851 but it really is 0.06367586. it is not correct. 
For example, I received 4 invoices:
1. 0.1
2. 0.1
3. 0.1
4. 0.1

That I know about 0.4 BTC in my wallet.
I send amount (1 + 2) 0.1 + 0.1  = 0.2 And in the dashboard I can see this transaction with with amount, but realy send 0.20005 (for example)
And after this transaction, I can not send any other 0.2 because BTCPay server told me an error

**Comment by NicolasDorier** [comment]
```
And in the dashboard I can see this transaction with with amount, but realy send 0.20005 (for example)
```
This is the case because you need to pay fee for your transaction to confirm, in this case 0.20005.

**Comment by sadovojav** [comment]
@NicolasDorier 

Thanks a lot fot you replays 
I just want to understand why in the transaction appears the 4th address (which is seems like mine, with the status chang)

Could you pls answers for a few questions which are required clarification? :
1. What is the conditions/trigges which generates the 4th address and who generates this address with 0.01* (3Qc4fq3XmMgEVKAnV2zuHLuWywztPsq4Td)?

3. How can I manage this 4th address in a transaction (on/off). Would be great if you could share with me more information about this. 

4. Currently, I can't manage the 0.01* balance (it's like it's frozen, isn't it?)
I don't see these funds in the BTCPay server and wallet address (3Qc4fq3XmMgEVKAnV2zuHLuWywztPsq4Td) is absent in Vallet. 
Looking at Electrum.

My goal is to remove the dynamic creation of the 4th address. Because of it the balance in BTCPay server does not converge. 

P.S. I will describe a detailed example in my next post.

Thanks a lot for your support.

**Comment by NicolasDorier** [comment]
Sorry I can't hand hold you about how bitcoin works and what UTXOs are. Read https://programmingblockchain.gitbook.io/programmingblockchain/ to understand how bitcoin works.

1. BTCPayServer wallet generate this address. If we didn't those `0.01000109` would be sent as mining fee, which you obviously don't want.
2. A bitcoin wallet has a near infinity number of addresses, and you can't control this. Do not attempt to control this, as you will end up losing money.
3. You already spent the money sent to `3Qc4fq3XmMgEVKAnV2zuHLuWywztPsq4Td` in [3fce346c90f48e74fd275f844ed26315f5da184038b396e55f5435cef1a8e978](https://blockstream.info/tx/3fce346c90f48e74fd275f844ed26315f5da184038b396e55f5435cef1a8e978).

**Comment by sadovojav** [comment]
@NicolasDorier thank you for the link. I will learn it.
But I have last questions?
When BTCPay server create this address?
What is the condition to create it?

I want to send transaction without this additional address. Can you help me understand condition for this.
