### ISSUE TITLE
Feature Request: Admin users can view and modify other stores

### ISSUE THREAD

**Issue by ghtsto** [btcpayserver/btcpayserver#396]
I would like to have the ability for my admin account to see other stores as well as have permissions to modify their settings. 

The use case would be, as an admin, inviting friends/clients to build their own stores, I'd want to offer assistance in the setup and management of the stores.

Additionally, I think it is important to have visibility into the number of stores and apps that have been created on a server that I run.

**Comment by bitcoinshirt** [comment]
I think this can be dangerous to allow.
We already have a way for users to add admin manually as owners.
There are many third-party hosts , we can't push this issue, it would allow owner to easily replace xpub.

**Comment by NicolasDorier** [comment]
Malicious third party host can already do this.

**Comment by bitcoinshirt** [comment]
I understand, but should we make it easier to people to do it? 
I'm certain it brings more good than it does bad, but maybe we need to add a consent from already existing users for the first time it's added?

I just don't want for third-hosts to have out of the box way to do it, without user consent.

**Comment by Kukks** [comment]
I'm with @bitcoinshirt on this. I don't see why we should make this easier. At least with the current way you need at least some technical skill to get in. There are plenty of people simply running btcpay instances for merchants for free with no technical knowledge and this would enable the asshole minority to wreak havoc. 

Maybe we can come to a compromise on this though and have a toggle in store settings to allow server admins to be able to manage it too.

**Comment by Eskyee** [comment]
We have to secure more, I think and protect our users... not allow admin features to weaken our users privacy... I thought this was a BTCPay server strong point, Full Protection from any Malicious third party host. is our end goal.
This is Very Important... other wise what's the point! of Bitcoin ??

**Comment by Eskyee** [comment]
ps I want everybody to run their own BTCPay Server node...  ;) 
Third party host's are second choice for the end users... but privacy is very important here too.

**Comment by ghtsto** [comment]
> Full Protection from any Malicious third party host. is our end goal.

Wouldn't the solution to this be "run your own instance"? If I am providing the hardware, hosting, installation, maintenance of a btcpayserver instance, I'd argue that I should have full access to all aspects of what happens on my server.

I agree that privacy is very important and one of the pillars of this project was to allow people to get away from centralized providers but that shouldn't mean that an administrator doesn't have visibility into what's happening on _their own server_. Currently, if I give someone access to my server, they have the ability to create an unlimited number of stores and apps and I have absolutely no way of knowing if this is occurring, unless I'm directly monitoring the DB.

If the main concern is the ability to see/change xpub then hiding or locking changes of the xpub through the web interface could be an acceptable compromise but, as mentioned in an earlier reply, a malicious admin can easily manipulate the key if they desire. Preventing the admin access to other stores only limits the usability of the server and the admin account.

Finally, if it is determined that this request is unreasonable, at a minimum, a basic reporting option that outputs all user's stores and apps would be very helpful.

**Comment by bitcoinshirt** [comment]
We shouldn't make it easy for third parties. Nobody said third-party hosting is trust-less. 

Any sort of easy access to xpub and the ability to access someone else store out of the box is a big no from me. I just can't agree on that. Yes it can be done, but we should not make it easier to manipulate. If someone needs this for an internal system of stores, we already have store roles, you can set several store owner and the problem is solved.

> basic reporting option that outputs all user's stores and apps would be very helpful.
Could you be a bit more specific on what kind of data? There have been talks about reporting but not enough people were able to provide specifics.

**Comment by ghtsto** [comment]
If the main concern is for existing users then this change could be for the creation of new stores only.

I think the current behaviour may also be giving a false sense of security since there is no actual security against a malicious admin. If the change was implemented, it could be done in a way that users understand the risks of hosting their store on a third party (risks that are very real right now but not highlighted to users in any way).

Regarding a report, from my server admin account, I'd like to be able to go to the Stores or Apps tabs and see two sections: the list of stores/apps I have access (as it is now) and another section showing the stores/apps of other users (depending on this feature request, include or exclude the actions for these stores/apps).

**Comment by bitcoinshirt** [comment]
False sense of security and providing an out of the box way for third parties is not the same imo, but can be even more dangerous. 

I strongly disagree to giving an out of the box way for someone to hijack and replace xpub at this point.People already deployed their stores with these third-party hosts and to me this would be highly unethical thing to do from our end.

But I agree with you on a malicious admin, actually that's a fact. Actually I think we should propose a pop up warring to anyone registering as non-admin account, explaining potential advantages/disadvantages and attack vectors. But in theory if someone was malicious, he can fork BTCPay and remove that warring.

Don't think I don't understand your points or need here @ghtsto they are completely valid. We just have to find a compromise somewhere.

**Comment by NicolasDorier** [comment]
If you start hosting btcpay for the stores of friends, and you want to offer support when they are in trouble, it is quite useful to connect as if you were them.

Making it more easy to do does not seem to impact security.

**Comment by Eskyee** [comment]
I agree yes Nicolas , if its with a invite and their permission, I don't see that as a problem! 

> you want to offer support when they are in trouble, it is quite useful to connect as if you were them.

**Comment by sipsorcery** [comment]
At the very least the server owner should be able to easily see which stores are on their server. Maybe something like this:

![btcpay_stores](https://user-images.githubusercontent.com/197660/51086289-581d2c80-1745-11e9-8240-6db124858df6.png)

As for whether the server admin should be able to edit other store settings another option would be to add a new feature where the server owner can be paid a commission for hosting other people's stores. This would then act as a disincentive for the server admin to steal sales by changing the payment destination with the logic being that they can make more from ongoing commissions rather than stealing a handful of sales.

This type of model is likely to get used by small stores testing out BTCPay. Once their sales reach a point where the commission payments outweigh the time and effort of setting up their own BTCPay server they can switch.

**Comment by NicolasDorier** [comment]
Showing all stores is not scalable on the UX. Some instances run 300 stores.
For the commission, I got lot's of request about it, but we can't for several reason:

1. There is no protocol to pay several destination in one payment widely supported
2. If there was, it would be expensive because more UTXO

One way might be to ask for monthly payment or something like this, but recurring payments can be an orthonal feature not limited to pay BTCPay subscriptions.

**Comment by sipsorcery** [comment]
> Showing all stores is not scalable on the UX. Some instances run 300 stores.

Very easy to make it a paged list...

> For the commission, I got lot's of request about it, but we can't for several reason:

Ah of course. Didn't think about that too deeply. All that we need is a softfork for a new P2SH script that splits the UTXO between two parties. The first spender generates the normal recipient and change addresses and also automatically creates a 3rd UTXO for the second party with their percentage of the payment.

**Comment by xmijo** [comment]
I would love to see this feature implemented, together with other enhancements for 3rd-party processors. But especially this feature could be essential for those using BTCPay to provide crypto payment management service for merchants, as many merchants/people lack technical ability. More store settings may be added in future BTCPay versions and make it even more complicated to configure and cause a lot of confusion for the layman.

Just some ideas off the top of my head for some options to preserve privacy and security;
- Provide warning message to store owner showing admin abilities.
- Email sent to user if xpub was changed.
- Disable admin viewing/editing the xpub (and maybe store urls?).
- Store owner toggle to enable or disable the admin abilities.

**Comment by sipsorcery** [comment]
@xmijo it's more of a philosophical issue here rather than a technical one. If you need this sort of thing I'd recommend jumping onto the mattermost channel and attempting to get some support there.

**Comment by pavlenex** [comment]
Related #204

**Comment by pavlenex** [comment]
Circling back on this issue, my understanding is that our main use-case is that a server admin can:
- See the list of stores on their server (I thought we already allow this?)
- With permission (via notification maybe?) request or get requested to access the store in order to provide support? (with our hot-wallet feature I'd probably wait for #1697 as I am a bit scared of giving out of the box access to a hot wallet)

**Comment by Goro2030** [comment]
We definetivelly need this feature, as @pavlenex explained. I don't want stores created on my server that I'm not even aware of ... If some shaddy guy uses my server to collect payments from selling drugs, I don't want to be involved in that ... I wish we have a toggle to "disable non-admins from creating new stores" to lock this down , as an option @NicolasDorier

**Comment by Goro2030** [comment]
What someone asked for in this thread, and not to "break" the "confidentiality" of the stores, one can run a single line bash file like this to see the list of stores in the system:

`docker exec -ti $(docker ps -a -q -f "name=postgres_1") psql -U postgres -d btcpayservermainnet -c 'select "Name" from "Apps";'`

You can also run this to see the users list:

`docker exec -ti $(docker ps -a -q -f "name=postgres_1") psql -U postgres -d btcpayservermainnet -c 'select "Id", "Email" from "AspNetUsers";'
`

Whoever controls the FAQ documents, these 2 bash scrips could be added there @pavlenex

**Comment by pavlenex** [comment]
@Goro2030 I am still not sure I completely understand what is it that you guys would like to have.

My understanding is that a server admin should have a control on who can register on their instance, and not allow anyone to register and do whatever they want, I 100% agree with that.

What would be ideal solution for you as server admin? Having a list of all stores created on your server and being able to manually disable/enable them?

**Comment by pavlenex** [comment]
Going back to this issue, since it's been tagged on 1.13, I'll outline the scope and the intention, but the design side is still something pending @dstrukt's mock.

We discussed on one of the calls, that currently admin has no context on the stores that are being run on their server. This can lead to abuse on the side of the user, as users may abuse not only the payment processing side, but also public-facing pages (crowdfund, payment request, point of sale) to do activites server admin doesn't agree to.

Allowing more gradual control over admins to have better control over users on their instance is certainly our priority, but this issue has to be built step by step until we reach full satisfaction based on the feedback.

The first scope is to allow admin to view stores created by users and then all apps the user is using with their links, this is thus far view-only approach, but going forward we can disuss the ability for server admin to have view over-access overall.

What was first suggested is that in Server Settings > Users we list in an expandable by default way all stores user is using.

<img width="917" alt="Screenshot 2024-01-11 at 22 31 00" src="https://github.com/btcpayserver/btcpayserver/assets/36959754/698603f9-815a-4984-9249-99bdd9f374ef">

The expandable view can be re-used from the invoice view, with invoices you need to click an arrow to see information, but with users I feel like it should be expandable by default.


<img width="909" alt="Screenshot 2024-01-11 at 22 31 28" src="https://github.com/btcpayserver/btcpayserver/assets/36959754/aa945735-8ad8-461b-8d48-1e2228635866">

**Comment by TChukwuleta** [comment]
I started working on something for this PR. I created a new section to the server settings and called it "stores"

Was a bit confused as to what the modification would entail for the admin users. 

![image](https://github.com/btcpayserver/btcpayserver/assets/47084273/027f43f6-b891-426c-a45e-35b872b5cb02)

**Comment by pavlenex** [comment]
This issue is being closed, since it's quite old and the scope of it is not clearly defined.
The issue is broken down in favor of 
1. #5674  - allow admin to view stores and apps planned for 1.13
2. #5675 - allow admin to have reporting for stores on their servers - planned for 1.14.0
3. #5676 - allow admin to control user stores - planned for 1.15.0

I would invite everyone involved in this discussion to comment on their specifics they need in dedicated issues and @TChukwuleta you follow #5674 where once mockups are done, it could be tackled. I am really sorry for not having this issue properly scoped and wasting your time, hopefully this breakdown simplifies the scope and gets clarity on how you can tackle it once all blockers are cleared.

**Comment by TChukwuleta** [comment]
Noted. Thanks @pavlenex
