### ISSUE TITLE
[Design] Improve Store User role information

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#4111]
Originally posted by @pavlenex 

Currently it's not the most clear what the permissions are granted to Admin and Guest, and this could be clearer. Adding for tracking.

![image](https://user-images.githubusercontent.com/6250771/189499077-3794307b-f673-4f55-8114-c1c0eede287f.png)

**Comment by Kukks** [comment]
I think we can create a view similar to the create api key for each role so
that you can see what permissions are available.

This opens us up to creating a role creator/editor feature for specialized
roles in the future

**Comment by pavlenex** [comment]
I like that idea, we should just make sure permissions are clearly communicated even then, since these will most likely be used by a non-tech savvy admins giving access to someone more knowledgable (for example a store owner giving access to a dev who's integrating BTCPay, hence needs access to API, but should ideally not be able to see wallet, etc. I like the flexibility aspect of it, plus we can have some cool default roles like the one above mentioned (dev, cashier, etc)

**Comment by dstrukt** [comment]
Discussed on design call, going to mirror API Key functionality, and refine the UI on the PR, will not require any mocks in Figma to proceed.

**Comment by dennisreimann** [comment]
I think this can be closed and we should make the design efforts part of #4741.
