### ISSUE TITLE
Improve Currency Selector

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#4154]
Expected Experience:
- Dropdown should appear without having to delete text first

Current Experience:
![improve-payment-method-selector](https://user-images.githubusercontent.com/6250771/191889535-2ceafdc4-c7e8-4a30-8dcc-593c766012b7.gif)

**Comment by woutersamaey** [comment]
Just wanted to add that I have currency names on my radar. At present we cannot put something like "BTC - Bitcoin", because the currency names are not in the system, but for the custodians, we can have unlimited currencies or assets, and there will be names for those. 

Not a priority or so, but just making note of this that if you can make this fit, it'll make its way here eventually.

**Comment by dennisreimann** [comment]
@woutersamaey I've added the name in the PR I just posted. Good idea!
