### ISSUE TITLE
Cloudflare and ssl

### ISSUE THREAD

**Issue by darkban** [btcpayserver/btcpayserver#418]
Hi guys pls check the error whit cloudflare because i try point cnam ----> domain and a ---> ip but not work always error 503 nginx

**Comment by Kukks** [comment]
If you are using the docker setup, please close this and open an issue at https://github.com/btcpayserver/btcpayserver-docker/

That said, since you are using Cloudflare, you most likely would do well to just use the "no reverse proxy" option as Cloudflare also gives you ssl out of the box from what I remember.
