### ISSUE TITLE
[Bug]: Binance rate provider doesn't work

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#4194]
### What is your BTCPay version?

1.6.11.0

### How did you deploy BTCPay Server?

docker deployment

### What happened?

The `binance` rate provider doesn't work.

Seems to be fixed in next version of ExchangeSharp.

https://github.com/DigitalRuby/ExchangeSharp/issues/789

### How did you encounter this bug?

Set `binance` as rate provider.

### Relevant log output

```shell
Error while contacting exchange binance: No market symbol metadata returned or unable to find symbol metadata for AXSBIDR
```
```


### What browser do you use?

_No response_

### Additional information

_No response_

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
Narrowing down the problem: It seems like the binance.com API which is used in the ExchangeSharp lib does not return the `BTCUSD` pair, whereas e.g. binance.us does:

- https://api.binance.com/api/v3/ticker/24hr?symbol=BTCUSD
- https://api.binance.us/api/v3/ticker/24hr?symbol=BTCUSD

I tried replacing the base URL (`.us` instead of `.com`) and that works for us. So the issue in general seems more like binance.com removed that trading pair.

**Comment by dennisreimann** [comment]
@NicolasDorier I don't think there's anything beyond telling people to use another rate source then. Imho we can close this.
