### ISSUE TITLE
[Bug]: Generated address type changes without notice

### ISSUE THREAD

**Issue by afilini** [btcpayserver/btcpayserver#4286]
### What is your BTCPay version?

v1.6.12

### How did you deploy BTCPay Server?

Compiled manually with `./build.sh` and then started with `./run.sh`.

OS: Ubuntu 22.04 LTS

### What happened?

I'm looking at an instance with a few stores and some of them apparently changed the address type without any human intervention. They were initially configured to generate p2sh addresses and they are now generating p2wpkh addresses using the same key, which makes it a bit harder to recover funds because the xpub was generated for bip49 but it is now being embedded into bip84-style addresses.

The instance has recently been upgraded, but it looks like this switch happened before the upgrade and I only noticed it now.

### How did you encounter this bug?

-----

### Additional information

The only error I can see in the logs is:

```
Npgsql.PostgresException (0x80004005): 23505: duplicate key value violates unique constraint "PK_AddressInvoices"
```

Could this be the cause?

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NicolasDorier** [comment]
Given your report, it seems that you are running BTCPay outside of our docker deployment.

This error ` duplicate key value violates unique constraint "PK_AddressInvoices"` could happen if you wiped NBXplorer data after generating some addresses with it. Basically the new NBXplorer wouldn't remember the old addresses and think they are unused. 

BTCPayServer would then crash because it would try to affect the same address to different invoices. This error would disappear after a while, every time you see this error, NBXplorer would take a new address eventually getting back to the latest generated address from the old instance.

Now about the xpub changing. I don't see how this could happen. I never saw it happening. Maybe the user changed it by mistake?

**Comment by afilini** [comment]
A few months ago the instance was migrated to a different cloud provider, so this probably explains the database error.

As for the wallet changing: the xpub itself remains the same, it's just btcpay using it differently.  There are no plugins installed. It could be the users, but they are saying they didn't do anything and I don't think I can prove them wrong, there's no trace of those changes anywhere.

The keys are in cold storage, the users have their own wallets and only the xpub is imported into btcpay. I didn't do the import myself but if I understood correctly they imported `ypub`s so that btcpay would figure out the address type automatically. When I open the wallet page I only see the xpub though, so I'm guessing internally it re-converts to xpub and stores the address type separately.

**Comment by NicolasDorier** [comment]
@afilini do you need help for recovering the money of those users? I sadly can't understand what happened here, I don't see how it could happen without user mistake.

**Comment by afilini** [comment]
No that's not a problem, I got it covered.

I guess I'll just close this issue, thanks for taking a look!
