### ISSUE TITLE
POS new design

### ISSUE THREAD

**Issue by mariodian** [btcpayserver/btcpayserver#432]
Hi, I think POS should have a more POS-like design with an always visible "shopping cart" for easier manipulation on tablet devices. Which is where it shall mostly be used by physical vendors.

I'm using standard bootstrap elements (except for the sidebar "shopping cart" which is customized a bit) so it's easy to colorize with bootswatch themes. 

![](http://magicmockups.com/media/screen/guest/99/a63cb4fb965b40d985272d5ac124dd33_12_1600.jpg)

A first semi-working prototype is [here](http://btcpay-pos.freedomnode.com/).

- Let's brainstorm what the ideal POS should look like in terms of UI and UX. 
- Also the question is whether we want to have 2 separate apps (the current POS which could be renamed to something like "eshop" and the new POS), change the design of the current POS, or have a switch in the administration to switch between the eshop UI or the new POS UI.

Also can someone please check whether the sidebar works correctly on very old Android tablets? Thanks!

**Comment by bitcoinshirt** [comment]
## PoS
I agree with the concept. Looks nice and solves important UX problem for physical merchants.

> A first semi-working prototype is here.

The link does not work for me.

I agree with the idea that we split the eshop and PoS apps. Even though at one point there will be a dedicated iOS or Android App, I think we should offer this, mostly because in theory some users may not have a compatible device for the actual mobile app or simply someone may want to have it on a desktop.

## eShop

In order to have an eShop app, imo we need: 
* To allow billing/shipping address entry that will be added to invoices in BTCPay.
* To have TOS and privacy policies at the checkout (GDPR)
* Make product adding easier and intuitive 

For an e-shop we don't need anything too complex, whoever needs complexity can use WordPress, but this sort of app would allow merchants to run their store on hardware device, which is great use case.

I have a very old Android tablet somewhere and will test it out if you can fix that link.

**Comment by mariodian** [comment]
Sorry, wrong link. Try again please http://btcpay-pos.freedomnode.com/

**Comment by bitcoinshirt** [comment]
@darkban that's more like quick invoice 
@mariodian 
Okay, tested on HP 7, 4.1.2
- On default browser does not work at all. screenshoot
![oldbrowser](https://user-images.githubusercontent.com/36959754/49465294-8bdb6d00-f7fd-11e8-8b04-2811732a8c72.jpg)
- On Chrome 70.0.3538.110 it works, but the Pay button is cut off as well as btcpay logo. screenshoot
![chrome](https://user-images.githubusercontent.com/36959754/49465311-939b1180-f7fd-11e8-88dc-9bbedb4566a7.jpg)
After playing around here are my additional suggestions:
1. Instead of POS name maybe have a navigation header there with product categories? [Example 1 ](https://dribbble.com/shots/5477398-Yellow-Cab-Pizza-POS/attachments)and [Example 2](https://dribbble.com/shots/5499066-Point-of-Sale-for-Restaurant-Caffe) Maybe even quick invoice darkban suggested can be squeezed, though it appears he failed to communicate it properly, though I would not mind quick invoice being a separate app. I'm sure this would require some back-end changes for user to add the categories and items.
2. Play around with + and - right now it seems quite cumbersome to change quantities on a device I tested. The first example has a neat way of handling + and - in cart, where as the second handles it in a left side of the PoS which is again - an interesting concept.

**Comment by darkban** [comment]
yes but if one has different products? is inconvenient to look for a scrolling ... that pos is fine only if you have few products but who has many? you should enter a kind of calculator and a product tab with a search field to speed up the search

**Comment by bitcoinshirt** [comment]
> The sidebar should be scrollable vertically.
It's not that's the point. When going portrait to landscape in my environment it's stuck and scrolling does not work.

As for complexity, I have no answer for that one. The truth is people are working on a PoS  mobile app that should integrate with BTCPay from what I know, so perhaps that one should be used whoever needs a more robust solution. Perhaps @JimmyMow has some comments on how we should differentiate those two.

**Comment by mariodian** [comment]
@darkban 
> yes but if one has different products? is inconvenient to look for a scrolling 

That of course depends on the number of products. Scrolling through smaller number of products is much faster then typing in a search field.

@bitcoinshirt 
> When going portrait to landscape in my environment it's stuck and scrolling does not work.

That’s weird because the scrollbar isn’t anything fancy other than css’ `overflow-y: scroll`. Not sure if we should support too old devices if they can’t even handle basic css.

**Comment by bitcoinshirt** [comment]
@mariodian 
After some further testing, I was able to replicate the issue on iOS Safari.
1. In portrait mode, add all of the items from PoS or at least as many to fill the cart.
2. Click on the cart icon.
3. Full screen cart will be shown. 
4.  While still in portrait **you can't exit** the cart if you forgot an item.
5. Go landscape and now you can add items, cool.
6. In landscape button is stuck, so I'm trying to navigate downwards. Sometimes it works, sometimes it's just stuck and **moves the left sideba**r instead.
7. I try to move up again and the cart can't go up it's completely stuck. Cant see upper items.

Overall UX is a bit broken here. I don't know what is but there's certainly room for improvement there.

**Comment by NicolasDorier** [comment]
@mariodian I think you should have a search bar which filter in real time.

Like if the user type "tea" then only the items with "tea" in description should appear.

**Comment by junierkl** [comment]
it would be nice an option to print a receipt for the customer

**Comment by darkban** [comment]
my idea is 
- receipt print
- search bar products
- possibily add a logo custom
- add tab whit calculatr
- add button for discount in %
- history order
- download order in pdf or xls

and is food idea this graphic and structure
https://dribbble.com/shots/5477398-Yellow-Cab-Pizza-POS/attachments

**Comment by mariodian** [comment]
> receipt print
This would have to be facilitated by the backend somehow I guess, as javascript can't force an external device to print something AFAIK.

> search bar products
OK

> possibily add a logo custom
IF there will be a logo it will surely be customized

> add tab whit calculatr
Can you explain the reasoning? There's no custom price input in the cart so where/how would the calculator be used?

> add button for discount in %
Yup

> history order
What's the reasoning behind this? 

> download order in pdf or xls
I think data export should be done via the administration. There's no reason polluting the UI with such feature.

**Comment by mariodian** [comment]
New POS mockup with these features:

- add discount
- search
- +/- buttons to easily manage the cart on tablets/phones
- responsive version
- ability to add a standalone web app to the home screen on tablets and phones

**Comment by darkban** [comment]
fantastico per me funziona su android smartphone secondo me manca solo adesso due funzioni importanti cioè 

- generare una ricevuta di pagamento che può essere stampata a conferma del pagamento

- inserire una calcolatrice manuale in modo che possano scrivere direttamente  l'importo con tasto di sconto e una nota opzionale
fantastic for me it works on android smartphone in my opinion is missing only now two important functions that is

- generate a payment receipt that can be printed to confirm payment

- enter a manual calculator so that they can directly write the amount with a discount button and an optional note

**Comment by mariodian** [comment]
Printing a payment receipt will have to be done on backend. I can’t code C# so it would have to be done by someone else. Sorry can’t help you with that.

For the calculator I still don’t understand what are you trying to achieve? Because the field is of type “number” your OS will popup a numeric keyboard when you click the field. Calculator seems redundant to me in that case.

**Comment by mariodian** [comment]
Added a better and clearer animation when you add an item to the cart.

The same link http://btcpay-pos.freedomnode.com/index2.php

**Comment by Eskyee** [comment]
excellent work @mariodian

**Comment by NicolasDorier** [comment]
A button to empty the cart would be nice.
The old animation advantage was that we could see very well if we did double click by mistake,

**Comment by mariodian** [comment]
> A button to empty the cart would be nice.

I'll think about where to put it.

> The old animation advantage was that we could see very well if we did double click by mistake

My friend tested it thoroughly and said he couldn't always see it depending how he was scrolled. 

The new one is much clearer but I agree you have no way of knowing whether you clicked numerous times.

I could either temporary stop catching click events while the animation is on so you can't doubleclick or come up with something else but I don't know yet what it could be.

**Comment by darkban** [comment]
fantastic work mario... thanks for your contribution...

a numeric keyboard with a string that allows you to add the price manually ... this is because if you miss some product you can add a price with a personalized price in the cart

p.s. will it be possible to change the logo and colors after right?

**Comment by mariodian** [comment]
I added a custom price in the cart. You can now pay what you want. The question is if it should be always visible or only when the cart is empty.

The reasoning for the latter is that you either click products or you add a custom price. Not sure if there are scenarios when you need to do both at the same time?

Keyboard: your OS should pop out numeric keyboard so I’d stay away from implementing a custom one. Perhaps in the future but I don’t want to polute the UI too much.

Yes you can change the color theme and (likely) the logo too (I’ll have to look into it). Not the language. BTCPay doesn’t have this feauture implemented yet.

**Comment by darkban** [comment]
according to my opinion the manual string should always be visible also the discount and tip

another idea that came to me is to create the checkout process in modal mode that the user never leaves the page but generates the qr code directly with a popup. It happens the same fosa in the Invoice section and pressing on ^ when generating an invoice ... this to make everything more immediate and never leave the main page

**Comment by NicolasDorier** [comment]
@mariodian don't let me stop you on details, this is great enough, we can always adjust stuff later.

**Comment by astupidmoose** [comment]
Great work on the POS improvements! I'd love to push this to merchants locally. 

From a customer / merchant standpoint, the "Do you want to leave a tip" should possibly be asked after the merchant confirms the entire order and amount. Not sure if this is possible in the current app. 

Typically the server would not ask the customer if they want to give a tip, they would give the total amount and the customer can then choose to enter a tip. 

The merchant would also not want to hand over the entire POS system for a tip option if the customer does, as the customer could potentially delete items.

**Comment by mariodian** [comment]
@astupidmoose 

> From a customer / merchant standpoint, the "Do you want to leave a tip" should possibly be asked after the merchant confirms the entire order and amount. Not sure if this is possible in the current app.

I can change "buy" button to "confirm" and then a pop up window could show a summary and a tip field. Will play with it later.

@darkban 

> it would be great to request an optional email to send a final proof of payment to those customers where the receipt is a legal obligation

You can already set that a buyer has to provide an email address where he receives the invoice.

**Comment by britttttk** [comment]
@mariodian 

Sometimes it's kind of an issue to let any employee add discounts. Seems like store permissions is under discussion right now for BTCPay... But just in case, can discounts be enabled/disabled easily when they customize the store?

Thank you for your hard work, POS looks really great.  :)

**Comment by darkban** [comment]
very good work....

you can add also a button for teatures Full screen browser?

**Comment by darkban** [comment]
nice but according to me new confirm does not make any sense and slows down with one more useless step ... it's nice instead the immediacy of pos and do not add step do not you think?

**Comment by mariodian** [comment]
I'm not a merchant myself so I don't know what the best option is. 

According to @astupidmoose the confirmation (with an ability to tip) does make a sense:

> From a customer / merchant standpoint, the "Do you want to leave a tip" should possibly be asked after the merchant confirms the entire order and amount. Not sure if this is possible in the current app.

It would be nice to know which of the commenters here are merchants to avoid implementing meaningless features.

**Comment by CarlosRoldanx** [comment]
> @astupidmoose moved the tip to a new confirmation page.
> 
> http://prototypes.test/btcpay-pos/index3.php
> 
> @darkban
> 
> > you can add also a button for teatures Full screen browser?
> 
> On the mobile, it's always in a fullscreen mode when you save it to the home screen. On a desktop, you can just click the OS' "maximize button". Again, I don't want to pollute the UI with features that can be performed natively.
> 
> @britttttk
> 
> > But just in case, can discounts be enabled/disabled easily when they customize the store?
> 
> They could but only per app, not per user. But I'm not sure if that make sense in such case.

The link is broken

**Comment by darkban** [comment]
i mean the link correct is this

http://btcpay-pos.freedomnode.com/index3.php

**Comment by darkban** [comment]
@mariodian I think that if you have to enter the confirmation step then also discount features move in this area... 

I would also recommend adding a button that allows you to delete all products in the cart to avoid deleting one by one

**Comment by britttttk** [comment]
@mariodian yes @astupidmoose is correct. The merchant creates the order for the customer (adds items to cart) then typically the screen is given to the customer who is able to pay and choose the tip. It's not that the merchant can't know the tip, but the customer usually manually enters the tip for these reasons:

1. employee error or malicious employee who chooses a larger tip than customer agrees to.
2. customer disputes regarding tips are always in favor of the merchant because the customer has undoubtedly chosen the tip.
3. a tip is like an evaluation of service so it's kind of awkward and unnecessary to communicate the value you have placed on their service, directly to them. The tip is a type of non-verbal communication.
4. It's usually part of the confirmation page, like do you agree to pay this bill and do you want to leave a tip?

* The most common way to do tips is using buttons which add a percentage of the total bill to the final total (total += tip) 

In the US it's usually these buttons for service industry but merchants should be able to customize these values depending on the service: [15%] [18%] [20%] [XX%]

**Comment by mariodian** [comment]
@britttttk 

> The most common way to do tips is using buttons which add a percentage of the total bill to the final total (total += tip)

I don't wanna get rid of the "tipping" field because in Europe tipping is usually rounded to the nearest integer amount. eg 9.10 eur -> 10 eur. But I'll try to figure out the UI so it can also have a few buttons with percentage tips. Not sure if the buttons should be customizable by the vendor though. What are the 4-5 most common tips?

@darkban 

> I think that if you have to enter the confirmation step then also discount features move in this area

Discount is given by the staff not the customer. Confirmation should only show customer-related inputs (tip) so he can't change other values (see what @britttttk and @astupidmoose wrote).

> I would also recommend adding a button that allows you to delete all products in the cart to avoid deleting one by one

I'll think about it. Struggling to find a space for the button. Any suggestion?

**Comment by mariodian** [comment]
http://btcpay-pos.freedomnode.com/index3.php

- added empty cart button
- added tip buttons with percentage so Americans are able to tip :)))

**Comment by darkban** [comment]
- fix in my browser chrome the cart does not increase the number of objects

- the tip in% predefined is not in my opinion a good dirty feature too ... at most you can use a condition ... for example if I add "%" then insetendo the number the system understands that you are meaning the percentage and not the value fixed.

also because in all of Europe there is no such function so I would recommend to implement the tip but do not dirty it with buttons in percentages because for European users it could be a function not appreciated

**Comment by mariodian** [comment]
> fix in my browser chrome the cart does not increase the number of objects

Do you see any errors in the Chrome console?

>  for example if I add "%" then insetendo the number the system understands that you are meaning the percentage and not the value fixed

The input field is of type "number" (so it's easier to type on tablets) and can't contain anything other than numbers.

**Comment by darkban** [comment]
![pos](https://user-images.githubusercontent.com/32014414/49880832-3c182980-fe2d-11e8-8f56-23c982682574.PNG)

the tip example 10% 15% 25% according to me it is too dirty .... in fact, here in europe we do not use that function and it would be too confused and inutilizable... I think it would be enough to insert the amount number

**Comment by junierkl** [comment]
I like the tip percentage, here is US is very useful

**Comment by mariodian** [comment]
And do you see any error when you click the button? I can't seem to replicate the error.

> the tip example 10% 15% 25% according to me it is too dirty .... in fact, here in europe we do not use that function and it would be too confused and inutilizable... I think it would be enough to insert the amount number

The PoS is not made for EU-only vendors. It should be usable for most countries.

**Comment by darkban** [comment]
no any errors only not shotw in cart number
yes is correct not increment number in cart...
i understand that not only for eu but i tink that is better realize multy countries
and not to dirty the pos with extra default tabs ... but this is my opinion you decide how to make it better

**Comment by mariodian** [comment]
> no any errors only not shotw in cart number

Oh I see. Thanks! I'll fix it.

> and not to dirty the pos with extra default tabs ... but this is my opinion you decide how to make it better

I'll think about it. We can get rid of it later if needed.

**Comment by darkban** [comment]
perfect now works ...

I would also recommend:
- that if the cart is empty you can not press CONFIRM

**Comment by mariodian** [comment]
> that if the cart is empty you can not press CONFIRM button

I'll do it tomorrow

**Comment by darkban** [comment]
guys I was thinking about what to improve on the pos and I realized that missing the language of defaul that I think is essential
