### ISSUE TITLE
[Checkout V2] Add Copy Address support

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#4442]
- [ ] Show address(es)
A) Via Copy button
<img width="267" alt="Screen Shot 2022-12-21 at 12 00 32 AM" src="https://user-images.githubusercontent.com/6250771/208851846-53a15370-5e0c-476b-acd7-790470c30a1c.png">
B) Dumping the payment URL under the QR
<img width="408" alt="Screen Shot 2022-12-21 at 1 08 20 AM" src="https://user-images.githubusercontent.com/6250771/208865757-29292600-dab5-41c8-a1a4-a9c6a7749325.png">

- [ ] Shows addresses / relevant payment details as a modal on `Copy` button click for >1 
<img width="267" src="https://user-images.githubusercontent.com/886/208935952-85ef08a3-8236-4a76-8966-30551894fc5a.png">

**Comment by NicolasDorier** [comment]
I prefer B

**Comment by ndeet** [comment]
I prefer A, if A opens then a modal to show on-chain and bolt 11 and maybe also amount in separate to copy text fields. Reasoning is that those who want to copy and not use the QR do not need the unified url but want to copy specific on- or off-chain data and amount.

**Comment by dennisreimann** [comment]
We talked about this in the dev meeting and the copy popup/modal/drawer/whatever should show the individual items for explicitely copying:

- Amount
- Bitcoin address
- BOLT 11

So for the unified QR case, we'd have both addresses (Bitcoin + BOLT11) and the amount, otherwise just the one destination (e.g. Bitcoin address OR BOLT11) for the payment method.

The QR code will contain and copy the full payment URL, that will stay as it is.
