### ISSUE TITLE
Checkout experience where the user is asked about the altcoins before creating the invoice

### ISSUE THREAD

**Issue by rockstardev** [btcpayserver/btcpayserver#46]
Currently each invoice is created with all coins that merchant wants to support. We are considering alternative checkout experience where there is an additional step: The user choose what crypto he wants to use for payment.

**Comment by NicolasDorier** [comment]
For details: 
When creating an invoice, you need to exactly know what coins are supported in order to generate the addresses. So right now, when an invoice is created, an address of each crypto currency is created.
Crypto which are not used a lot then start having huge gaps of unused addresses.

The desired alternative is to add one more step in checkout. The customer is directed to a page asking him to select the currency in which he wants to pay the invoice. Then only this currency will be supported by this invoice.  This prevent getting huge address gap.

**Comment by rockstardev** [comment]
I like our ability to switch coins during invoice phase. Because it does give more freedom to the end user - he can change his mind on what coin to use whenever during the process - doesn't need to go back and initiate creation of new invoice.

So from UX perspective, it would make sense to keep what we have - but from technical perspective we would need to extend system a lot to support flow of:

- Invoice is presented to user - we display default coin and only address for that coin is generated and listened to
- User switches to coin S - now we generate extra S address, and start the listening process for that new address

Technically this would require refactoring large parts of system... and I don't think it's realistic at this point - so for now I will close this issue... we can revisit and reopen in future... especially when new API is done.

**Comment by rockstardev** [comment]
Related discussion on #22
