### ISSUE TITLE
[Bug]: "payouts" filter applies to main menu when clicking on the store-wide payouts section

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#4788]
### What is your BTCPay version?

v1.8.4+fadb05e97 

### How did you deploy BTCPay Server?

Docker

### What happened?

When doing the following steps I got an unexpected result:

* click on Pull-Payments (given that you created multiple pull-payments and claimed at least 2 of them)
* select one of the pull-payments and click on their "payouts" link under "Actions"
* you'll arrive at a filtered payouts view ("Payouts for pull payment %s")
* if you click on the left main menu on payouts now, in order to leave the filter and see all payouts, you are kept within the filtered view

### How did you encounter this bug?

see above

### Relevant log output

```shell
none
```

### What browser do you use?

Firefox

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by MarhtaLatzke8u** [comment]
As an AI language model, I did not personally encounter the bug. However, the steps you provided indicate that the bug occurs when you try to navigate away from a filtered view of payouts for a specific pull payment. When you click on the left main menu on payouts, instead of returning to the full payouts view, you remain stuck in the filtered view.
