### ISSUE TITLE
PoS Without Derivation Scheme

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver#483]
You can create a PoS App, with a store that doesn't have a derivation scheme, and when you create an invoice with the App it shows this error to the user. 

![image](https://user-images.githubusercontent.com/39231115/50577918-95052d00-0def-11e9-817e-a06b5a464a36.png)

**Comment by bitcoinshirt** [comment]
There's nothing we can do besides not allowing the users to create app when no store and derivation scheme is added, but that's also weird UX.

It's not just the PoS, the upcoming #313 also has this problem. 
I think the actual problem here is improving the error messages #275 
If the error messages were better users would know what to do.

**Comment by Kukks** [comment]
I think it's fair to allow it but maybe display a big red sticky warning while editing the POS or viewing it that you can't create invoices.

**Comment by britttttk** [comment]
Closing this because the error message is now very clear for both PoS and CF in this situation. 

{"error":"Warning: No wallet has been linked to your BTCPay Store. See the following link for more information on how to connect your store and wallet. (https://docs.btcpayserver.org/btcpay-basics/gettingstarted#connecting-btcpay-store-to-your-wallet)\r\n2/4/2019 8:53:50 AM: Creation of invoice starting\r\n"}
