### ISSUE TITLE
Add support for ethereum

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#50]
Considering Ethereum is the second largest coin in terms of market cap, it makes sense to integrate. 
You have an amazing project going!

**Comment by NicolasDorier** [comment]
Ethereum as a too different design and consume too much resources for owning a full node. It is unlikely BTCPay ever support it.

**Comment by Kukks** [comment]
If you could guide us a bit through the current architecture, I would be
willing to give it a shot. :)

**Comment by lepipele** [comment]
@Kukks here is the video @NicolasDorier made when he was adding Litecoin as template for altcoin support: https://www.youtube.com/watch?v=liOUTqBUi_g

**Comment by Kukks** [comment]
I am guessing I would need to abstract away the nbxplorer layer since the api calls and system is different @lepipele Any thoughts?

**Comment by NicolasDorier** [comment]
@Kukks Yes you can try, I think it is a large undertaking though.

**Comment by NicolasDorier** [comment]
Just keep in mind that it is important the people host their own node and do not rely on a public API.

**Comment by NicolasDorier** [comment]
I am making some refactoring to make it easier to add none bitcoin related currencies right now. It might be easier for you to add then.

**Comment by Kukks** [comment]
That sounds great. Let me know if you need anything from my side to help.
ᐧ

**Comment by NicolasDorier** [comment]
@Kukks so that sounds messy will need probably better refactoring.
I managed to isolate bitcoin related logic in https://github.com/btcpayserver/btcpayserver/blob/5de330b1f9d3249069c843bf563f28aac7ae7c1a/BTCPayServer/HostedServices/NBXplorerListener.cs

This class basically connect to my block explorer via websocket and add payments to invoices. It also notify the InvoiceWatcher when the state machine should run.

A ethereum support would so something similar. (In way simpler though as there is no concept of RBF)

**Comment by NicolasDorier** [comment]
Ok so I worked well to make BTCPay more welcoming for non bitcoin fork.

Question: 

* How to map an incoming payment to an invoice in ethereum? (In bitcoin we use addresses)
* Does it exist a decent public block explorer so I do not require merchant to have their own eth node.

The point 2 is because I don't want to provide support when the merchants node eat all resources of their machine. (And also because I care less about decentralisation of ethereum versus bitcoin)

**Comment by NicolasDorier** [comment]
Thing is that for creating an address on eth, you need first to create a contract right? You don't change address for each payment right ?

**Comment by NicolasDorier** [comment]
@Kukks so the basic idea is that you will have a class like the `NBXplorerListener` which add payments to the invoice.

**Comment by Kukks** [comment]
@NicolasDorier  No, contracts are a separate thing. You can ignore them and just use "accounts" as the alternative of addresses in ethereum. Here is an example of an HD Wallet in C# for Ethereum. :)
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.HDWallet/Wallet.cs

**Comment by NicolasDorier** [comment]
I did against quite substantial refactoring today to introduce the concept of `PaymentMethod` (before, it was called `CryptoData`).

I did my best to hide the legacy stuff. I think the code should be easier to understand now.

**Comment by lepipele** [comment]
@Kukks any update on this?

**Comment by Kukks** [comment]
Not yet @lepipele 
I need to do some work on NBitcoin first on a separate issue and then I will move on to this.

**Comment by lepipele** [comment]
OK @Kukks - looking forward to your contribution!

**Comment by Kukks** [comment]
Sorry for the delay, I will hopefully be getting some time to look at this in May.

**Comment by Kukks** [comment]
Starting at it now, will be tasckling this primarily through a third party api and then handle full node support after. Do you have some pointers I should follow @NicolasDorier ? I am looking at the Payments folder and thinking I should copy pasta all the Bitcoin specific implementation stuff under an Ethereum namespace

**Comment by NicolasDorier** [comment]
Take example in the Payments/Bitcoin or Payments/Lightning.

**Comment by NicolasDorier** [comment]
yes

**Comment by NicolasDorier** [comment]
Encapsulate the explorer dependency in an interface. You can inject such interface in `AddPayServer` using AddTrySingleton. 

Then in tests, in the `BTCPayServerTester` class, you can inject a mock inside `ConfigureServices`, so at least we can unit test it. (not perfect, but we have no choice because no way to have the explorer working on regtest)

**Comment by Kukks** [comment]
Nope, feel free to donate a pr or sponsor me to prioritize it though :)

**Comment by giltotherescue** [comment]
@Kukks I'm interested in sponsoring the development. Please contact me at myfirstname at gilded.finance.

**Comment by gdipri01** [comment]
@giltotherescue would love to see this done with ERC20 support in mind. Let me know if there's anything Maker can do to assist.

**Comment by Kukks** [comment]
no money, no party 
https://btcpay.kukks.org/apps/3eFThAEycrZopgT5HeAMzZMFVWCa/crowdfund

**Comment by jooray** [comment]
Hi @Kukks, what is the reason that this task is closed? Maker offered help (I guess also sponsorship), I don't see it has been done. The crowdfunding link does not work, but if your crowdfunding campaign did not raise enough funds, it does not mean that this issue is fixed, maybe someone else could continue the work and implement this, so I would very much like this to be kept open.

Also, what is the current status, have you done something? I might be willing to take a look at it, if I understand this better.

**Comment by Kukks** [comment]
Nothing has been done and the task requires big refactoring efforts in the codebase. I was willing to do it for a number of reasons:
* I rely 100% of donations and btcpay related work currently( actually I rely mostly on my savings right now since I get next to nothing in either)
* It would allow btcpay to be used by quite a few more merchants from the eth scene( who would most likely use bitcoin in the future as a result)
* Some people promised funding if I did this ( I think around 3-5 committed to 1BTC each for sponsorship)

So, in January I created the crowdfund, contacted these people that committed to funding me earlier, and was greeted to the world of shit. A tweet promoting the crowdfund was twisted by some questionable actors and turned it into a FUD anti-btcpay campaign. Only 1 of the committed people came forward and put their money where their mouth was while the others either came up with excuses or ignored me. I left the crowdfund running for 2 months after that moment just to give others a chance and it ended a few days ago when I refunded the funds.

I have no interest in doing ethereum integration for free and there is no work to pass on as it was mostly research and findings. 

Regarding the closed issue, we've taken a stance in order to avoid issue spam on here to close off altcoin requests unless they have a pull request with work.

**Comment by jooray** [comment]
Hi, thank you for clarifying. I understand your reasons now. The reasons I asked for keeping this open is that it might be a good place to discuss, possibly crowdfund and move forward.

Technically I think it is important mainly for tokens, it is quite rare for merchants to accepts ETH as payment itself, but tokens (especially stablecoins like [MakerDAO / DAI](https://github.com/makerdao/) ) are a good potential customer. The holders of DAI would benefit from this a lot (and many other projects too).

MakerDAO has a foundation that finances such projects. They have a process and I don't think they would just participate in the crowdfunding, but if you send them proposal, they well may finance it.

If you don't have time for that, I could try to do that, but I need to know what kind of funding would be required on your part. The crowdfunding website is down.

**Comment by Kukks** [comment]
Yeah, feel free to reach out to them or me on https://chat.btcpayserver.org

**Comment by gdipri01** [comment]
Hi Andrew,

While I know our initial offer was only for Dai integration (as the broader
ethereum integration seemed to be covered), we may be able to contract you
to complete the entire process. If you're interested, please reach out to
rich@makerdao.com and go through our grant application process (feel free
to Cc me/say I sent you there for necessary context).

Best,
Greg

**Comment by aaronmboyd** [comment]
I'm developing a commercial product with BTCPayServer for BTC, LTC, and currently handling Ethereum myself manually with web3 / Metamask. 

Obviously would be great to have everything in the one place on BTCPayServer. I'm actually trying to modify my Ethereum payment modal to look like BTCPayServer invoice for feature/UI parity in my application.

Please keep this ticket open and update if there is a new crowdfunding campaign.

**Comment by xpayserver** [comment]
https://github.com/btcpayserver/btcpayserver/pull/1730
