### ISSUE TITLE
[Enchancement]: Continue scanning for NFC after payment to prevent accidental redirects out of the checkout

### ISSUE THREAD

**Issue by rockstardev** [btcpayserver/btcpayserver#5507]
When paying at checkout with NFC card, customers need to remove it before payment is processed. If they do not remove the card fast enough they will be redirected out of checkout page, Android's default NFC scanning functionality will take over.

Video illustration:

https://drive.google.com/file/d/1cpOVV9H54npy4BjK4sZP49ZL0jNinM7M/view?usp=sharing

**Comment by dennisreimann** [comment]
I have that on my TODO, thanks that you opened the issue for tracking.

It's a bit tricky, because right now we have the NFC code only on the Lightning payment partial/component, which is only active during the payment, not after. It would need to get pulled up into the Vue app-level to handle the result states as well. 

Is this one urgent for the conf?
