### ISSUE TITLE
`btn-primary `/save  button consistency update

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5581]
`Save` is pretty common button in our UI, it's used to erm - save your progress! However, we're not really consistent in how `Save` button appears in our UI, sometime it's sticky on top, sometimes it's just on the top, and sometimes it's at the bottom. 

![Screenshot 2023-12-21 at 14 09 04](https://github.com/btcpayserver/btcpayserver/assets/36959754/768d1434-79eb-49dc-ada1-75a09963ed04)

![Screenshot 2023-12-21 at 14 09 04](https://github.com/btcpayserver/btcpayserver/assets/36959754/49fe3a7a-37fb-476f-bf1b-00a9b178dfae)
![Screenshot 2023-12-21 at 14 11 29](https://github.com/btcpayserver/btcpayserver/assets/36959754/81f328c5-6cee-4326-b687-755cba5d47d1)
![Screenshot 2023-12-21 at 14 11 35](https://github.com/btcpayserver/btcpayserver/assets/36959754/5ad0f193-92f9-4bae-a359-e4d9d20c620d)
![Screenshot 2023-12-21 at 14 11 51](https://github.com/btcpayserver/btcpayserver/assets/36959754/d5a96a66-d27f-4e5a-a759-7c4d96d46606)
![Screenshot 2023-12-21 at 14 12 14](https://github.com/btcpayserver/btcpayserver/assets/36959754/f5c6e750-d9ad-4260-94d5-dab9f3d17ffb)
![Screenshot 2023-12-21 at 14 12 42](https://github.com/btcpayserver/btcpayserver/assets/36959754/163961bf-5982-480f-aaf5-737cd137044c)

Since progress can't be saved unless user clicks save, I propose we make it consistent and sticky on top, but leaving this discussion up to @dstrukt and @dennisreimann to find consensus, and hopefully we'll end up uniting things.

**Comment by pavlenex** [comment]
@dennisreimann pointed out that this is more of a `primary call to action` discussion so it should go in that direction how do we ensure `btn-primary ` is consistent and visible as a primary call to action

**Comment by dstrukt** [comment]
Agree this is definitely something to resolve the consistency, ties heavily into the consolidation and refinement of all the various Settings screens we've accumulated over the years.

I still think this inconsistency ties into this exploration: https://github.com/btcpayserver/btcpayserver/issues/3827

e.g. we can push the main CTAs to the top right and fix them with the breadcrumbs on the top left, and the sub-nav elements shown on the left sidebar, only when relevant (e.g. I'm in the Server Settings, so I see that expanded, otherwise it's collapsed).

But this does need a little more thought overall on both Issues, so will set aside some time this Christmas!
