### ISSUE TITLE
[Bug]: WebNFC Not Supported on Samsung Internet

### ISSUE THREAD

**Issue by leesalminen** [btcpayserver/btcpayserver#5861]
### What is your BTCPay version?

v1.13.0
1fe766cb16fdff35e1e29952a0bd1996fdf36960

### How did you deploy BTCPay Server?

Manual

### What happened?

When attempting to pay an invoice using Checkout V2 using Samsung Internet browser, the "Pay By NFC" option is shown to the user. This leads them to believe that they can use WebNFC, however Samsung Internet does not support WebNFC at all.

### How did you encounter this bug?

- Create an Invoice
- Attempt to pay invoice with Checkout V2 enabled
- Click Pay By NFC button
- Tap NFC card to device
- Nothing happens

### What browser do you use?

- Samsung A54 5G (SM-A546E/DS)
- Android 14
- One UI 6.0
- Samsung Internet v23.0.1.1

### Additional information

https://caniuse.com/webnfc indicates that WebNFC is not supported in any version of Samsung Internet.

I think the Pay by NFC button should be hidden from users of Samsung Internet, similar to how it is handled on iOS devices.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
The problem here is, that the browser properly signals support: Both checks `'NDEFReader' in window` and `navigator.permissions.query({ name: 'nfc' }))` indicate support and maybe that's also why [MDN reports WebNFC as working in Samsung Internet](https://developer.mozilla.org/en-US/docs/Web/API/Web_NFC_API#browser_compatibility).

Yet it doesn't prompt the user for permission and I couldn't find a setting that would enable it. With the current state it's difficult to fix and ensure it doesn't break elsewhere, so I'd wait for this to get fixed upstream in the browser.
