### ISSUE TITLE
Adding Tether as BTCPay Server Foundation supporter

### ISSUE THREAD

**Issue by rockstardev** [btcpayserver/btcpayserver#5889]
Here is the necessary information:

- Name: Tether
- Link: https://tether.to
- SVG: ![tether](https://github.com/btcpayserver/btcpayserver/assets/5191402/95f8f38b-5c1f-4c23-b49e-766742750e2e)

**Comment by rockstardev** [comment]
OK, I think I got everything covered with these changes. I will check tomorrow on dev call with @dennisreimann and @pavlenex.

Questions:
- Do we even need assets/tether.svg considering SVG itself is embedded as symbol? (https://github.com/btcpayserver/foundation.btcpayserver.org/pull/32)
- How do we have dynamic theme (dark/light) changing SVGs on READMEs the way we have them on https://foundation.btcpayserver.org ?
  - https://github.com/btcpayserver/btcpayserver
  - https://github.com/btcpayserver/btcpayserver-doc

**Comment by dennisreimann** [comment]
> Do we even need assets/tether.svg considering SVG itself is embedded as symbol?

Practically not. I think the reason those duplicate SVGs exist is due to the fact that we wanted to have them somewhere, but now they should be managed via the design repo: https://design.btcpayserver.org/resources/supporters/

> How do we have dynamic theme (dark/light) changing SVGs on READMEs the way we have them on https://foundation.btcpayserver.org/ ?

No, we cannot do that for the READMEs, that's why these SVGs are extra and also share a common format. In cases where the foreground logo doesn't work on both themes, we simply apply a background to the README SVG.
