### ISSUE TITLE
Branding: Change File IDs to full URL

### ISSUE THREAD

**Issue by dennisreimann** [btcpayserver/btcpayserver#5953]
For the branding properties, which refer to files (e.g. logo and CSS), we save the file ID and generate the URL when needed. Examples:

- Set: https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Controllers/UIStoresController.Settings.cs#L99
- Get: https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Views/Shared/LayoutHeadStoreBranding.cshtml#L5

This makes it incompatible with the API, because the API does not offer file upload and setters for the file IDs.

The most practical way to fix this would be to switch from saving the file IDs to the full URL. This way the URLs could be read and set via the API without the need to also provide file upload via the API.

**Comment by ndeet** [comment]
Sounds great! 

For internal files you might want to store the absolute path to the file and not the full URL with domain. E.g. I have a BTCPay instance with multiple domains mapped. I mean it would not be any problem if you use the full URL as long as that domain stays mapped. Problem will arise if you switch to another domain then the old asset links might break, this a big pain point with wordpress for example. So if possible, for internal URLs I would store the absolute path (/files/public/path/file-something-logo.png) because it will be domain agnostic.

**Comment by Kukks** [comment]
how about we introduce format resolvers like "filed:xyz" or otherwise "https://xyz.com/image.png" or  "base64..."
