### ISSUE TITLE
When an invoice expires, the corresponding Shopify order remains pending instead of canceling.

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#6021]
> When an invoice expires, the corresponding Shopify order remains pending instead of canceling.

This has been reported by a user, but we need to try to replicate it and if we manage to replicate it, then we need to address it for 1.13.x as it's tricky UX issue that can potentially mess up the fulfilment for certain type of merchants.

Deployment method: Voltage

**Comment by pavlenex** [comment]
It's actually a pretty meaningful issue: the quantity of the items ordered remains committed indefnintately. Timeline for resolving it sounds reasonable.

**Comment by ndeet** [comment]
Can confirm that the expired status does not get updated on shopify. First order I did pay and the second is expired:

![screenshot-admin shopify com-2024 05 31-10_42_02](https://github.com/btcpayserver/btcpayserver/assets/1136761/c2db911a-bf81-4e42-83db-ba7c39828ea8)

**Comment by Kukks** [comment]
But this is expected behavior? It's not usual for the payment method to effect the order itself, and rather the e-commerce platform times it out on its own. Iirc this is also the same behavior on other integrations too. Maybe @ndeet can confirm?

**Comment by pavlenex** [comment]
So, once expired, the invoice should end up being canceled, right now, it's pending (aka our processing), which causes inventory to get stuck infinitely for the merchant.

**Comment by pavlenex** [comment]
Expired > Canceled or whatever is equivalent on shopify
Processing > Payment pending
Settled > Complete


Right now it seems that
Expired triggers > processing / payment pending

**Comment by seedor-io** [comment]
Let me preface I've been super happy with BTCPay on Shopify for over a long time now, but here are my takeaways:

I've purposely set the invoice expiration time to 6000 minutes (100 hours) since we receive 50% of the Bitcoin payments on-chain and we've had quite a few moments where transactions did not confirm for a few days, especially if shoppers were stingy on sats/vB.

Before setting the expiration time this high, we had cases where customers paid the address at a later time and BTCPay Server not registering or somehow no longer monitoring the address and not marking it as paid in Shopify or paying the order cost manually via keysend to our public node URI 🙈

On the other hand I've had shoppers receive the order confirmation from Shopify before they had paid the invoice leading some customers to maybe believe they exploited the system and would get their stuff for free (spoiler: they didn't since it was never marked as paid in Shopify, just the email prompt was triggered too early)

Lastly customers try and pay in Lightning and run in the usual problems of not finding a route, not having enough outbound liquidity, etc and then abandoning the shopping cart. These orders could be marked as "payment declined" after invoice expiration (as I've been doing manually so far, after a couple days in case the customer returns) 
For now given that we still have "only" single digit customers per day that pay in BTC it's manageable manually, but would love to see this automated after the "invoice expiration" timer runs out.

![Screenshot_20240602-200918.png](https://github.com/btcpayserver/btcpayserver/assets/122058767/d0e0be72-a130-439e-ba2e-80a8f1b2745d)

**Comment by ndeet** [comment]
@Kukks for keeping it pending, it depends on WooCommerce the order gets set to cancelled by the WooCommerce after some time but we also do it explicitly when the payment expires (it is also configurable if merchants don't want that).

Tested yesterday with v1.13.2 branch (and local docker image) and today with the 1.13.2-rc2 docker image. The payment status stays as pending for me, see screenshot.

![screenshot-admin shopify com-2024 06 04-08_17_40](https://github.com/btcpayserver/btcpayserver/assets/1136761/d94ee881-6327-4554-ba00-d7f782a847ca)

**Comment by pavlenex** [comment]
cc @NicolasDorier @Kukks should we re-open the issue then?

**Comment by ndeet** [comment]
Hey @2urkivip, this has been fixed with BTCPay Server v1.13.2, the pending orders will now get invalid and items will go back to stock.
