### ISSUE TITLE
Point of Sale app - Cart Button and pop-up window size, invoice generation indicator

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#606]
After [watching this video](https://twitter.com/turm_im/status/1098735185481383937) I see we can make a few UX improvements in the PoS app.

- [x] Cart button size should be increased
- [x] Increase the size of pop-up confirmation windows, it's too small and fields are hard to navigate and click
- [x] When pay button is clicked, it should give some sort of indicator that the invoice is being generated

**Comment by bolatovumar** [comment]
@pavlenex I also have some suggestions and nits to consider:

- [ ] Increase the default step amount for tip percentage to 1 instead of 0.01 (see screenshot below). You are unlikely to want to increase the tip in 0.01% amounts
- [ ] Ensure tip amount always shows up in cent amount (see screenshot below where it shows up as 0.7560000000000000001)
- [ ] Ensure selected tip amount is prominently displayed as selected (see screenshot below). Right now it has a background color on hover but when selected it only has a border. It should have a background color when selected and not just on hover
![tip](https://user-images.githubusercontent.com/1934678/63585486-e6914080-c5a7-11e9-8209-4269c44af8f2.png)
- [ ] Don't show cart in opened state on desktop (same as on mobile)
- [ ] Don't show anything in the cart when it's empty. Show a message like "Your shopping cart is empty." instead
- [ ] Center align amount input vertically. Right now it's shifted to the top
![input alignment](https://user-images.githubusercontent.com/1934678/63585462-d8432480-c5a7-11e9-9b7b-171c7b8d7af0.png)
- [ ] Left align the search bar with products below it. Right now it's floating out of alignment
- [ ] Apply consistent border radius to the search bar. Right now it's rounded on the left but not on the right for some reason
![search bar](https://user-images.githubusercontent.com/1934678/63585457-d4170700-c5a7-11e9-864d-dfc2738e9a6c.png)
- [ ] Consider increasing the search bar size to extend all the way to the cart button. Right now it's not obvious why it's taking up a little bit more than half the space available and it's just sort of floating there

**Comment by bolatovumar** [comment]
@pavlenex I've address the three items you mentioned in the above three commits. I can continue with implementing the suggestions I listed above if deemed appropriate.

**Comment by pavlenex** [comment]
@bolatovumar Thanks, feel free to tackle the remaining ones, nicely spotted.

**Comment by NicolasDorier** [comment]
should update the checkboxes

**Comment by bolatovumar** [comment]
@NicolasDorier you mean the checkboxes by the tasks I wrote out above? I haven't completed all the tasks yet (haven't had time) hence why not all of them are checked.

**Comment by bolatovumar** [comment]
> should update the checkboxes

ok, I updated the checkboxes and tackled the remaining issue in the above PR.
