### ISSUE TITLE
Improve the scannability of QR codes in BOLT11 invoices

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#609]
Several users reported that lately BOLT11 invoices take a while to be scanned.
It was proposed by @Kukks that we reduce the size of the icons in the middle or remove them entirely:

> They have too much data on them . We should remove the circle on them so it has around an extra 10% success rate

**Comment by skddc** [comment]
I'm not sure why it would be getting worse, but I'm almost completely unable to get it to recognize a QR code now. I also tried scanning the same invoice codes with QRDroid and it would find random different short strings of numbers instead of the payment request most of the time.

**Comment by skddc** [comment]
I just tried removing the bitcoin logo that is overlayed and even that didn't improve scanability. :/

**Comment by skddc** [comment]
OK, found the issue. I'm using a higher-res display and the image resolution is simply too low, so the sharpness decreases to a degree that makes it impossible to scan from my phone (a current flagship Android phone with excellent camera I should add).

I'll open a pull request that doubles the resolution while keeping the rendered size, so that people with higher-resolution displays are also able to consistently scan the code.

**Comment by rockstardev** [comment]
@skddc I've changed QR code generator in the meantime...

I'm gonna close this issue to prevent confusion -> and we are opening new issue and new pull request - try to get someone else to independently verify similar problem, because new QR code generator was working for others without problems you mention.

**Comment by pavlenex** [comment]
@rockstardev After the latest update QR codes scanning of Bolt11 invoices works great for me. I no longer have issues, but I saw @skddc's PR so wanted to leave the issue open for a little bit to see if others experience problems. 

For me personally, it's resolved.
