### ISSUE TITLE
[Bug]: Changing number of confirms required for one coin changes it for all of them.

### ISSUE THREAD

**Issue by mattius459** [btcpayserver/btcpayserver#6237]
### What is your BTCPay version?

© BTCPay Server v1.13.5+30d91d0bd (Altcoins)

### How did you deploy BTCPay Server?

Azure

### What happened?

Hello, I have several coins integrated into BTC Pay Server. When I change the number of confirms required for settlement on one of the coins, it changes that for all of them. So for example if I change LTC to 0, it also changes it to 0 for BTC, DOGE, and Liquid.
<img width="484" alt="Screen Shot 2024-09-21 at 7 36 11 AM" src="https://github.com/user-attachments/assets/517229db-1d19-47e3-9708-4f9540c90111">

### How did you encounter this bug?

asdf

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
This is not a bug.

**Comment by mattius459** [comment]
I wanted to add zero conf on LTC because there is no rbf risk. Then all I had to do was create a script to make sure the fee set with LTC payments was sufficiently high, thus enabling instant payments with LTC.

But okay!

**Comment by pavlenex** [comment]
Yeah, you're right, I completely forgot we changed that part of the code. Apologies. 

@dennisreimann this one needs to be investigated, when we moved store confirmations into settings for every payment method, then it needs to reflect changes per payment method, or otherwise be moved to general store settings.

**Comment by dennisreimann** [comment]
@pavlenex Yes, I think it was erroneously moved from the general store settings to the configuration of individual payment methods, because it has been and still is a setting on the store-level.

Even on the invoice level, the speed policy is only defined once, so it is the same for every payment method. Changing this to be per payment method would be a larger change and I'm not sure if this is even necessary.

So shall this be moved back to the general store settings to reflect its functionality?

**Comment by dennisreimann** [comment]
Checked some more, the above goes for all of the payment settings: 

![grafik](https://github.com/user-attachments/assets/15a99b11-fee7-4ffd-8e3a-5c210893d019)
