### ISSUE TITLE
error MSB3883: Unexpected exception:  [/home/vincent/source/btcpayserver/BTCPayServer/BTCPayServer.csproj]

### ISSUE THREAD

**Issue by EchoRC** [btcpayserver/btcpayserver#686]
.NET Core SDK information

$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.505
 Commit:    b220231234

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.505/

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.1.505 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

________________________________________________________________

I want install btcpay server on an aws EC2 instance with .NET Core SDK 2.1.505 installed.

$ cd btcpayserver
$ ./build.sh

Problem:1.First time I run ./build.sh .it's stucked 4 hours and my aws EC2 instance dead as well.
2.I reboot my EC2 instance. and run ./build.sh again.
RED Errors i got:

Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 526.08 ms for /home/vincent/source/btcpayserver/BTCPayServer/BTCPayServer.csproj.
  Restore completed in 73.17 ms for /home/vincent/source/btcpayserver/BTCPayServer/BTCPayServer.csproj.

  Bundler: Begin processing bundleconfig.json
  Bundler: Done processing bundleconfig.json

/usr/share/dotnet/sdk/2.1.505/Roslyn/Microsoft.CSharp.Core.targets(52,5): error MSB3883: Unexpected exception:  [/home/vincent/source/btcpayserver/BTCPayServer/BTCPayServer.csproj]
/usr/share/dotnet/sdk/2.1.505/Roslyn/Microsoft.CSharp.Core.targets(52,5): error : System.ComponentModel.Win32Exception (12): Cannot allocate memory [/home/vincent/source/btcpayserver/BTCPayServer/BTCPayServer.csproj]
/usr/share/dotnet/sdk/2.1.505/Roslyn/Microsoft.CSharp.Core.targets(52,5): error : at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow) [/home/vincent/source/btcpayserver/BTCPayServer/BTCPayServer.csproj]
/usr/share/dotnet/sdk/2.1.505/Roslyn/Microsoft.CSharp.Core.targets(52,5): error : at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) [/home/vincent/source/btcpayserver/BTCPayServer/BTCPayServer.csproj]
/usr/share/dotnet/sdk/2.1.505/Roslyn/Microsoft.CSharp.Core.targets(52,5): error : at System.Diagnostics.Process.Start() [/home/vincent/source/btcpayserver/BTCPayServer/BTCPayServer.csproj]
/usr/share/dotnet/sdk/2.1.505/Roslyn/Microsoft.CSharp.Core.targets(52,5): error : at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [/home/vincent/source/btcpayserver/BTCPayServer/BTCPayServer.csproj]
/usr/share/dotnet/sdk/2.1.505/Roslyn/Microsoft.CSharp.Core.targets(52,5): error : at Microsoft.CodeAnalysis.BuildTasks.ManagedCompiler.HandleResponse(BuildResponse response, String pathToTool, String responseFileCommands, String commandLineCommands) [/home/vincent/source/btcpayserver/BTCPayServer/BTCPayServer.csproj]
/usr/share/dotnet/sdk/2.1.505/Roslyn/Microsoft.CSharp.Core.targets(52,5): error : at Microsoft.CodeAnalysis.BuildTasks.ManagedCompiler.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [/home/vincent/source/btcpayserver/BTCPayServer/BTCPayServer.csproj]

Build FAILED.

/usr/share/dotnet/sdk/2.1.505/Roslyn/Microsoft.CSharp.Core.targets(52,5): error MSB3883: Unexpected exception:  [/home/vincent/source/btcpayserver/BTCPayServer/BTCPayServer.csproj]
/usr/share/dotnet/sdk/2.1.505/Roslyn/Microsoft.CSharp.Core.targets(52,5): error : System.ComponentModel.Win32Exception (12): Cannot allocate memory [/home/vincent/source/btcpayserver/BTCPayServer/BTCPayServer.csproj]
/usr/share/dotnet/sdk/2.1.505/Roslyn/Microsoft.CSharp.Core.targets(52,5): error : at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow) [/home/vincent/source/btcpayserver/BTCPayServer/BTCPayServer.csproj]
/usr/share/dotnet/sdk/2.1.505/Roslyn/Microsoft.CSharp.Core.targets(52,5): error : at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) [/home/vincent/source/btcpayserver/BTCPayServer/BTCPayServer.csproj]
/usr/share/dotnet/sdk/2.1.505/Roslyn/Microsoft.CSharp.Core.targets(52,5): error : at System.Diagnostics.Process.Start() [/home/vincent/source/btcpayserver/BTCPayServer/BTCPayServer.csproj]
/usr/share/dotnet/sdk/2.1.505/Roslyn/Microsoft.CSharp.Core.targets(52,5): error : at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [/home/vincent/source/btcpayserver/BTCPayServer/BTCPayServer.csproj]
/usr/share/dotnet/sdk/2.1.505/Roslyn/Microsoft.CSharp.Core.targets(52,5): error : at Microsoft.CodeAnalysis.BuildTasks.ManagedCompiler.HandleResponse(BuildResponse response, String pathToTool, String responseFileCommands, String commandLineCommands) [/home/vincent/source/btcpayserver/BTCPayServer/BTCPayServer.csproj]
/usr/share/dotnet/sdk/2.1.505/Roslyn/Microsoft.CSharp.Core.targets(52,5): error : at Microsoft.CodeAnalysis.BuildTasks.ManagedCompiler.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [/home/vincent/source/btcpayserver/BTCPayServer/BTCPayServer.csproj]
    0 Warning(s)
    8 Error(s)

Time Elapsed 00:00:08.46

Help needed please. any solution will be appreciated.

**Comment by NicolasDorier** [comment]
`Cannot allocate memory`. Maybe you need more powerful machine. Building BTCPay take normally less than 1 min.

**Comment by vincentyycheung** [comment]
vincent@ip-172-31-31-1:~$ /usr/bin/dotnet run -p ~/source/btcpayserver/BTCPayServer/BTCPayServer.csproj -c ~/.btcpayserver/Main/settings.config --network=mainnet
/usr/share/dotnet/sdk/2.1.505/Roslyn/Microsoft.CSharp.Core.targets(52,5): warning MSB3052: The parameter to the compiler is invalid, '/define:/HOME/VINCENT/_BTCPAYSERVER/MAIN/SETTINGS_CONFIG' will be ignored. [/home/vincent/source/btcpayserver/BTCPayServer/BTCPayServer.csproj]
/usr/share/dotnet/sdk/2.1.505/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Compilation.targets(106,5): warning MSB3052: The parameter to the compiler is invalid, '/define:/HOME/VINCENT/_BTCPAYSERVER/MAIN/SETTINGS_CONFIG' will be ignored. [/home/vincent/source/btcpayserver/BTCPayServer/BTCPayServer.csproj]
Using launch settings from /home/vincent/source/btcpayserver/BTCPayServer/Properties/launchSettings.json...
info: Configuration:  Data Directory: /home/vincent/.btcpayserver/Main
info: Configuration:  Configuration File: /home/vincent/.btcpayserver/Main/settings.config
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  Root Path: /
info: Configuration:  Postgres DB used (User ID=satoshi;Password=satoshi;Host=localhost;Port=5432;Database=btcpayserver;)
info: Configuration:  BTC: Explorer url is http://127.0.0.1:24445/
info: Configuration:  BTC: Cookie file is /home/vincent/.nbxplorer/Main/.cookie
info: PayServer:      Starting listening NBXplorer (BTC)
info: PayServer:      Start watching invoices
info: PayServer:      Starting payment request expiration watcher
info: Configuration:  Listening on http://0.0.0.0:23001
info: Events:         NBXplorer BTC: NotConnected => Synching
info: PayServer:      0 pending payment requests being checked since last run


![btcpay status](https://user-images.githubusercontent.com/48667188/54513264-db4f3e80-4991-11e9-8109-c921976f9abf.png)



![btcpay server syncing](https://user-images.githubusercontent.com/48667188/54513298-f326c280-4991-11e9-8b2d-cdae7aeb21d6.png)
Question: Is this status good or not? anything wrong?

**Comment by NicolasDorier** [comment]
@vincentyycheung if "the node is starting" is stuck, it means your Bitcoin node fails to start.
You need to check why.

**Comment by vincentyycheung** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  thank you so much. I will restart bitcoin                                                                                                                                                                        发送自我的 BlackBerry - 安全智能手机                                                                                                                                                                           发件人： notifications@github.com发送时间： 2019年3月19日 14:00收件人： btcpayserver@noreply.github.com回复： reply@reply.github.com抄送： 545265803@qq.com; mention@noreply.github.com主题： Re: [btcpayserver/btcpayserver] error MSB3883: Unexpected exception:  [/home/vincent/source/btcpayserver/BTCPayServer/BTCPayServer.csproj] (#686)  @vincentyycheung if "the node is starting" is stuck, it means your Bitcoin node fails to start.
You need to check why.

**Comment by vincentyycheung** [comment]
I find your website  https://freedomnode.com/blog/114/how-to-setup-btc-and-lightning-payment-gateway-with-btcpayserver-on-linux-manual-install
 and install the btcpay server on my AWS EC2 instance flow your steps. Thank you so much.

I want to run the btcpay server on my AWS EC2 instance ,and with a raspiblitz raspiberrypi full bitcoin and lnd
node, which was full synced. 
I changed some config for my raspiblitz referenced  https://docs.google.com/document/d/1PyX4R6zQt8tyVl8wkWhphAfFU5q4HatBGv3YvvZX6zE/preview# .

my NBxplore setting.config is :
#18.136.47.20 is my ip.

#cat /home/bitcoin/.bitcoin/bitcoin.conf | grep rpc
#your bitcoin.conf path
btc.rpc.url=http://18.136.47.20:8332/
#this port is for nbxplorer, open it on your server or computer
port=24445
#[YOUR RASPIBLITZ IP/DOMAIN] is your ssh to your raspiblitz
btc.rpc.user=raspibolt
btc.rpc.password=myrpcpassword

my BTCpay server setting.congfig:

network=mainnet
#this port is for btcpay server remote-connection, open it on your server or co$
port=23001
bind=0.0.0.0
chains=btc
#24445 is for nbxplorer open it on your server or computer
BTC.explorer.url=http://127.0.0.1:24445
BTC.lightning=type=lnd-rest;server=https://127.0.0.1:8080/;macaroonfilepath=~/.lnd/data/chain/bitcoin/mainnet/admin.macaroon;certthumbprint=BF:4A:CD:0B:04:BF blabla
postgres=User ID=satoshi;Password=satoshi;Host=localhost;Port=5432;Database=btcpayserver;

my bitcoin.conf:

# bitcoind configuration

# mainnet/testnet
testnet=0

# Bitcoind options
server=1
daemon=1
txindex=1
disablewallet=1

# Connection settings
rpcuser=raspibolt
rpcpassword=myrpcpassword
rpcport=8332
rpcallowip=127.0.0.1
rpcbind=127.0.0.1:8332
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28333
#I add four lines below for NBxplorer
rpcallowip=18.136.47.20/255.255.255.0
whitelist=18.136.47.20


# Raspberry Pi optimizations
dbcache=100
maxorphantx=10
maxmempool=50
maxconnections=40
maxuploadtarget=5000

datadir=/mnt/hdd/bitcoin



my lnd.conf:

# lnd configuration

[Application Options]
debuglevel=debug
maxpendingchannels=50
alias=PANDA's LN3
color=#68F442
nat=false

# RPC open to all connections on Port 10009
rpclisten=0.0.0.0:10009
#I add one line below to set up btcpayserver
rpclisten=127.0.0.1:10008
# REST open to all connections on Port 8080
restlisten=0.0.0.0:8080
# Domain, could use https://freedns.afraid.org
#tlsextradomain=lightning.yourhost.com
tlsextraip=0.0.0.0

[Bitcoin]
bitcoin.active=1
bitcoin.node=bitcoind
# enable either testnet or mainnet
#bitcoin.testnet=1
bitcoin.mainnet=1

[Bitcoind]
bitcoind.rpcuser=raspibolt
bitcoind.rpcpass=myrpcpassword
bitcoind.rpchost=127.0.0.1
bitcoind.zmqpubrawblock=tcp://*:28332
bitcoind.zmqpubrawtx=tcp://*:28333

[autopilot]
autopilot.active=0
autopilot.maxchannels=5
autopilot.allocation=0.6


then :/usr/bin/dotnet run -p ~/source/btcpayserver/BTCPayServer/BTCPayServer.csproj -c ~/.btcpayserver/Main/settings.config --network=mainnet

 I got:
vincent@ip-172-31-31-1xx:~$ /usr/bin/dotnet run -p ~/source/btcpayserver/BTCPayServer/BTCPayServer.csproj -c ~/.btcpayserver/Main/settings.config --network=mainnet
/usr/share/dotnet/sdk/2.1.505/Roslyn/Microsoft.CSharp.Core.targets(52,5): warning MSB3052: The parameter to the compiler is invalid, '/define:/HOME/VINCENT/_BTCPAYSERVER/MAIN/SETTINGS_CONFIG' will be ignored. [/home/vincent/source/btcpayserver/BTCPayServer/BTCPayServer.csproj]
/usr/share/dotnet/sdk/2.1.505/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Compilation.targets(106,5): warning MSB3052: The parameter to the compiler is invalid, '/define:/HOME/VINCENT/_BTCPAYSERVER/MAIN/SETTINGS_CONFIG' will be ignored. [/home/vincent/source/btcpayserver/BTCPayServer/BTCPayServer.csproj]
Using launch settings from /home/vincent/source/btcpayserver/BTCPayServer/Properties/launchSettings.json...
info: Configuration:  Data Directory: /home/vincent/.btcpayserver/Main
info: Configuration:  Configuration File: /home/vincent/.btcpayserver/Main/settings.config
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  Root Path: /
info: Configuration:  Postgres DB used (User ID=satoshi;Password=satoshi;Host=localhost;Port=5432;Database=btcpayserver;)
info: Configuration:  BTC: Explorer url is http://127.0.0.1:24445/
info: Configuration:  BTC: Cookie file is /home/vincent/.nbxplorer/Main/.cookie
info: PayServer:      Starting listening NBXplorer (BTC)
info: PayServer:      Start watching invoices
info: PayServer:      Starting payment request expiration watcher
info: Configuration:  Listening on http://0.0.0.0:23001
info: Events:         NBXplorer BTC: NotConnected => Synching
info: PayServer:      0 pending payment requests being checked since last run

and in my explore: myip:23001
shows:

Your nodes are synching...
×
Some of your nodes are still synchronizing...
BTCPay Server will not create invoices with those cryptocurrencies.

BTC
NBXplorer headers height: 0
The node is starting...

My questions:
1. am I right?
2. the lase line:
info: Events:         NBXplorer BTC: NotConnected => Synching
is that good or not? I have a raspiblitz berrypi full node already, why the BTCpay server is synching? and is it synching the Blockchain? how long it will take?


![btcpay and nbxplorer](https://user-images.githubusercontent.com/48667188/54731443-34ed7e00-4bc9-11e9-8d3c-52761fc709d5.png)
![btcpay status](https://user-images.githubusercontent.com/48667188/54731451-3e76e600-4bc9-11e9-9ac3-aa3432f68231.png)
![btcpay server syncing](https://user-images.githubusercontent.com/48667188/54731457-420a6d00-4bc9-11e9-947c-5ea1452ee239.png)

update：
I check my bitcoin status, it's running

● bitcoind.service - Bitcoin daemon
   Loaded: loaded (/etc/systemd/system/bitcoind.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-03-19 20:35:27 CST; 1 day 14h ago
  Process: 754 ExecStart=/usr/local/bin/bitcoind -daemon -conf=/home/bitcoin/.bitcoin/bitcoin.conf -pid=/h
 Main PID: 762 (bitcoind)
   CGroup: /system.slice/bitcoind.service
           └─762 /usr/local/bin/bitcoind -daemon -conf=/home/bitcoin/.bitcoin/bitcoin.conf -pid=/home/bitc

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
~

@NicolasDorier  Please help me.
Thanks a lot.

**Comment by NicolasDorier** [comment]
I really advise you against setting up things manually and just use the docker deployment for your raspblitz.

You need to checks the log of your bitcoind to know what it is doing.

**Comment by vincentyycheung** [comment]
okay，thanks

**Comment by pavlenex** [comment]
Closing this one, for now, if your issue has not been resolved, feel free to re-open. As said manual deployment is quite tough and not recommended, Docker makes everything much easier.
