### ISSUE TITLE
The invoice can be smaller than 1 satoshi

### ISSUE THREAD

**Issue by kemoantemo** [btcpayserver/btcpayserver#716]
**Describe the problem/bug**
Btcpay make invoices with less than 1 satoshi and it ask to pay 1 satoshi but the invoice value is less than that so why it didn't give an error instead? 
**Your environment**
* Version of BTCPay Server: testned demo site
* Deployment method: 
* Other relevant environment details:

**Logs (if applicable)**
Basic logs can be found in Server Settings > Logs.

**To Reproduce**
Use the api and make invoice with less than 1 satoshi

**Expected behavior**
Give an error and not making invoice

**Actual behavior**
Make ivoice with the value that is less than 1 satoahi but at tje page of paying it asks for 1 satoshi

**Screenshots/Links**
![Screenshot_2019-03-25-16-59-26-220_com android chrome](https://user-images.githubusercontent.com/19779701/54930539-1ae0d200-4f20-11e9-9fb5-57f04ca7e938.png)

**Comment by pavlenex** [comment]
That's because @NicolasDorier has some magic to round-up the amounts. I'm not sure what's the use of it, he'll know to explain it better.

**Comment by NicolasDorier** [comment]
So here is what happen:

1. I should not round up to the smallest value because @pavlenex then complains he can't pay 0.001$
2. I still need to somehow round up any value, or some people start making invoices of 0.0000000010000000000002839713791 USD.
3. Invoice can't be less than 1 satoshi, because on-chain payments can't pay less than 1 satoshi
4. Off chain payment even if in theory can pay less than 1 satoshi, in practice the other party can still your sub satoshi amount, making it useless.
5. Milli satoshi does not make sense for any micropayments. It does not even pay the body calory expenses of taking your wallet out of your pocket, or even moving the mouse on the confirm button.

**Comment by kemoantemo** [comment]
ok it's not the big problem but just putting light of thing i was think it's a bug ty for explanation
