### ISSUE TITLE
Modal pop-up invoice for payment button

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#796]
**Is your feature request related to a problem? Please describe.**
We should give an option to display the payment button invoice in pop-up out of the box, where the user just ticks the checkbox. It makes sense for it to even be checked by default.

**Describe the solution you'd like**
- Add modal invoice support to pay button 
- Add checkbox in the UI

**Describe alternatives you've considered**
Current page redirect is not good UX most of the times.

** Screenshots
I kinda liked the position here, but any other would be okay. Maybe after button size makes even more sense.
![New Mockup 1 copy](https://user-images.githubusercontent.com/36959754/56885884-ee176180-6a6d-11e9-96f6-0d2f9fbf8973.png)

**Comment by Eskyee** [comment]
after the button size would look better, I think too Pav

**Comment by bolatovumar** [comment]
I'm looking at this and it doesn't look like it would be that simple. If we were to enable this, then I assume we would have to ship some JS with the pay button code which we currently do not do. I feel like the pay button code could get very large in that case.

Also, either a new endpoint would need to be created which instead of redirecting to the invoice page would return the invoice id which would be used by the pay button JS to actually open the invoice modal.

**Comment by NicolasDorier** [comment]
@bolatovumar still on it?

**Comment by bolatovumar** [comment]
@NicolasDorier I haven't looked at this in a while. I can come back to this and take another look. My comment above is still valid though, I think.

**Comment by NicolasDorier** [comment]
@bolatovumar I think this is fair to ask the user to add `btcpay.js` to their page for this purpose.
