### ISSUE TITLE
Display app on website root 

### ISSUE THREAD

**Issue by uslsfslwtt** [btcpayserver/btcpayserver#828]
When I select this option on the admin website and select my App that is already setup and working for months now, I Save the change, restart the btcpay services on Raspi via Stop and then Up commands. When I go to the root of my domain name setup for my BTCPAY store, I will get the basic BTCPay website, not my App for donations. Am I missing something to make this work?

**Comment by pavlenex** [comment]
ping @rockstardev possible bug in the app/root setup.

**Comment by pavlenex** [comment]
I tried to replicate this, updated btcpay that had previously set up app on a root domain, and everything remained on the root. I'd have to ask you to provide more information so we can understand the problem, please don't ignore issues template when posting a bug report.

**Comment by britttttk** [comment]
**Describe the problem/bug**
Same issue when I try to display app on website root, and visit my https://btcps0.com it does not bring me to [my app set to show on website root](https://btcps0.com/apps/2CCRTE84cnbSyEsJVvDxsqq9uUJV/pos). 

**Your environment**
* Version of BTCPay Server: v1.0.3.103
* Deployment method: LunaNode

**To Reproduce**
Steps to reproduce the behavior:
1. Set app on website root
2. Go to what I think is website root & login

**Expected behavior**
See app that has been set to display on website root.

**Actual behavior**
I only see app when I navigate to apps and press the view button or use the normal app link.

**Additional context**
What exactly does website root mean? :) @uslsfslwtt sorry to high jack your issue but I am also confused what i'm missing. :D

**Comment by pavlenex** [comment]
@rockstardev this is definitely a bug, when you select the app on which you want to show on a root, it does not show after saving settings for some reason.

**Comment by NicolasDorier** [comment]
Solved by the great @rockstardev in next version!
