### ISSUE TITLE
Payment request with "Allow payee to create invoices" marked, allow to put 0 as payment amount

### ISSUE THREAD

**Issue by rvrv** [btcpayserver/btcpayserver#844]
**Describe the problem/bug**
See title

**Your environment**
BTCPayServer v1.0.3.94

**To Reproduce**
Create payment request with Allow payee to create invoices in their own denomination checked. Try to make payment fo 0.

**Expected behavior**
Validate if payment amount > 0

**Actual behavior**
Payment request for 0 is created.

**Comment by britttttk** [comment]
Hi @rvrv 

If you set the payment request value to $0, your request will not produce invoices to accept payments, See [Example1](https://btcps0.com/payment-requests/0deec04b-cae4-4431-8c8a-71cd765826ff). 

If you set the payment request value above $0, users can make a "payment denomination of $0" because btcpay accepts over payment of invoices. See [Example2](https://btcps0.com/payment-requests/d7554462-e16b-4169-81f5-831becc3b2d9)

You can also modify the POS system to accept payments of any denomination. The link can be shared just like the payment request link. See the [modified Web POS](https://blog.btcpayserver.org/how-to-accept-bitcoin-donations/) section of this blog. See [Example3](https://btcps0.com/apps/3azQ7EFLKjsxaheTSs1wDuYE4oLE/pos)

Does that help with your issue? If not, please explain more about your issue :)

**Comment by rvrv** [comment]
Hi @britttttk 
Thanks a lot for your swift response.

> If you set the payment request value above $0, users can make a "payment denomination of $0" because btcpay accepts over payment of invoices. See [Example2](https://btcps0.com/payment-requests/d7554462-e16b-4169-81f5-831becc3b2d9)

I don't quite understand why this could be the case to allow user to create $0 invoice. Could you elaborate a bit? 

Furthermore i don't see an option to 'Cancel current invoice' in case of payment requests created with my instance of btcpay. This feature is quite new or i missed something?

Thanks again.

**Comment by britttttk** [comment]
> option to 'Cancel current invoice'

Yes please update your server by going to: Server Settings > Maintenance > Update
The cancel feature for payment requests was introduced in a recent version. 

> the case to allow user to create $0 invoice

I think because btcpay is able to produce an address for each invoice request regardless of amount, so it's allowed. There is probably someone else who knows the exact reason for this. 

@rvrv happy to help :)

**Comment by rvrv** [comment]
@britttttk thanks for your feedback.

If there is a real use case for user to be able to create $0 invoice i will appreciate if someone could explain it to me and close this issue afterwards :-)

Cheers!

**Comment by Kukks** [comment]
There's no real use case here. It's just extra work to validate against it and nothing bad happens if you create an invoice of 0 amount since you can cancel it now. I'll look into adding a validation check. :)
