### ISSUE TITLE
Spark wallet logs show UNUSUAL error: Missing inputs

### ISSUE THREAD

**Issue by DebugFuture** [btcpayserver/btcpayserver#885]
**Describe the problem/bug**
 Spark wallet log shows UNUSUAL: 25 error code: -25?error message:?Missing inputs?

Some actions I did after launch: 
1. create an incoming channel
2. received one payment
3. close the channel in spark wallet

**Your environment**
* Version of BTCPay Server: v1.0.3.94
* Deployment method: docker
* Other relevant environment details:

**Logs (if applicable)**
2019-06-10T02:42:17.656Z [UNUSUAL] lightningd(6): Broadcasting tx 020000000001017ecec03ec9ef4...: 25 error code: -25?error message:?Missing inputs?
[SKIPPED] 2

**To Reproduce**
1. Go to '/spark/btc/#/logs'
2. See error

**Expected behavior**
no error

**Actual behavior**
UNUSUAL log

**Comment by pavlenex** [comment]
So the channel closed and you got the money in your on-chain? I don't see what's the problem here besides seeing something you believe is suspicious. If there's a problem you should probably post it in c-lightning repo together with [more in-depth logs.](https://docs.btcpayserver.org/support-and-community/troubleshooting#2-2-2-lightning-network-c-lightning-docker)

**Comment by DebugFuture** [comment]
Thanks @pavlenex . Yes, everything works fine except the 25 error. Sorry I didn't find the related issue before.
