### ISSUE TITLE
Need translations for Lightning

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#89]
This [new commit](https://github.com/btcpayserver/btcpayserver/commit/53c53b98e638331734ab804663196bd9c128b41e) added some strings to translate.

- [x] English @ lepipele
- [x] Icelandic @Saevar2000
- [x] Spanish @marcosrdz
- [x] Japanese @junderw
- [x] Dutch @LinoxBE
- [x] German @lepipele
- [x] French @NicolasDorier
- [x] Czech @pajasevi
- [x] Portuguese @rsandrade

![image](https://user-images.githubusercontent.com/3020646/38127364-d59945a2-3430-11e8-8ed9-02889b28d00e.png)

If you prefer not being pinged when a new translation is needed, let me know!

**Comment by NicolasDorier** [comment]
Renamed "Peer Info" to "Node Info" to match the standard lightning terminology.

**Comment by LinoxBE** [comment]
For the Dutch update: https://github.com/btcpayserver/btcpayserver/pull/90.

**Comment by lepipele** [comment]
I've merged German translations to master in order to close this issue and do cleanup... here is PR:

https://github.com/btcpayserver/btcpayserver/pull/121

Also, we now have new batch of translations here: https://github.com/btcpayserver/btcpayserver/issues/119 another reason why I wanted to close this. Again, if we can get native speaker to review these... it would be awesome ;)

**Comment by mutedstorm** [comment]
@lepipele I'm German i could help you with the German translation

**Comment by lepipele** [comment]
Awesome @mutedstorm ... can you take a look at this file and fix any errors:

https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/wwwroot/checkout/js/langs/de.js

If you can please create Pull Request so that we can automatically merge... if not you can also send me file directly, whatever is easier for you.

**Comment by mutedstorm** [comment]
Done
