### ISSUE TITLE
RequiresRefundEmail on store

### ISSUE THREAD

**Issue by Laeka** [btcpayserver/btcpayserver#901]
Basically it more a question,iam trying to add a RequiresRefundEmail on the app store but is not working. any idea how i can do this... thank u
![image](https://user-images.githubusercontent.com/50962181/60355751-c755a880-9994-11e9-9ca4-5a21bd01233f.png)

**Comment by pavlenex** [comment]
You can show that on the invoice itself, Store Settings > Checkout Experience > Refund e-mail?

**Comment by Laeka** [comment]
yes i know but i want to show that option on the app store too, so when i go to the app i can check or uncheck that option.

**Comment by britttttk** [comment]
To me, this is a bit confusing UI to allow the user to check or uncheck an email refund box prior to paying but I understand your request. 

For example, on a donation link, I can request email so that if it is someone I know, I can thank them or they can provide some indication of who/why they're donating since there is no other field for text input. But I think many new users who just want to see the invoice and check it out, don't want to put an email and don't really think to provide a fake one... so they close it and don't see btcpay invoice. 

I believe that this issue could maybe be addressed in #863 possibly or maybe there could be a skip button under the email field?

**Comment by Laeka** [comment]
Because if I have 2 store applications in a store, and one of them does not want that option and the other does, I can not because I would have to enter the store settings every time it is required to modify it. For that reason I think it would be convenient that this option appears in the application of the store as in the attached image.... Sry for bad english.

**Comment by pavlenex** [comment]
Just create 2 separate stores with same xpubkey and tie app1 to store 1 and app2 to store 2.
