### ISSUE TITLE
When logged in, the URL /account/login is still accessable

### ISSUE THREAD

**Issue by woutersamaey** [btcpayserver/btcpayserver#916]
**Describe the problem/bug**
When you are logged in, you can still open `/account/login` and see a login form.

**Your environment**
* Version of BTCPay Server: Latest
* Deployment method: Docker
* Other relevant environment details: Nothing special

**To Reproduce**
1. Login
2. Point your browsers to domain.com/account/login
3. You will see a login form, even though you are already logged in

**Expected behavior**
Redirect to the same page as after a successful login.

**Actual behavior**
We see a login form but don't need to see that

**Comment by pavlenex** [comment]
I noticed this as well yesterday, well spotted.

**Comment by woutersamaey** [comment]
Another thing I noticed is that some URLs are have Capitals while most URLs are all lowercase. 
The app is case insensitive, so didn’t want to report this as a real issue. Would be prettier though. 

After looking at the code, it seams the “route” is not set for the Capitalized controllers. Maybe someone can fix both in 1 swoop?

**Comment by NicolasDorier** [comment]
In 1.0.3.124

**Comment by NicolasDorier** [comment]
Note that  `https://btcpay.blah.org/Account/Login?ReturnUrl=%2Fapps` does not redirect to '/apps' if you are already logged in.

The reason is that BTCPay, if you request a ressource you have no permission on, will redirect to /login. But if you redirect to the ReturnUrl then you would go back to the permissioned resource which will redirect you to login.... resulting in infinite redirect loop.

**Comment by woutersamaey** [comment]
@NicolasDorier nice!!

Also, what about the uppercased URLs fragements on some pages? Or is it a "won't fix"?

**Comment by NicolasDorier** [comment]
Open an issue so I feel some reward closing it then.
