### ISSUE TITLE
Decimal denomination in the crowdfuding header

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#926]
**Describe the problem/bug**
Denomination in the header has 7 decimals, in the wallet, we have 6, 6 is also standard for BTC denomination.

**Your environment**
* Version of BTCPay Server:  v1.0.3.124
* Deployment method: Docker

**To Reproduce**
1. Go to Crowdfunding app
2. Hover over the amount in BTC, see 7 decimals.
3. Go to the wallet, check the amount it's 6 decimals.

**Expected behavior**
The value in the wallet and in crowdfunding should be the same.

**Actual behavior**
The denomination is different in wallet and crowdfunding app.

**Screenshots/Links**
![Screen Shot 2019-07-16 at 23 22 59](https://user-images.githubusercontent.com/36959754/61330778-ac05ec80-a820-11e9-9516-89949368c3b2.png)

**Comment by bitcoinbrisbane** [comment]
Seems to be an error in the .toFixed method on the `/wwwroot/bundles/crowdfund-bundle-1.min.js`.  Just need to work out where it gets bundled from.

```{return parseFloat(this.srvModel.info.currentAmount+this.srvModel.info.currentPendingAmount).toFixed(this.srvModel.currencyData.divisibility)},percentageRaisedAmount:function(){return parseFloat(this.srvModel.info.progressPercentage+this.srvModel.info.pendingProgressPercentage).toFixed(2)}```

**Comment by bitcoinbrisbane** [comment]
Seems odd, because https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/CurrencyValue.cs#L13 loads Bitcoin with divisibility = 8

**Comment by pavlenex** [comment]
My bad, so divisibility is the crowdfunding is 7 when it should be 8 there.
@Kukks can you elaborate if this is a minor bug or intentionally set for any reason?

**Comment by bitcoinbrisbane** [comment]
Probably a discrepancy on how js (tool tip) and .net (wallet) round.

**Comment by Kukks** [comment]
> My bad, so divisibility is the crowdfunding is 7 when it should be 8 there.
> @Kukks can you elaborate if this is a minor bug or intentionally set for any reason?

It's an issue

**Comment by bolatovumar** [comment]
The underlying issue here is that trailing zeros aren't included in numbers (as expected) but we want to have them when rendering them as strings in our view so we need to do a `.toFixed`.

A related issue here is that you get a tooltip even if you don't have any LN contributions so your tooltip doesn't add anything. See here:

![Screen Shot 2019-08-23 at 11 53 56 AM](https://user-images.githubusercontent.com/1934678/63580381-5cdc7580-c59d-11e9-861d-4a5a03679e09.png)

I wonder if this tooltip should be updated to only show up if there are at least two lines of items to show. In this case the tooltip would actually be useful and wouldn't just show the same info as what's below it.

**Comment by pavlenex** [comment]
> I wonder if this tooltip should be updated to only show up if there are at least two lines of items to show. 
@bolatovumar That's a good idea actually.
